### ISSUE TITLE
suggestion graphviz ui : display node and reltype selectors before loading the graph

### ISSUE THREAD

**Issue by ophileon** [structr/structr#104]
Now the entire graph is loaded from start, could take long, and result is an overload of nodes. Why not this sequence

- load nodetype and reltype selectors 
- user makes selection
- user enters search term
- query is executed and limited to selected nodetypes and reltypes
- display nodes and rels

**Comment by vigorouscoding** [comment]
I think this should also be (at least partially) done. The node types are loaded upon displaying the "Graph" section of structr-ui. Then the user does not need to make a selection of node types as this is done via the cypher- or the REST-query.
Relationship types are displayed in the reltype box when one of a type exists and can then be hidden.

**Comment by vigorouscoding** [comment]
I think we'll close this one as the graph section has evolved quite a bit and the issue seems to be corrected
