### ISSUE TITLE
Schema: PropertyParser / DatePropertyParser does not handle pattern with ":" correctly

### ISSUE THREAD

**Issue by cmorgner** [structr/structr#132]
This is because internally, the field separator for the default value is ":", so a date pattern like dd.MM.yyyy HH:mm:ss is misinterpreted as a default value both by the backend and the Ui.

**Comment by amorgner** [comment]
This was fixed a couple of months ago, closing.

![screen_083](https://cloud.githubusercontent.com/assets/291266/12115190/4e083cb8-b3b0-11e5-8e3b-ce33d60e75c2.png)
