### ISSUE TITLE
Node filters in Dashboard RC2 not working?

### ISSUE THREAD

**Issue by ophileon** [structr/structr#152]
Custom node types and rel types do not appear.

![screen shot 2014-05-10 at 10 09 38](https://cloud.githubusercontent.com/assets/3007812/2935576/bf65ae40-d81a-11e3-9bbe-91482d3b1baf.png)

**Comment by amorgner** [comment]
The Graph view (formerly under the "Dashboard" menu entry) was replaced by a new implementation which doesn't have this bug.
