### ISSUE TITLE
RC2. viz in Dashboard does not display rels. 

### ISSUE THREAD

**Issue by ophileon** [structr/structr#154]
I run this cypher

match (s:RcNode)-[:RS]->(t)-[:RE]->(e:RcNode)
return s,t,e

and filter settings are 
![screen shot 2014-05-10 at 11 22 48](https://cloud.githubusercontent.com/assets/3007812/2935699/b2d75c6e-d824-11e3-8b8d-9231b998e005.png)

viz only returns the nodes, not the connecting  [:RS] and  [:RE] rels

![screen shot 2014-05-10 at 11 24 58](https://cloud.githubusercontent.com/assets/3007812/2935707/01ec6628-d825-11e3-87d3-bf8bea6993aa.png)

**Comment by amorgner** [comment]
Also fixed long time ago with new implementation of Graph viz.
