### ISSUE TITLE
OWNS default type.

### ISSUE THREAD

**Issue by jmatsushita** [structr/structr#164]
Hi there,

I guess I'll probably not be the only one trying to model ownership relationships in Structr and entering a relationship type collision with the default OWNS relationship type. How about _OWNS?

Jun

**Comment by amorgner** [comment]
With the latest snapshot (will be included in release 1.1), you can use OWNS as relationship type. Structr  will then make the custom relation class implement the ``Ownership`` interface so that it's compatible with the built-in security layer.
