### ISSUE TITLE
AccessControllable shows up on Schema

### ISSUE THREAD

**Issue by jmatsushita** [structr/structr#174]
Hi there,

I've been playing with [more complex data structures in gists](https://gist.githubusercontent.com/jmatsushita/28534761b0ad3d485a03/raw/2c96bbe7545bfd4f0187206c6f281ecdd0edf8f7/OpenOil-Structr) and sometimes after clearing the schema and reimporting an AccessControllable Type shows up (which I guess is a system type).

![image](https://cloud.githubusercontent.com/assets/356097/3388691/4eccf018-fc8b-11e3-81f6-fba0cbcc5796.png)

**Comment by amorgner** [comment]
Fixed, closing.
