### ISSUE TITLE
Cannot have polymorphic relationships

### ISSUE THREAD

**Issue by jmatsushita** [structr/structr#176]
Hi there,

Still working on the same data model. On branch ```develop``` of Structr. With [this Gist](https://gist.githubusercontent.com/jmatsushita/28534761b0ad3d485a03/raw/889ae29d43545d83131521249a5fc01b6160f24a/OpenOil-Structr) the HAS_DOCUMENT type or IS_OWNER relations aren't imported which I think is because they are both meant to link different Types. IS_OWNER can be between 2 companies or between a country and a company, while HAS_DOCUMENT can be between a Contract and a Document or between a Company and a Document.

If I [update the gist](https://gist.githubusercontent.com/jmatsushita/28534761b0ad3d485a03/raw/18036ab1211e7f5f70c6da4d5a38dac29d82aeca/OpenOil-Structr) to have different relationship types 

Then the import works fine and the relationships are created.

This type of polymorphic relationship type declaration of course works in neo4j.

Is that by design? Are you hoping to allow this to happen? I have created [a gist with only one of these relationship types](https://gist.githubusercontent.com/jmatsushita/09e142ef14759f1c14c5/raw/bdc07d6fb506e69dd34dc77b092a3fc936707da6/OpenOil-Structr-Monomorphic). If I add the second types by hand with the same name. Is that going to create problems down the road?

Cheers,

Jun

**Comment by amorgner** [comment]
Over the past month, the schema support in Structr has improved a lot.

@jmatsushita Is there a chance for you to try a recent snapshot version and see if you can accomplish what you tried to do a year ago, or should we just close this issue?

**Comment by eric-schleicher** [comment]
reading through this..  is the task here to take a class inherit from more than one existing entity?  I have a usecase for this.

**Comment by amorgner** [comment]
What should we do with this issue? I'm tempted to close it as we try to focus on features/bugs here, moving discussions over to https://structr.org/forum.

That said, I'll close it as the original issue is more than one year old and the @jmatsushita still seems to hold his breath (see above) :-)
