### ISSUE TITLE
Quick and easy UX enhancements

### ISSUE THREAD

**Issue by cmorgner** [structr/structr#191]
This issue is intended to act as a container for small changes that can improve user experience.

#### Really helpful
- [x] Add shortcut for editing a CSS file with one click
- [x] Add shortcut for editing an element's `class` attribute
- [x] Add (configurable?) shortcuts for editing an element's HTML attributes
- [x] Make "embed in element" function available for more elements than just &lt;a&gt;
- [x] ...

#### Nice to have (a.k.a. Structr 1.1)
- [x] Alternative pager (direct page selection) in the pages tree view
- [x] Clean up dialog texts
- [x] Make dialog descriptions more precise 
- [ ] Nice to have: add select box to choose from available CSS classes
- [x] Add shortcut overlay somewhere (?) with the most useful items
- [x] Context-aware dialogs
- [x] Backend-supported autocompletion

**Comment by amorgner** [comment]
Almost any of the issues mentioned here (formulated back in 2014!) were addressed over time, so safely closing this issue.

Note: Giving (admin/editor) users the option to select/deselect available (user-defined) CSS classes in the Structr backend UI doesn't make sense. Defining the CSS for a user-facing page/site is done by writing CSS files in the user domain, so the interface is a text editor.
