### ISSUE TITLE
Ui: add dialog options for popular node parameters

### ISSUE THREAD

**Issue by cmorgner** [structr/structr#201]
I'm thinking of a select box with options like
- Hide if a user is logged in
- Hide if no user is logged in
- Hide if collection X is empty
...

**Comment by amorgner** [comment]
Seems a bit too unspecific, lacking context. There are so many places in the Structr backend UI with node parameters.

I'd rather close this one and ask you to create new issues with specific feature requests and a detailed description what you mean, thanks. :-)
