### ISSUE TITLE
Do not automatically index all dynamic properties

### ISSUE THREAD

**Issue by cmorgner** [structr/structr#207]
Whether a property is indexed or not should be selectable in the Schema Editor.

**Comment by ravensorb** [comment]
I am not sure I understand the value of this one -- it would actually be a nice feature to easily enable indexing of additional properties (especially custom ones).

**Comment by amorgner** [comment]
By default, any custom property/attribute is indexed.  Indexing attributes (esp. in Structr where all attributes are indexed in both, a fulltext and an exact index) is expensive, so having more control of the indexing of particular attributes would help keeping the database indexes compact, or, OTOH, make attributes available for (fulltext/exact) search.

**Comment by ravensorb** [comment]
So wouldn't that indicate that a good feature would be to allow for us to enable/disable indexing on a property by property basis and maybe disable the majority by default?

Example:  Right now height and width of images and videos are not indexed -- I would like to enable this, however there is no way to do this (that I can find).

**Comment by amorgner** [comment]
For built-in properties, this can only be set in the Java code.

**Comment by amorgner** [comment]
You can now enable/disable indexing for custom properties, but allowing to change the indexing behaviour for built-in (Java-based) types would be to much of a risk as it could lead to malfunction of the core system.
