### ISSUE TITLE
Importing Graph Gist into hosted Structr instance - spinning but no completion

### ISSUE THREAD

**Issue by legalba** [structr/structr#212]
![structr_import_cycling](https://cloud.githubusercontent.com/assets/7526415/3500557/5ac10ab4-060c-11e4-89e4-d174735cc24d.png)

Hi, I'm trying to import a graph gist on my hosted instance but when I press 'import' I just get a constant spinner, but it never completes. I can run the same Graph Gist on Neo4J gist page and it works. 

Is it timing out on the back end? 

How can I troubleshoot?

I've cut-down my original Graph Gist so it only has CREATE Cypher but still no import.

RAW below:
https://gist.githubusercontent.com/legalba/f1e8aac89aa5ca07284d/raw/32458cba0939a3be9872a6be3f6b97581be36672/leon-2

**Comment by amorgner** [comment]
Closing, too old.
