### ISSUE TITLE
Make POST parameters available in user-defined methods

### ISSUE THREAD

**Issue by hwloh** [structr/structr#219]
It is currently not possible to access POST parameters in methods (e.g. onCreate01) defined against a node type.

**Comment by cmorgner** [comment]
Is this still relevant? There is a recent change that allows passing of a JSON body into those methods making the key-value pairs available via the `retrieve()` method.

**Comment by hwloh** [comment]
Will the retrieve() method work in onCreate too? It would be great if it did. I still have to resort to adding dummy fields to some of my content types in order to pass additional parameters in to the onCreate method. I ended up moving all my schema definition into a java module as the logic I needed to perform in my custom methods couldn't easily be done using the functional approach provided in the schema editor (also has the benefit of easy version control). When implementing custom methods in java I noticed that you can access the POST parameters by specifying them as function parameters of the custom methods. Unfortunately I didn't manage to get at the POST parameter in any overridden onCreation method. By the time the overridden onCreation method is called the object that parses the POST data has already consumed it and you can't access it again.

Cheers,

Holger

**Comment by amorgner** [comment]
I think this possible now. @vigorouscoding Could you shed some light onto this?

**Comment by vigorouscoding** [comment]
I just tested this with the current master - you can access the parameters in "regular" schema methods via "retrieve()". In the onCreate method this is currently not possible

**Comment by amorgner** [comment]
Leaving this open as the original question was regarding ``onCreate`` methods.

**Comment by amorgner** [comment]
Just checked again. There are two ways to access the paramters in `onCreate` methods:

1. Create an attribute, f.e. 'bar', in the schema and access the data after creation of a new object (this is what happens when POSTing to a type resource), and then retrieve the value with `get(this, 'bar'))`.

2. If you want to process data from the request before creating the object, pass it as URL paramters, like f.e. `POST http://0.0.0.0:8082/structr/rest/foo?bar=test123` and retrieve it by `request.bar`.

Does that help?

**Comment by cmorgner** [comment]
Is this still relevant? Please comment or close, thank you!

**Comment by amorgner** [comment]
Thought about this again. The attributes passed to the type resource by POST to create new objects have to be validated against the schema, so they should not be repurposed as custom attributes.

At the moment I can't think of a case where this could not be resolved by using another custom method or request parameters, but I think we should be open to a discussion if this comes up again.
