### ISSUE TITLE
Make template importer support assets referenced by @import 

### ISSUE THREAD

**Issue by amorgner** [structr/structr#225]
Things like

```
<style type="text/css">@import "style.css";</style>
```

should be supported as well.

**Comment by cmorgner** [comment]
This issue is two years old, what is the status here?

**Comment by amorgner** [comment]
Added support for `@import` in CSS to the importer.

The following cases are covered (see https://developer.mozilla.org/en-US/docs/Web/CSS/%40import):

	@import url("a.css") print;
	@import url("b.css") projection, tv;
	@import 'c.css';
	@import url("d.css/");
	@import "e.css" screen, projection;
	@import url('f.css') screen and (orientation:landscape);
