### ISSUE TITLE
Make relationships editable

### ISSUE THREAD

**Issue by ghost** [structr/structr#227]
I saw on a blog somewhere that you have plans to change the frontend so that users can modify relationship properties. I went through the issues on Github, but didn't find anything that mentions it.

In schema editor, I can define properties for a relationship between nodes. I can even create or modify those properties via REST. Unfortunatelly, relationships cannot neither be listed nor be modified in the frontend.

In the top-level menu, there is an item called 'Data', which details all available node types (each node-type has a separate submenu and with its own table of properties).

I suggest:
1) Change the 'Data' top-level menu item to something like 'Node data'.
2) Add a new top-level item called 'Relationship data'. This new submenu will have similar logic as the 'Node data': a submenu will be populated with user-defined relationship types and every sub-menu item will show a relationships table (listing all the relationships of a given type per row with columns populated with user-defined relationship properties plus some system properties). User-defined properties should be editable.

From my (narrow) point of, all the nodes and the relationships have a reference UUID, so listing or accessing those data in a table should be possible.

Thank you for your great work on structr!

Petr

**Comment by amorgner** [comment]
@dave-lee-hk 
To 1:: I agree, working with UUIDs is not feasable. Editing relationships will be done in a graph-style editor in a future release, probably 1.2 (ETA: mid 2015)
To 2.: The auto-naming for attributes does not always yield best results. You can rename the Remote Attributes, in your case maybe ``pupils`` and ``teachers`` fits better?

**Comment by amorgner** [comment]
@brady77 In the latest snapshot is a fix for displaying source and target node of a relationship with the name label, see 89cffd506926ca5830111b196130578edd092c1c.

Leaving this issue open. We need to fix the rel type/underscore problem.

**Comment by cmorgner** [comment]
What is the status of this issue?

**Comment by amorgner** [comment]
I think this can safely be closed as relationships are editable in the Graph section since version 2.0.
