### ISSUE TITLE
Improve file manager

### ISSUE THREAD

**Issue by cmorgner** [structr/structr#229]
Create a unified, pageable file manager ui

**Comment by amorgner** [comment]
We're working on this. A lot of files-related stuff will be added to 2.0.

**Comment by amorgner** [comment]
A first version of the new file manager was recently added to the master branch:

![structr-filesystem-browser](https://cloud.githubusercontent.com/assets/291266/10350501/9f4b11e8-6d44-11e5-9375-e07a829c119f.png)

**Comment by amorgner** [comment]
The new file manager has been kind-of finished with release 2.0. Many more enhancements to come, but enough to close this issue. :-)
