### ISSUE TITLE
Add file synchronisation with GitHub

### ISSUE THREAD

**Issue by amorgner** [structr/structr#243]
We're thinking about adding a direct synchronization between GitHub and Structr's file system, using their API (https://developer.github.com/v3/repos/contents/).

Ideally, you could then import files from GitHub directly into Structr and keep them in sync. Editing a file in Structr would update it in the git repo on GitHub, new versions edited outside of Structr would be automatically synchronized to Structr's file system.

As soon as there are enough users upvoting this feature, we would start planning.

**Comment by eric-schleicher** [comment]
++1 (for schemas too)

**Comment by cmorgner** [comment]
@amorgner can this be closed?

**Comment by whatSocks** [comment]
Why not make it easier to commit changes to a local repo and push to whatever remote they want?

**Comment by vigorouscoding** [comment]
I'll close this issue as we have created a file-based exchange format for structr applications (see https://support.structr.com/article/428)
These files can be checked in to any repository the user wishes (so we are not limiting us or our users to GitHub - even though GH is awesome)
Using this method we can decide what else we check in to the repository and can also put project-specific documentation etc in the repository without it automatically being imported into structr.

Our repositories look something like this most of the time:
```
example-repository
|-- documentation
|-- import-data
|-- requirements
|-- test-data
`-- webapp
````
