### ISSUE TITLE
Importing nodes with multi-labels fails to create relationships

### ISSUE THREAD

**Issue by adeze** [structr/structr#249]
Hi,
I've imported data via the methods similar to https://github.com/structr/structr/issues/183
(and finally! got it all working in neo4j)
however, my domain model/nodes have multi-labels representing an object hierarchy.

although my import cypher script works for neo4j (2.1.4), including creating relationships,
structr 1.0 only recognises the data (and the hierarchy!) , but fails to create relationships for those nodes. it works ok for nodes with only one label/type though.

not sure if its a bug or by design.

my potential workaround is to strip the multiple labels from the create node script, and then create the hierarchy manually in the schema editor. Is this my best option?

**Comment by cmorgner** [comment]
Closing this issue because the problem seems to be solved.
