### ISSUE TITLE
Serve docs locally

### ISSUE THREAD

**Issue by lazaridis-com** [structr/structr#251]
The docs are now in the repo within docs/markdown (see #246)

If I understand things correct, structr-ui could serve those md files.

A possible implementation would be, to have a config option, which points to the doc folder, which is then mapped to a url.

Something like (suggestions, I don't know the project structure yet):

localhost:8082/docs or localhost:8082/structr/docs => shows the docs
localhost:8082/structr = shows the usual structr-ui

This has the huge benefit that every instance has the correct documentation, even off-line. If a user does not want this, he just changes the config file to show no docs, or to show his own docs.

**Comment by amorgner** [comment]
We've decided to stick with online documentation only for now.
