### ISSUE TITLE
Suggestion for Structr's Introductive Summary

### ISSUE THREAD

**Issue by lazaridis-com** [structr/structr#258]
The current README starts with:

> Structr (pronounce it like 'structure') is a Java framework for mobile and web applications based on the graph database Neo4j. It was designed to simplify the creation of complex graph database applications by providing a comprehensive Java API and a set of features common to most use cases. This enables developers to build a sophisticated web or mobile app based on Neo4j within hours.

After one week on docu level, it seems to me that the above is a bit of an understatement. Please check if the following text suggestion contains factual errors:

Structr (pronounced: 'structure') is a Next Generation Graph CMF (Content Management Framework) based on the Java Graph Database Neo4j.

You can use Structr to create simple browser or mobile based web applications in hours. Those applications can then evolve and scale up to sophisticated distributed graph database systems.

Structr reduces your Neo4j teach-in-time dramatically, providing you with tools like a Visual Schema Editor and much more. Once you reach expert level, you can use the comprehensive Java API, or go down to the native Neo4j API itself.

And now the best: it's Open Source - you can try it in a matter of minutes.

**Comment by amorgner** [comment]
Thanks everyone for your suggestions. Let's agree that it's really hard to find the right words to describe what Structr is. I'll close this issue, as this discussion doesn't really belong here.

For 2015 and beyond, we'll try to coin a term around the thought of Structr being an application platform, with an unprecedented flexibility and integratability.
