### ISSUE TITLE
Make attribute(s) for data object lookup configurable 

### ISSUE THREAD

**Issue by amorgner** [structr/structr#259]
In 1.0, data objects are found by UUID or 'name' attribute lookup against the last part of the URL, e.g.:

/projects/2fe0fbaf7f29451282e6c0304b6b616f => Displays object with UUID ``2fe0fbaf7f29451282e6c0304b6b616f`` on the 'projects' page

/projects/just-another-project => Displays object with ``name="just-another-project"`` on the 'projects' page

It would be a great enhancement if one could define custom attributes that serve as a lookup parameter.

See also this thread in the Structr group: https://groups.google.com/forum/#!topic/structr/MpTwFtJBVpk

**Comment by eric-schleicher** [comment]
hello @amorgner ...  This is coming up again...   

Q1: Right now how does structr handle entities of differing types with the same name value?

Extending the example provided above; say we had two entity types (say OldProject and NewProject) each have their own nodes (with differernt uuids) but the same 'name' value for the name value what happens?  

I'm highlighting that attribute uniqueness is enforced @ an entity, level, but this lookup for determining which uuid to provide for rendering is a global search (correct?)

In this scenario (two node with same values in different entities), what is the behavior?  Return first found?

Related, but distinct Q:  Barring previously mentioned issues wrt:canonical names across entity types; what is the ordering of operations for a function.

can one set  the 'name' in #schema to be a function:  clean(userDefinedName) and have validation respect the uniquenes of the resulting value?  if so i believe that i can use this strategy to get closer to what i would like for clean urls.

**Comment by eric-schleicher** [comment]
@amorgner  can you comment on the expected behavior of the system when a value after the base / is provided?  

How will structr scan for matching 'name' values?

just curious
