### ISSUE TITLE
Simplify Getting Started

### ISSUE THREAD

**Issue by lazaridis-com** [structr/structr#260]
Currently, the Readme points to the following getting started:

http://vimeo.com/53235075

This is a 10min. video, which seems outdated, too.

The Getting Started should be simplified, ideally in a way that a few written instructions (provided either within the README, or within a file in the source-tree) are enough to get started.

**Comment by amorgner** [comment]
The discussion about creating video tutorials or not doesn't really belong here, so closing this.
