### ISSUE TITLE
backwards pointing relationship and missing properties

### ISSUE THREAD

**Issue by rconstantine** [structr/structr#277]
![screenhunter_05 oct 20 15 54](https://cloud.githubusercontent.com/assets/8312587/4710613/353a4d80-58ac-11e4-83f3-720631e83ec6.jpg)

I exported Neo4j 2.1.4 data using export-graphml and visually inspected the file. All was as expected, so far as I could tell. 

I then imported to structr using import-graphml and it appeared to go OK except that I have two relationships which should have properties in them, but the properties aren't there. One of them is also backwards. Add to that the fact that two relationships have overlapped on the display and I can't seem to access the one underneath.

It seems that despite checking out the latest git of structr, which is apparently 1.1 SNAPSHOT, the Neo4j version employed is still 2.0.4. I was under the impression it would be a later version.

In any case, I'm wondering if the version discrepancy is to blame, or if the data is there but structr can't read it correctly. I do have underscores in my relationship names and I read somewhere that this may be a problem.

What other information should I share here that might help in figuring out my issue?

**Comment by amorgner** [comment]
@rconstantine Would you mind retesting this issue with one of the latest snapshot versions?

**Comment by amorgner** [comment]
No response, closing.
