### ISSUE TITLE
FTP-Problem

### ISSUE THREAD

**Issue by vigorouscoding** [structr/structr#281]
I encountered a problem today when editing my files via FTP.

I saved my file "app.js" and get the following error message.

![screen shot 2014-10-23 at 12 08 10](https://cloud.githubusercontent.com/assets/3099108/4751378/449ae1f2-5a9d-11e4-801f-58a5b59a6e09.png)

I hit "try again" and everything looked fine, but my app stopped working.

The file-node "app.js" had been removed and recreated - which means that it had been removed from the page as well - only an empty script tag remained. (it happened multiple times today - see the screenshot)

![screen shot 2014-10-23 at 12 10 45](https://cloud.githubusercontent.com/assets/3099108/4751392/741f60ec-5a9d-11e4-9d5a-af1a10dc4195.png)

**Comment by amorgner** [comment]
@vigorouscoding Would you mind re-testing this issue with the latest ``master`` build? Thanks a bunch.

**Comment by vigorouscoding** [comment]
# Part 1

OK - I think I know now how this happens: The FTP client sends the "IDLE" command and afterwards needs to reconnect because structr is not listening any more. At least thats what I make of it - I only get this error after an IDLE command... (see the attached log)
It seems that is a Cyberduck-specific problem. In version 4.2.1 Cyberduck reopens the connection and everything works fine. Version 4.5.2+ don't reconnnect and get an error message - in the more recent versions a more descriptive yet misleading one:

![screen shot 2015-01-04 at 10 41 59](https://cloud.githubusercontent.com/assets/3099108/5605483/55161fde-93fe-11e4-9e5b-9695e2fbd40f.png)


	10:32:18.735 [pool-5-thread-37] INFO  o.a.f.listener.nio.FtpLoggingFilter - IDLE
	10:32:18.735 [pool-5-thread-37] INFO  o.a.ftpserver.impl.DefaultFtpHandler - Session idle, closing
	10:32:18.735 [pool-5-thread-37] INFO  o.a.f.listener.nio.FtpLoggingFilter - CLOSED
	Jan 04, 2015 10:32:18 AM org.structr.files.ftp.StructrFileSystemView dispose
	INFO: dispose() does nothing







# Part 2

I found a more severe problem with Cyberduck. Newer versions break structr file-uuids in a really stupid way: Saving a file will DELE the original, upload the new file to "filename-somehash" and then RNFR,RNTO the file back to its original name hence "changing" the files uuid.
Even downloading (for editing purposes - not the default downloading) an unknown file results in a changed uuid because Cyberduck does the same for this scenario.


	10:20:11.709 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: CWD /
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /
	10:20:11.711 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 250 Directory changed to /

	10:20:11.711 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: TYPE A
	10:20:11.711 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 200 Command TYPE okay.

	10:20:11.711 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: PASV
	10:20:11.712 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 227 Entering Passive Mode (127,0,0,1,198,169)

	10:20:11.713 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: MLSD
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: ./
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of / requested
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: 12 folders found
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /assets
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /https:
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /fonts
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /dist
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: 23 files found
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: 2 pages found
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /assets requested
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /assets/js
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /https: requested
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /https:/ajax.googleapis.com
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /fonts requested
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: File found: /fonts/glyphicons-halflings-regular.ttf
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: File found: /fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: File found: /fonts/glyphicons-halflings-regular.eot
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /dist requested
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /dist/js
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /dist/css
	10:20:11.726 [pool-5-thread-23] WARN  o.apache.ftpserver.impl.PassivePorts - Releasing unreserved passive port: 50857
	10:20:11.726 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 150 File status okay; about to open data connection.

	10:20:11.726 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 226 Closing data connection.

	10:20:11.739 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: TYPE I
	10:20:11.740 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 200 Command TYPE okay.

	10:20:11.740 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: PASV
	10:20:11.740 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 227 Entering Passive Mode (127,0,0,1,198,171)

	10:20:11.741 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: RETR /dings.js
	Jan 04, 2015 10:20:11 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /dings.js
	10:20:11.742 [pool-5-thread-24] INFO  o.apache.ftpserver.command.impl.RETR - File downloaded /dings.js
	10:20:11.743 [pool-5-thread-24] WARN  o.apache.ftpserver.impl.PassivePorts - Releasing unreserved passive port: 50859
	10:20:11.743 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 150 File status okay; about to open data connection.

	10:20:11.743 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 226 Transfer complete.

	10:20:12.817 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: CWD /
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /
	10:20:12.818 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 250 Directory changed to /

	10:20:12.818 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: TYPE A
	10:20:12.818 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 200 Command TYPE okay.

	10:20:12.819 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: PASV
	10:20:12.819 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 227 Entering Passive Mode (127,0,0,1,198,173)

	10:20:12.820 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: MLSD
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: ./
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of / requested
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: 12 folders found
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /assets
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /https:
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /fonts
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /dist
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: 23 files found
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: 2 pages found
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /assets requested
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /assets/js
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /https: requested
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /https:/ajax.googleapis.com
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /fonts requested
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: File found: /fonts/glyphicons-halflings-regular.ttf
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: File found: /fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: File found: /fonts/glyphicons-halflings-regular.eot
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /dist requested
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /dist/js
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /dist/css
	10:20:12.831 [pool-5-thread-23] WARN  o.apache.ftpserver.impl.PassivePorts - Releasing unreserved passive port: 50861
	10:20:12.831 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 150 File status okay; about to open data connection.

	10:20:12.831 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 226 Closing data connection.

	10:20:12.836 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: TYPE I
	10:20:12.836 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 200 Command TYPE okay.

	10:20:12.837 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: PASV
	10:20:12.837 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 227 Entering Passive Mode (127,0,0,1,198,175)

	10:20:12.838 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: STOR /dings.js-27fcbd6c-d334-40e4-b538-1053c23c08bc
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /dings.js-27fcbd6c-d334-40e4-b538-1053c23c08bc
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	WARNING: No existing file found: /dings.js-27fcbd6c-d334-40e4-b538-1053c23c08bc
	10:20:12.887 [pool-5-thread-24] INFO  o.apache.ftpserver.command.impl.STOR - File uploaded /dings.js-27fcbd6c-d334-40e4-b538-1053c23c08bc
	10:20:12.887 [pool-5-thread-24] WARN  o.apache.ftpserver.impl.PassivePorts - Releasing unreserved passive port: 50863
	10:20:12.887 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 150 File status okay; about to open data connection.

	10:20:12.887 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 226 Transfer complete.

	10:20:12.888 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: DELE /dings.js
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /dings.js
	10:20:12.918 [pool-5-thread-23] INFO  o.apache.ftpserver.command.impl.DELE - File delete : admin - /dings.js
	10:20:12.919 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 250 Requested file action okay, deleted /dings.js.

	10:20:12.919 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: RNFR /dings.js-27fcbd6c-d334-40e4-b538-1053c23c08bc
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /dings.js-27fcbd6c-d334-40e4-b538-1053c23c08bc
	10:20:12.923 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 350 Requested file action pending further information.

	10:20:12.923 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: RNTO /dings.js
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /dings.js
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	WARNING: No existing file found: /dings.js
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.AbstractStructrFtpFile move
	INFO: move()
	10:20:12.932 [pool-5-thread-24] INFO  o.apache.ftpserver.command.impl.RNTO - File rename from "/dings.js-27fcbd6c-d334-40e4-b538-1053c23c08bc" to "/dings.js"
	10:20:12.932 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 250 Requested file action okay, file renamed.

	10:20:12.935 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: CWD /
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /
	10:20:12.939 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 250 Directory changed to /

	10:20:12.939 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: TYPE A
	10:20:12.940 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 200 Command TYPE okay.

	10:20:12.940 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: PASV
	10:20:12.940 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 227 Entering Passive Mode (127,0,0,1,198,177)

	10:20:12.941 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: MLSD
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: ./
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of / requested
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: 12 folders found
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /assets
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /https:
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /fonts
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Folder found: /dist
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: 23 files found
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: 2 pages found
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /assets requested
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /assets/js
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /https: requested
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /https:/ajax.googleapis.com
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /fonts requested
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: File found: /fonts/glyphicons-halflings-regular.ttf
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: File found: /fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: File found: /fonts/glyphicons-halflings-regular.eot
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Children of /dist requested
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /dist/js
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFtpFolder listFiles
	INFO: Subfolder found: /dist/css
	10:20:12.955 [pool-5-thread-24] WARN  o.apache.ftpserver.impl.PassivePorts - Releasing unreserved passive port: 50865
	10:20:12.955 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 150 File status okay; about to open data connection.

	10:20:12.955 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 226 Closing data connection.

	10:20:12.960 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: TYPE I
	10:20:12.960 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 200 Command TYPE okay.

	10:20:12.960 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: PASV
	10:20:12.961 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 227 Entering Passive Mode (127,0,0,1,198,179)

	10:20:12.961 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: STOR /dings.js-6216c602-0ed7-4a27-960f-b29f31f60f28
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /dings.js-6216c602-0ed7-4a27-960f-b29f31f60f28
	Jan 04, 2015 10:20:12 AM org.structr.files.ftp.StructrFileSystemView getFile
	WARNING: No existing file found: /dings.js-6216c602-0ed7-4a27-960f-b29f31f60f28
	10:20:13.000 [pool-5-thread-23] INFO  o.apache.ftpserver.command.impl.STOR - File uploaded /dings.js-6216c602-0ed7-4a27-960f-b29f31f60f28
	10:20:13.000 [pool-5-thread-23] WARN  o.apache.ftpserver.impl.PassivePorts - Releasing unreserved passive port: 50867
	10:20:13.000 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 150 File status okay; about to open data connection.

	10:20:13.000 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 226 Transfer complete.

	10:20:13.001 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: DELE /dings.js
	Jan 04, 2015 10:20:13 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /dings.js
	10:20:13.028 [pool-5-thread-24] INFO  o.apache.ftpserver.command.impl.DELE - File delete : admin - /dings.js
	10:20:13.028 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 250 Requested file action okay, deleted /dings.js.

	10:20:13.028 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: RNFR /dings.js-6216c602-0ed7-4a27-960f-b29f31f60f28
	Jan 04, 2015 10:20:13 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /dings.js-6216c602-0ed7-4a27-960f-b29f31f60f28
	10:20:13.032 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 350 Requested file action pending further information.

	10:20:13.032 [pool-5-thread-24] INFO  o.a.f.listener.nio.FtpLoggingFilter - RECEIVED: RNTO /dings.js
	Jan 04, 2015 10:20:13 AM org.structr.files.ftp.StructrFileSystemView getFile
	INFO: Requested path: /dings.js
	Jan 04, 2015 10:20:13 AM org.structr.files.ftp.StructrFileSystemView getFile
	WARNING: No existing file found: /dings.js
	Jan 04, 2015 10:20:13 AM org.structr.files.ftp.AbstractStructrFtpFile move
	INFO: move()
	10:20:13.041 [pool-5-thread-24] INFO  o.apache.ftpserver.command.impl.RNTO - File rename from "/dings.js-6216c602-0ed7-4a27-960f-b29f31f60f28" to "/dings.js"
	10:20:13.042 [pool-5-thread-23] INFO  o.a.f.listener.nio.FtpLoggingFilter - SENT: 250 Requested file action okay, file renamed.

**Comment by vigorouscoding** [comment]
I created a ticket in the Cyberduck tracker https://trac.cyberduck.io/ticket/8456

**Comment by vigorouscoding** [comment]
part 2 is "fixed" now. removing the cyberduck preferences completely did the trick... :(

**Comment by amorgner** [comment]
Thanks! So we need to find a way to give the new file the old UUID. I can imagine that there are more FTP clients which work with temporary files out there.

**Comment by vigorouscoding** [comment]
i'll close this as it does not seem to be relevant for anyone else - maybe that also had to do with my cyberduck preferences...
