### ISSUE TITLE
GraphGist Importer dies on gists that run okay as GraphGists

### ISSUE THREAD

**Issue by Jim-Salmons** [structr/structr#282]
Somewhere in the ball of code that does GraphGist importing, this are fragile. I have a GraphGist file that runs okay as a GraphGist, but Structr gives up trying to import it. There are a bunch of logging messages, including suspicious notices of things that can't be found when trying to compile classes I believe. But Structr does not die, it just tries, then ignores, and keeps being ready for the next thing that will happen. 

The problematic source GraphGist is found here: https://gist.github.com/Jim-Salmons/b9d3ea14a6e2c5c1493c 

The GraphGist I am trying to import is a small dataset representing the minimal #cidocCRM-Compatible Form. There are some pretty extensive textual property values which I believe are good candidates for violating whatever assumptions there may be about what will likely be seen in a property value being imported. So maybe this is a helpful gist to figure out the edge cases that need to be covered for a more robust GraphGistImporter.

Also note, **this is not a manually authored GraphGist. The actual Cypher was generated by the Neo4jShell using a 'dump' operation** and that may be compounding things -- like its heavy use of backticks and text delimiting within property values, etc. I then wrapped this dump with minimally human-readable context content in prep for Structr import (so it could do its schema discovery).

Please let me know what I can do to help further identify and resolve this issue. GraphGist importing will be a SUPER feature as it becomes better and better.

It may be that there are some hard and fast rules about what forms of GraphGist expression will or will not be imported. If so, once we nail these limits, we can summarize "GraphGist prep" best practices in the docs. It may be helpful, too, to provide one or more links to interesting GraphGists that a new user could use to explore this powerful feature.

Finally, unless the import is nearly lightening fast, some kind of intermittent activity notification could keep someone from waiting and waiting for a complete import when the process has finished already in an error although the 'snaking circular arrow icon' is still spinning away.

**Comment by vigorouscoding** [comment]
This is because the Nodes in the GraphGist don't have Labels associated with them (and the internal handling in this case allowed an error to occur)
We just introduced a check for this kind of condition and now the mentioned GraphGist imports just fine (with the current master)

Please re-check when you find the time - thank you!

**Comment by vigorouscoding** [comment]
I'll close this as the current status is fixed and the mentioned GraphGist is imported fine now :)
