### ISSUE TITLE
Dynamic loading of drop down options for multiple select

### ISSUE THREAD

**Issue by ophileon** [structr/structr#287]
When using the multiselect dropdown component that is integrated, all possible options are loaded into the client, which of course has its limits. Would be nice to have some dynamic loading in combination with autocomplete.

![screen shot 2014-10-31 at 15 37 06](https://cloud.githubusercontent.com/assets/3007812/4862319/b0bf1028-610b-11e4-9536-f6c0598b0da8.png)

**Comment by amorgner** [comment]
There's a field named "Custom REST query for value options" in the Edit Mode Binding tab of the properties dialog. You can specify a REST query to create the selectable values.
