### ISSUE TITLE
<form data-structr-hide="non-edit">  needs context

### ISSUE THREAD

**Issue by ophileon** [structr/structr#288]
I have a page with two divs like this. each div contains a form that can  be put in edit mode independently from the other. I have set data-structr-hide to  "non-edit" for both forms.

     <div class="table-responsive" data-structr-id="cf68ef22abba478f8c1086854c74bedf">
        <h3>Indicators measuring this activity
          <button data-structr-id="cf68ef22abba478f8c1086854c74bedf" data-structr-action="edit" data-structr-attributes="measuredbyIndicator" data-structr-reload="true"><img src="/edit-128.png" width="12px" height="12px"></button>
        </h3>
        <table class="table">
          <tbody data-structr-attr="measuredbyIndicator" data-structr-type="Indicator[]" data-structr-raw-value="[5ae8ce03fa0a476cbed0af4cd06af826, 5a0fe65381dc4b3db8eea3fb4ed8444f, 3e8746ebb1c04a35a3d0706d4597f803, 42858dfc3b614b5baf0f08c0485a51c5]">
              <tr>
                <td><a href="/indicator/42858dfc3b614b5baf0f08c0485a51c5">333</a></td>
              </tr>
              <tr>
                <td><a href="/indicator/5a0fe65381dc4b3db8eea3fb4ed8444f">Kms of paved road</a></td>
              </tr>
              <tr>
                <td><a href="/indicator/5ae8ce03fa0a476cbed0af4cd06af826">a new one</a></td>
              </tr>
              <tr>
                <td><a href="/indicator/3e8746ebb1c04a35a3d0706d4597f803">number of trained people</a></td>
              </tr>
          </tbody>
        </table>
        <div>
          <form data-structr-hide="non-edit">
            <input data-structr-name="name">
            <button data-structr-action="create:Indicator" data-structr-attributes="name,activityMeasuredby" data-structr-reload="true">Add indicator</button>
            <select multiple="multiple" hidden="true" data-structr-name="activityMeasuredby">
              <option selected="selected">cf68ef22abba478f8c1086854c74bedf</option>
            </select>
          </form>
        </div>
      </div>

![screen shot 2014-11-02 at 14 04 40](https://cloud.githubusercontent.com/assets/3007812/4875294/dda7885a-6290-11e4-8ad6-c1ada6953af6.png)

The problem is that when putting one of the forms in edit mode, the controls of both forms appear. This is after clicking the upper edit button.

![screen shot 2014-11-02 at 14 05 53](https://cloud.githubusercontent.com/assets/3007812/4875297/0f1772b0-6291-11e4-868e-542a5f0f93dc.png)

Seems that the context that is put in edit mode, cannot be controlled.

**Comment by amorgner** [comment]
Old issue, closing it. In the meantime, the logic for forms in edit mode has evolved, see https://support.structr.com/article/295.
