### ISSUE TITLE
Run Structr against a remote standalone Neo4j server

### ISSUE THREAD

**Issue by hdorio** [structr/structr#291]
feature request to be able to replace Neo4j embedded database by a remote Neo4j server

**Comment by amorgner** [comment]
Just FYI @hdorio, we're working on a Neo4j driver for Bolt, see https://github.com/nigelsmall/bolt-howto.

**Comment by cmorgner** [comment]
Connecting to a remote Neo4j 3.0 instance will be possible in one of the future versions, starting from 2.1-SNAPSHOT.

**Comment by amorgner** [comment]
With the latest snapshot, Structr can be configured to run against any remote Neo4j 3.0 database:

	#############################################################################
	# Neo4j server settings
	#############################################################################

	database.driver = org.structr.bolt.BoltDatabaseService
	database.driver.mode = remote

	database.connection.url = bolt://localhost:7687
	database.connection.username = neo4j
	database.connection.password = neo4j

**Comment by amorgner** [comment]
https://support.structr.com/article/456

**Comment by richiepaez** [comment]
Hi Axel!

Thank you for sending a link to that article.  Unfortunately it doesn't add
any new information that we didn't know and have already done.

Best regards,

Richie
