### ISSUE TITLE
Improve Schema Editor layout algorithm

### ISSUE THREAD

**Issue by cmorgner** [structr/structr#296]

**Comment by eric-schleicher** [comment]
I'll just go on the record to say i have to do this (re-layout) a lot more than i care to:
![image](https://cloud.githubusercontent.com/assets/8261783/6716843/666f0cf0-cd65-11e4-82ee-156632321609.png)

sometime i nee to clear my cookies and local storage, and i'm greeted with this upon returning to structr.

**Comment by amorgner** [comment]
There's a layout export/import tool as described in #398, and with the latest snapshots, you can select multiple schema nodes by drawing a rectangle to drag them as a group.

@cmorgner Does it count as improved schema layouting?

**Comment by eric-schleicher** [comment]
Argh!!!!!!!!

![image](https://cloud.githubusercontent.com/assets/8261783/11758989/2997299e-a027-11e5-8b27-f42de3a4bf54.png)

**Comment by eric-schleicher** [comment]
BTW.  multi Select and Drag for the entities is a Major #win

**Comment by cmorgner** [comment]
Closing this issue because - hopefully - most of the schema editor layout issues are controllable using the import/export, search and multi-select functions.

**Comment by eric-schleicher** [comment]
Agreed.  Schema "management" is much better now with the ability to save and restore layouts.
