### ISSUE TITLE
Make DELETE REST call in structr-app.js include the type

### ISSUE THREAD

**Issue by cmorgner** [structr/structr#297]
The type is currently not included in the REST URL that is used to delete an entity, so the user cannot use a ResourceAccess object to control the deletion of individual types separately. All DELETE actions happen on /<uuid>, so in order to allow delete at all, the ResourceAccess object for "/" must be set.

**Comment by amorgner** [comment]
If the type (e.g. ``delete:SampleApplication``) is given in the ``data-structr-action`` attribute, it is included in the REST URL.
