### ISSUE TITLE
Feature request for the ResourceAccess dialog: highlight / display access errors

### ISSUE THREAD

**Issue by cmorgner** [structr/structr#298]
The default permission for all ResourceAccess flags is "0", so nothing is allowed. When testing an application, it would be great if the individual ResourceAccess objects were logging / displaying all HTTP access errors that happen on the corresponding resource.

**Comment by cmorgner** [comment]
Closing this issue since the requested feature ("log resource access errors") is implemented.

**Comment by eric-schleicher** [comment]
Is this controllable by value, or just set in the standard log?   Is this why i see '_env' resource access error in the log all the time?

**Comment by vigorouscoding** [comment]
Any request that gets blocked because of a missing resource access get logged to the standard log.
As of 3702b21f1872b19e9c00564669253024193a18e5 there backend should not generate the "_env" error all the time.
