### ISSUE TITLE
HTML property not listed for Tag Type <optgroup>

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#306]
Currently (1.1 snapshot 24) does not support setting the label attribute of an <optgroup> DOM node

Attempts to add it manually from the html attribute dialog fail.  the dialog accepts the new input of a new property and flashed as if it's been accepted, but the value is not persisted.  

Researching the code yielded that the statically defined allow attribute are not implemented.

Also noted that there is not a way to manually add this value from the node properties dialog (not sure if that's a separate issue or potential feature)

**Comment by cmorgner** [comment]
Can this be closed?

**Comment by eric-schleicher** [comment]
Thanks, sorry it took so link to see.
