### ISSUE TITLE
error on addition of second group to user from CRUD

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#307]
When attempting to add a group to a user through the CRUD UI, recieve the following error when adding  second group: 

Not found: { "code": 404, "errors": { "Group": { "base": [ { "object_not_found": { "id": "", "type": "Group" } } ] } } }

removing the first group then allows the selection of a new (single) group.  this is unexpected since it's believed that user:group is a 1:n relationship

**Comment by amorgner** [comment]
It's a n:m relation, and in recent snapshots, you can add multiple users to one group, and also multiple groups to one user through the CRUD UI.

Can you confirm this working?

**Comment by eric-schleicher** [comment]
I'll try and get to this next week.

**Comment by eric-schleicher** [comment]
This works..  I can add a user to multiple groups, however the treeview does't really display correctly as it's a mixup in the display paradigm (the three view implies that that the user is only displayed once)

**Comment by amorgner** [comment]
Your observation re. the tree view paradigm is correct, this is something we'll have to find a good solution for in a future release.
