### ISSUE TITLE
Include build version in startup message and logs

### ISSUE THREAD

**Issue by amorgner** [structr/structr#310]
It would be helpful to see version and build date at startup, and log file.

**Comment by amorgner** [comment]
With commit aec5fcf4d255d1abe573ecc272a9e3f202f51b8d, build number (=first 5 characters of the git commit hash) are included in the version and the jar filename.

The start scripts run the particular build, and there's new REST endpoint ``/structr/rest/_env`` which outputs some environment information like this:

	curl -HX-User:superadmin -HX-Password:xxxxxxxxxx http://0.0.0.0:8082/structr/rest/_env
	{
	   "query_time": "0.007557129",
	   "result_count": 1,
	   "result": {
	      "modules": [
	         {
	            "module": "structr-core",
	            "build": "",
	            "version": "1.1"
	         },
	         {
	            "module": "structr-rest",
	            "build": "",
	            "version": "1.1"
	         },
	         {
	            "module": "structr-ui",
	            "build": "1956a",
	            "version": "1.1-SNAPSHOT"
	         }
	      ],
	      "classPath": "target/lib/javax.servlet.jsp.jstl-1.2.2.jar:target/lib/json-simple-1.1.jar:target/lib/commons-fileupload-1.3.1.jar:target/lib/structr-core-1.1-SNAPSHOT.jar:target/lib/bcprov-jdk16-140.jar:target/lib/parboiled-core-1.1.6.jar:target/lib/asciidoctor-java-integration-0.1.4.jar:target/lib/geronimo-jta_1.1_spec-1.1.1.jar:target/lib/gt-data-9.2.jar:target/lib/commons-net-3.3.jar:target/lib/httpclient-4.2.6.jar:target/lib/neo4j-graph-matching-2.1.6.jar:target/lib/opencsv-2.3.jar:target/lib/gt-metadata-9.2.jar:target/lib/jetty-http-9.1.4.v20140401.jar:target/lib/hamcrest-library-1.3.jar:target/lib/commons-io-2.4.jar:target/lib/commons-codec-1.10.jar:target/lib/diff_match_patch-current.jar:target/lib/jetty-servlets-9.1.4.v20140401.jar:target/lib/websocket-servlet-9.1.4.v20140401.jar:target/lib/rest-assured-common-2.3.1.jar:target/lib/json-path-2.3.1.jar:target/lib/gt-shapefile-9.2.jar:target/lib/jcommander-1.30.jar:target/lib/jai_core-1.1.3.jar:target/lib/websocket-client-9.1.4.v20140401.jar:target/lib/twitter4j-core-4.0.2.jar:target/lib/jruby-complete-1.7.4.jar:target/lib/textile-j-2.2.jar:target/lib/structr-rest-1.1-SNAPSHOT.jar:target/lib/neo4j-kernel-2.1.6.jar:target/lib/jackson-mapper-asl-1.9.7.jar:target/lib/rhino-1.7R4.jar:target/lib/logback-access-1.1.2.jar:target/lib/rest-assured-2.3.1.jar:target/lib/neo4j-cypher-compiler-1.9-2.0.3.jar:target/lib/neo4j-primitive-collections-2.1.6.jar:target/lib/commons-lang3-3.3.2.jar:target/lib/org.eclipse.jdt.core-3.8.2.v20130121.jar:target/lib/commons-collections-3.2.1.jar:target/lib/groovy-xml-2.2.1.jar:target/lib/jsoup-1.8.1.jar:target/lib/java-image-scaling-0.8.6.jar:target/lib/jetty-util-9.1.4.v20140401.jar:target/lib/jetty-jndi-9.1.4.v20140401.jar:target/lib/groovy-2.2.1.jar:target/lib/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar:target/lib/imageio-ext-utilities-1.1.7.jar:target/lib/vecmath-1.3.2.jar:target/lib/gt-referencing-9.2.jar:target/lib/rrd4j-2.0.7.jar:target/lib/jetty-security-9.1.4.v20140401.jar:target/lib/server-api-2.1.6.jar:target/lib/jetty-xml-9.1.4.v20140401.jar:target/lib/mina-core-2.0.4.jar:target/lib/urlrewritefilter-4.0.4.jar:target/lib/xml-apis-1.0.b2.jar:target/lib/imageio-ext-tiff-1.1.7.jar:target/lib/oro-2.0.8.jar:target/lib/javax.servlet.jsp-api-2.3.1.jar:target/lib/ftplet-api-1.0.6.jar:target/lib/websocket-server-9.1.4.v20140401.jar:target/lib/logback-classic-1.1.2.jar:target/lib/asm-analysis-4.1.jar:target/lib/org.apache.oltu.oauth2.common-1.0.0.jar:target/lib/neo4j-graph-algo-2.1.6.jar:target/lib/concurrentlinkedhashmap-lru-1.3.1.jar:target/lib/jetty-server-9.1.4.v20140401.jar:target/lib/httpmime-4.2.6.jar:target/lib/jgridshift-1.0.jar:target/lib/jetty-schemas-3.1.M0.jar:target/lib/dom4j-1.6.1.jar:target/lib/jsr-275-1.0-beta-2.jar:target/lib/commons-logging-1.0.4.jar:target/lib/jai_imageio-1.1.jar:target/lib/gson-2.3.1.jar:target/lib/neo4j-jmx-2.1.6.jar:target/lib/hawtdb-1.6.jar:target/lib/logback-core-1.1.2.jar:target/lib/commons-beanutils-core-1.8.0.jar:target/lib/jetty-runner-9.1.4.v20140401.jar:target/lib/commons-configuration-1.6.jar:target/lib/parboiled-scala_2.10-1.1.6.jar:target/lib/javax.annotation-api-1.2.jar:target/lib/commons-compiler-2.6.1.jar:target/lib/jts-1.13.jar:target/lib/neo4j-shell-2.1.6.jar:target/lib/neo4j-cypher-2.1.6.jar:target/lib/gt-coverage-9.2.jar:target/lib/commons-beanutils-1.8.0.jar:target/lib/groovy-json-2.2.1.jar:target/lib/gt-render-9.2.jar:target/lib/asm-commons-4.1.jar:target/lib/commons-compress-1.9.jar:target/lib/commons-jxpath-1.3.jar:target/lib/gt-process-9.2.jar:target/lib/scala-library-2.10.4.jar:target/lib/asm-tree-4.1.jar:target/lib/asm-4.1.jar:target/lib/jsr311-api-1.1.2.r612.jar:target/lib/gt-opengis-9.2.jar:target/lib/slf4j-api-1.6.1.jar:target/lib/gt-cql-9.2.jar:target/lib/gt-main-9.2.jar:target/lib/jetty-annotations-9.1.4.v20140401.jar:target/lib/commons-email-1.3.3.jar:target/lib/neo4j-browser-2.1.6.jar:target/lib/jetty-io-9.1.4.v20140401.jar:target/lib/jersey-server-1.9.jar:target/lib/activation-1.1.1.jar:target/lib/jersey-core-1.9.jar:target/lib/jetty-servlet-9.1.4.v20140401.jar:target/lib/jdom-1.0.jar:target/lib/jackson-core-asl-1.9.7.jar:target/lib/javax.servlet-api-3.1.0.jar:target/lib/antlr-2.7.7.jar:target/lib/filters-2.0.235.jar:target/lib/javax.el-3.0.0.jar:target/lib/commons-pool-1.5.4.jar:target/lib/javax.servlet.jsp-2.3.2.jar:target/lib/neo4j-spatial-0.13-neo4j-2.1.6.jar:target/lib/jersey-multipart-1.9.jar:target/lib/neo4j-udc-2.1.6.jar:target/lib/janino-2.6.1.jar:target/lib/neo4j-cypher-compiler-2.0-2.0.3.jar:target/lib/jt-utils-1.3.0.jar:target/lib/mail-1.4.5.jar:target/lib/log4j-1.2.8.jar:target/lib/mimepull-1.6.jar:target/lib/neo4j-cypher-commons-2.1.6.jar:target/lib/neo4j-cypher-compiler-2.1-2.1.6.jar:target/lib/json-20131018.jar:target/lib/jetty-continuation-9.1.4.v20140401.jar:target/lib/xml-path-2.3.1.jar:target/lib/jackson-jaxrs-1.9.7.jar:target/lib/asm-util-4.1.jar:target/lib/gt-api-9.2.jar:target/lib/jetty-plus-9.1.4.v20140401.jar:target/lib/lucene-core-3.6.2.jar:target/lib/commons-digester-1.8.1.jar:target/lib/org.apache.oltu.oauth2.client-1.0.0.jar:target/lib/hamcrest-core-1.3.jar:target/lib/jai_codec-1.1.3.jar:target/lib/ftpserver-core-1.0.6.jar:target/lib/jt-zonalstats-1.3.0.jar:target/lib/pegdown-1.4.2.jar:target/lib/jetty-webapp-9.1.4.v20140401.jar:target/lib/httpcore-4.2.5.jar:target/lib/neo4j-server-2.1.6.jar:target/lib/tagsoup-1.2.1.jar:target/lib/org.apache.servicemix.bundles.jline-0.9.94_1.jar:target/lib/websocket-api-9.1.4.v20140401.jar:target/lib/hawtbuf-1.4.jar:target/lib/jetty-jsp-9.1.4.v20140401.jar:target/lib/neo4j-lucene-index-2.1.6.jar:target/lib/parboiled-java-1.1.6.jar:target/lib/commons-lang-2.4.jar:target/lib/jmimemagic-0.1.2.jar:target/lib/jetty-jaas-9.1.4.v20140401.jar:target/lib/junit-4.11.jar:target/lib/xmlParserAPIs-2.0.2.jar:target/lib/websocket-common-9.1.4.v20140401.jar:target/structr-ui-1.1-SNAPSHOT-1956a.jar"
	   },
	   "serialization_time": "0.003052508"
	}

**Comment by amorgner** [comment]
With commit 74d44916aca49c6a45903ce3d5d0876edc5fa3be, version and build info is displayed in the bottom-left corner of the backend UI's header.

**Comment by vigorouscoding** [comment]
awesome! that's very useful
