### ISSUE TITLE
Problems installing on Windows 8 using the binary distribution

### ISSUE THREAD

**Issue by NachoDog** [structr/structr#312]
I'm following the installation instructions in the tutorial section of the website as follows:

1.Download the binary distribution file (-dist.tar.gz) from Maven Central (~ 100 MB): https://oss.sonatype.org/content/repositories/releases/org/structr/structr-ui/
2.Extract the file and enter the created directory (with bin, lib and the .jar file)
3.Start Structr UI from this directory with the following command: bin/start
4.Go to  http://localhost:8082/structr#pages

I first installed the Java SE SDK version 8.  I then downloaded the dist.tar.gz binary distribution and unzipped it.  I then tried the bin/start without much luck.  What kind of file is this, it has no extension so Windows won't run it as a batch file.  

I'm not very technical so don't assume I know anything.

**Comment by amorgner** [comment]
Please try with Java SDK 7 as version 8 is not supported right now.

Running Structr on Windows is not straight-forward, we're looking for some Windows wizards. :-)

**Comment by davidtamayo177** [comment]
Hello! Are there any updates on this? I can't seem to install mine as well :(

**Comment by NachoDog** [comment]
To be honest I gave up.  I tried writing a dos batch file to do the same thing that the supplied Unix shell script does but failed.  However I think my problem was that Java wants to see windows file names as uri's not normal dos file names.  I learned this lesson trying to get neo4j batch load scripts to work.

**Comment by amorgner** [comment]
There's an installation guide for Windows now: https://docs.structr.org/installation-and-configuration-guide#Windows%20Manual%20Installation.

And JDK 8 is also supported with the latest snapshot (1.1-SNAPSHOT #74 https://oss.sonatype.org/content/repositories/snapshots/org/structr/structr-ui/1.1-SNAPSHOT/).
