### ISSUE TITLE
data-structr-* properties can not be set to null via the "HTML Attributes" tab

### ISSUE THREAD

**Issue by vigorouscoding** [structr/structr#314]
on "HTML Attributes" the small "x" image does not have an event listener for the "click" event because the ID already exists on the "Edit Mode Binding" tab.

**Comment by vigorouscoding** [comment]
commit e82a899bc0fd0c8e0862c1cac152ab532a46d5bf partially fixes the problem.

new
- a prefix for the "HTML Attributes" so there is no ID clash with the fields in the "Edit Mode Binding" tab
- properties which are "!== null" are now shown by default


one problem remains: "data-structr-reload" and "data-structr-confirm" can not be set to null. this seems to be because they are of type Boolean. if set to "true" and then clicking "set to null" the properties are set to "false"

**Comment by amorgner** [comment]
I can confirm the remaining problem, but closing this issue as the core bug is fixed.
