### ISSUE TITLE
ResourceAccess UI inconsistent with Documentation

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#315]
The docs and numerous  groups conversations show these as the flags values for resource access nodes...

    FORBIDDEN                   = 0;
    AUTH_USER_GET               = 1;
    AUTH_USER_PUT               = 2;
    AUTH_USER_POST              = 4;
    AUTH_USER_DELETE            = 8;
    NON_AUTH_USER_GET           = 16;
    NON_AUTH_USER_PUT           = 32;
    NON_AUTH_USER_POST          = 64;
    NON_AUTH_USER_DELETE        = 128;
    AUTH_USER_OPTIONS           = 256;
    NON_AUTH_USER_OPTIONS       = 512;
    AUTH_USER_HEAD              = 1024;
    NON_AUTH_USER_HEAD          = 2048;

but the UI sets these

    AUTH_USER_GET               = 64;
    AUTH_USER_PUT               = 128;
    AUTH_USER_POST              = 256;
    AUTH_USER_DELETE            = 512;
    NON_AUTH_USER_GET           = 1;
    NON_AUTH_USER_PUT           = 2;
    NON_AUTH_USER_POST          = 4;
    NON_AUTH_USER_DELETE        = 8;
    AUTH_USER_OPTIONS           = 1024;
    NON_AUTH_USER_OPTIONS       = 16;
    AUTH_USER_HEAD              = 2048;
    NON_AUTH_USER_HEAD          = 32;

It's unclear whether the interpretations of the flag values has changes, or whether this is a small defect with the the UI.

**Comment by amorgner** [comment]
That's a known bug, fixed with commit e153b6b2aab123de8ebfe8e4ebc5080853e06e04 in the latest snapshots.
