### ISSUE TITLE
dialog parsing/display issue with formula

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#316]
See video:  http://youtu.be/up0DYLh_h2w

Use Case:

I'm attempting to allow for my login page to dynamically send a user a page.  i'm using a request value called targetPage to control the return URI once the logon has occured.  i'm using an if statement to send the user to their default page (in this case user-home) if not targetPage is specified.

This works as desired/intended, however the once entering the formula in the dialog, closing the dialog and returning to the page results in a defect displaying the value correctly.

the value is successfully retained and displayed on the HTML Attributes Tab, but is displayed incorrectly on the "Edit Mode Binding" Tab

Value on HTML Attribute Tab:
`${if(empty(request.targetPage),"user-home",request.targetPage)}`

Value displayed on the "Edit Mode Binding" Tab:
`${if(empty(request.targetPage),`

**Comment by vigorouscoding** [comment]
thanks for reporting - this seems to be an escaping-related bug in the "Edit Mode Binding" tab.

a general rule of thumb is to use single quotes instead of double quotes to avoid this kind of behavior (though it needs to be fixed)

**Comment by eric-schleicher** [comment]
Agreed but your right (need 2bfixes)  I'm a 'typical' user

**Comment by vigorouscoding** [comment]
I added a quick fix for this issue in commit https://github.com/structr/structr/commit/2cf8ac8ea78573cc9da346753b2a01b80ca0758b
