### ISSUE TITLE
credentials admin/admin not working for the local instance

### ISSUE THREAD

**Issue by waqasmoazzam** [structr/structr#320]
Hi,

I cloned the project and installed/built it according to the guidelines. I am unable to login. username: admin and password: admin is not working. Please, guide. 

I am running it on windows 8.1

Thanks

**Comment by cmorgner** [comment]
Hi, are there any error messages in the log file? Do you get to the login form at all? Please share your logs/server.log file.

**Comment by waqasmoazzam** [comment]
I am not sure where the log file is located. I can see the login page and the login form. Kindly tell me where the log file is located.

It will be great if you could tell me how I can stop the process? I did mvn exec:exec I am not sure how to stop it. I want to delete the db folder to start over.

**Comment by waqasmoazzam** [comment]
I reinstalled it and it works fine now. Thanks.
