### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#321]
#Bug Detail

source and target are both running `structr-ui-1.1-SNAPSHOT-7d0fd`

###Screenshot Dialog on target System:
![Dialog](https://dl.dropboxusercontent.com/u/12024/2015-01-19-sync_error_1.png)

###From source server
`$ sudo cat /usr/lib/structr-ui/structr.conf | grep tcp`

displays: **tcp.port = 54555**

---
###When clicking 'Show Available Entities'
Notification area on lower left of dialog indicates:

1. Shows: Transferred 2 of 3 objects...  and stays there for a while and then
2. Shows: Authentication Failed !

Produces the following output in /var/log/structr-ui.log

###Log Output
```
INFO: Initialization complete
Jan 20, 2015 5:29:34 AM org.structr.cloud.CloudConnection <init>
INFO: New connection from /76.176.115.242:56936
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
        at org.structr.cloud.message.Message.deserialize(Message.java:268)
        at org.structr.cloud.Receiver.run(Receiver.java:52)
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
        at org.structr.cloud.message.Message.deserialize(Message.java:268)
        at org.structr.cloud.Receiver.run(Receiver.java:52)
Jan 20, 2015 5:29:35 AM org.structr.cloud.message.Message deserialize
WARNING: Invalid CloudService message: unknown type admin
Jan 20, 2015 5:29:35 AM org.structr.cloud.CloudConnection run
INFO: Transmission finished
```

server available for additional collection

**Comment by cmorgner** [comment]
The progress message indicates that you aren't using the latest snapshot, please try again with the most recent snapshot and clear the browser cache. It seems that at least one of your instances is outdated.

Hope that helps!

**Comment by eric-schleicher** [comment]
In this test scenario, the target system was a fresh docker install.   it was my understanding that a fresh docker install (snaphot) would install the most recent, which it seems to not have done.  i'll try and verify what version is installed againg to check.

chose a new target system that i was positive was build #40 and the functionality worked as design in syncing a page (push).  I have not yet tested other functionality.  

Closing this as appears to be operator head space issue..
