### ISSUE TITLE
Submitting a POST request from the server

### ISSUE THREAD

**Issue by mimen** [structr/structr#322]
Best practices for Mailchimp API indicate that a POST verb should be used.

We would like to integrate against the Mailchimp API and be able to make calls from entity methods and from specific pages without exposing protected credentials. It is viewed that adding a POST function to the structr language would allow such functionality as well as open up the door to other interesting and compelling capabilities.

Additional details:
https://groups.google.com/forum/#!topic/structr/H9W1qFk3MGQ

**Comment by amorgner** [comment]
+1 from @eric-schleicher (via https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/structr/H9W1qFk3MGQ/O2Sc-DrzJLAJ): "We vote for #2.   being able to post from the server side is very compelling functionality."

**Comment by amorgner** [comment]
Server-side POST is available in the latest snapshot builds, so closing this one.

**Comment by eric-schleicher** [comment]
@amorgner   Having Post is awesome...  But the inability to control a response (like product a JSON result) from a custom method limits the awesomeness.  contemplating a specific feature request for that ability.   

How it this type of ability envisioned?

**Comment by amorgner** [comment]
It's already there, just do:

    ${to_json(POST('http://localhost:8082/structr/rest/sample_applications', '{"name":"test"}'))}

Or with the new JavaScript scripting, you can do this:

    ${{
    return Structr.toJson(Structr.POST('http://localhost:8082/structr/rest/sample_applications', '{"name":"test"}'));
    }}
