### ISSUE TITLE
Concat function  with curly brace seems to misbehave, reventing testing of new POST method

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#323]
# Intro
--- 
I have a custom method on an entity in which i'm attempting to pull together a JSON string to use [for testing] with the new POST() function.

This approach allows us to keep API key and other important identifiers protects (not in the dom).

I'm working towards using the POST function and have not yet completed the string for the data argument (a JSON string) and cannot move forward with the test/implementation.

**TL;DR version:** *the concat function seems to error with a curly as the last string*

Here is relevent information on the custom method code

- the first two lines are trivial lookups to system configurations (an entity I've created for managing that type of information)
- next three are just checking to see that ive got the data right.
- the print() with contcat is the problematic piece.

### This works
````
(
store('list', get(find('SystemConfig', 'name', 'mailing-list-updates-default'), 'configValue')),
store('api-key', get(find('SystemConfig', 'name', 'mailchimp-api-key'), 'configValue')),
print(concat('email address to push to mailchimp list:', this.emailAddress)),
print(retrieve('api-key')),
print(retrieve('list')),
print(concat('{"apikey" : "', retrieve('api-key'),'", ', ' "list" : "', retrieve('list'), '" , "','email', '" : "', this.emailAddress,'"','curlybace'))
)
````
this produces the following log output:
````
<blah blah>
email address to push to mailchimp list:redacted4@github.edu
ec5c9d9222222992827222265422223b180e85722223fs7662ac15286d6-us3
0f8222445533ffg2f117
{"apikey" : "ec5c9d9222222992827222265422223b180e85722223fs7662ac15286d6-us3",  "list" : "0f8222445533ffg2f117" , "email" : "redacted4@github.edu"curlybrace
````

---
### This Doesn't - identical except for the last argument of the concat() function
- This number of arguments is consistent.  so don't think i'm hitting a limit on arguments on one and not the other.
````
(
store('list', get(find('SystemConfig', 'name', 'mailing-list-updates-default'), 'configValue')),
store('api-key', get(find('SystemConfig', 'name', 'mailchimp-api-key'), 'configValue')),
print(concat('email address to push to mailchimp list: ', this.emailAddress)),
print(retrieve('api-key')),
print(retrieve('list')),
print(concat('{"apikey" : "', retrieve('api-key'),'", ', ' "list" : "', retrieve('list'), '" , "','email', '" : "', this.emailAddress,'"','}'))
)
````
the web log shows the following error output
````

HTTP/1.1 422 NA
Access-Control-Allow-Origin: http://intern.redacted.com
Content-Type: application/json; charset=utf-8

{
  "code": 422,
  "message": "Invalid expression: mismatched closing bracket after "
}
````

**Comment by amorgner** [comment]
@eric-schleicher Could you please retest this with the latest snapshot and close this if it's working fine? Thanks!

**Comment by eric-schleicher** [comment]
task assigned internally.  will update this week

**Comment by eric-schleicher** [comment]
Verified.  Thanks!
