### ISSUE TITLE
Issue invoking custom method varies by user

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#324]
I have a simple MailSignup Entity on which I've create a custom method called syncSignup

**The Entity looks like this:**
![image](https://cloud.githubusercontent.com/assets/8261783/5933656/67d2046c-a678-11e4-9572-7fa58cb93efe.png)

I also have an admin page for this MailSignup that looks like this:  the primary purpose of this page is to allow an operator (who is appropriate authorized) to push new signups over the mailchimp api to the list.
![image](https://cloud.githubusercontent.com/assets/8261783/5933675/a8dbfdbe-a678-11e4-91d2-4643d8c27b60.png)

This page has a button wired up to this custom method. Per previous discussion with Structr team here is how the method is being called via the button properties dialog:
![image](https://cloud.githubusercontent.com/assets/8261783/5933769/fb47521e-a679-11e4-90a7-b9e161bbd895.png)

here is sample HTML output from view:source
````html
<tr>
                  <td>redacted@gmail.com</td>
                  <td>false</td>
                  <td>
                    <button data-structr-id="3db538f1085f4f0fb76ebf1c57ef1046" data-structr-action="syncSignup:MailSignup" data-structr-reload="false">Submit	</button>
                  </td>
                  <td>Initial text for td</td>
                </tr>
````
# Issue: 

##### When logged on as an admin user i get the following log output
````
WARNING: Unable to invoke method syncSignup: object is not an instance of declaring class
email address to push to mailchimp list:redacted@gmail.com
ec5c9d923b180e853322eevv79f7662ac15286d6-us3
0f8222f117
{"apikey" : "ef9f9f9f9f9f9f9f9f9f9f9f9fc454c494d9223bc1d8bd0de8579f7662ac15286d6-us3",  "list" : "0ffft85e2ac715722f117" , "email" : "redaccted@gmail.com"curlybrace
````

**Observation(s):** 
- The id being passed is ABSOLUTELY a mailSignup Entity
- Despite the message the code runs anyways 

##### When logged in as a non-admin user, i get no output at all indicating either the method entity type mismatch, or the print statements from within the method code block.

[update]  web access log shows 401 for non-admin users.  so this is a resource access issue methinks.

**Comment by amorgner** [comment]
Sorry for this stuff being overly complex. We now there are issues with naming conventions. The signature of a REST resource is normalized by something like a "toUpperCamelCase" method.

And BTW, @cmorgner has worked on improving the server-side POST function, and completely rewrote the expression parser. See https://github.com/structr/structr/commit/f42b9c03c6398403787c7e83592aef0442f2fd0e for details.

I'd really wish we could eventually agree on one single notation. But that would require people to stop being religous about "their" case notation. :-)

**Comment by eric-schleicher** [comment]
ok so clarity on this is great. and now allows focus on the issue, which is the warning messaging indicating entity type mismatch, which is not the case

````
Jan 28, 2015 11:03:14 PM org.structr.core.entity.AbstractNode invokeMethod
WARNING: Unable to invoke method syncSignup: java.lang.ClassCastException@5a713370
Jan 28, 2015 11:03:14 PM org.structr.core.entity.AbstractNode invokeMethod
WARNING: Unable to invoke method syncSignup: java.lang.ClassCastException@3de82c73
````

**Comment by amorgner** [comment]
This is just a warning, should be removed from the logs. WDYT @cmorgner?

**Comment by cmorgner** [comment]
Yes, definitely!

**Comment by eric-schleicher** [comment]
leave this open?

**Comment by amorgner** [comment]
Thanks for the reminder. I just set the log level to FINE for this: https://github.com/structr/structr/commit/b71d31c0be8fe71ae318bbdb1b7464593fa8ccb8
