### ISSUE TITLE
internationalization issue

### ISSUE THREAD

**Issue by Eljah** [structr/structr#327]
I tried to save page with some Unicode Cyrillic titles. Unfrotunately, I got Exception from 

TransactionCommand.java

		throw new FrameworkException(422, errorBuffer);
			
and the only workaround was to set doValidation to false in Tx.java and disable the upate of the Tx's doViolation. 

Any ideas is it possible to configure it without commenting out the source code?

**Comment by Eljah** [comment]
example of title that's wan't work: Заголовок

**Comment by Eljah** [comment]
tried the latest source code from master branch, seems to be no longer an issue. thanks a lot!

**Comment by Eljah** [comment]
on the last code I still see the issue

**Comment by amorgner** [comment]
At the moment, the page name must match the following regular expression:

    [_a-zA-Z0-9\\s\\-\\.]+

Do you have a tested regex which works for all unicode characters?

**Comment by amorgner** [comment]
I'd try replacing the ``a-zA-Z`` part with ``\p{L}``, see http://stackoverflow.com/questions/10894122/java-regex-for-support-unicode.

**Comment by amorgner** [comment]
Fixed, see 0b441353ec6c15ef20cc69e95141ffd64f17eb75.
