### ISSUE TITLE
Copy DOM-Node issue

### ISSUE THREAD

**Issue by vigorouscoding** [structr/structr#329]
copying a DOM node (by clicking the new "Copy" Symbol or by dragging the node to another page) results in an incomplete copy of that node and its subnodes.

The nodes are all there, but properties are missing (for example if you have a hidden input field it won't be hidden afterwards)

I will investigate this ASAP

**Comment by amorgner** [comment]
Could be that the wrong internal view is used, see https://github.com/structr/structr/blob/master/structr-ui/src/main/java/org/structr/web/entity/dom/DOMNode.java#L1681

**Comment by vigorouscoding** [comment]
thx for the info! will check that as soon as possible

**Comment by amorgner** [comment]
Additional info, might be useful: Before a recent change I made to support deep cloning, there was a ``cloneNode`` method in the subclass ``DOMElement`` which used the HTML view.

**Comment by vigorouscoding** [comment]
it seems you were right - the new version uses "uiView.name()" and the old version uses "htmlView.name()"

I will try this locally and report back

**Comment by vigorouscoding** [comment]
just commited a small change so that first the uiView properties are cloned and afterwards the DOMElement.htmlView properties are cloned.

see https://github.com/structr/structr/commit/6de992f834d34ca0351fd0e81c11c229a50df2c8

In my local tests it works as intended.

I'll leave this issue open for a while so you can confirm the change.

**Comment by amorgner** [comment]
I can confirm the fix, successfully cloned a node with the following code, contaning properties from both views:

```html
  <div>
    <h2>User List</h2>
      <table data-structr-meta-show-conditions="me.isAdmin">
        <thead>
          <tr class="table-header">
            <th>ID</th>
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
          <tr data-structr-meta-data-key="user" data-structr-meta-rest-query="users">
            <td class="user-id" id="user-${user.id}">${user.id}</td>
            <td class="user-name">${user.name}</td>
          </tr>
        </tbody>
      </table>
  </div>
```
