### ISSUE TITLE
Feature Request:  better control usability of schema

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#330]
Perhaps some combination of user definable canvas size, a pan/scan loupe, an export png button would help for  #schema usability.

I'm aware that any work touching jsplumb may be problematic, but the model that i'm building is starting to grow outside the available [1980 x 1080] real estate in #schema.  

1. a Loupe might help to navigate when using lower resolutions or with more complicated models

2. Since the canvas size is set based on the browser windows size.  If i re-layout at a higher reslution, when i return to a lower resolution the entities are off screen and difficult to re-layout. (quirky)

3. In general, it's also a pain to repetitively switch between pages and #schema. an image export option would be nice.

Thanks.

**Comment by amorgner** [comment]
Thanks for the input, that sounds very similar to what we're planning for 1.2!

**Comment by ravensorb** [comment]
On a similiar note, any thought to allowing for "views" of the schema?  Consider having several "domains" -- it might be nice to be able to have a way work with entities in one domain at a time and then maybe have a higher level view that contains certain nodes from each domain?

**Comment by eric-schleicher** [comment]
this is a good idea, i think if we're stuck with plumb.js for the
diagramming then this would be very useful...  My models are starting to
get difficult to navigate the ways things are right now.

A big plus would also be saving a layout could be formally saved

**Comment by ravensorb** [comment]
I agree saving a layout wounds be a huge benefit as a starting improvement.

**Comment by amorgner** [comment]
In the latest snapshots, the schema layout is saved serverside on logout. To be precise, the complete localStorage is saved/restored. Manual saving of course would be much better.

**Comment by ravensorb** [comment]
Very cool -- only issue is, I cannot get the latest snapshot to work at all.  The browser will not connect.  I log in and it immediately gets caught in a loop saying "connection lost".

**Comment by eric-schleicher** [comment]
Thought I would comment here on the current state of the schema designer (build 1.1 snap 60).   FWIW the most recent build is much more 'stable'  i haven't had a repeat of the unwanted "undefined relationship" bug. 

Also the explicit save button is very nice, and the zoom control is really very useful.  surely since i spend so much time in #schema I would love to see more enhancements here, but i find these changes have significantly improved the experience.  

I'll close this, but hope that more love will be added here as the roadmap permits.

Many thanks!

**Comment by amorgner** [comment]
Snapshot  62 contains a rather large upgrade of the schema editor. Please be very careful and be sure you have a working backup in place before trying it, as it automatically changes the schema graph in Neo4j when starting for the first time.

One feature you might like is that the new version lets you create the schema definition as a JSON file and restore it back.

**Comment by eric-schleicher** [comment]
i just brought a backup online and updated to structr-ui-1.1-SNAPSHOT-6105c (62).

should the upgrades to the editor be noticable? or are the big improvements behind the scenes?  I don't see the save Schema JSON (which BTW sounds fully awesome)
