### ISSUE TITLE
Entities changes in Schema are not picked up by the Data view

### ISSUE THREAD

**Issue by Eljah** [structr/structr#331]
https://structr.org/blog/structr-demo-in-ten-minutes 

Hi! I tried to reproduce the video step by step and faced with the problem: after adding the new Schema entity extending AbstractNode I don't see any new tab in Data and can't populate new type of entity. So, it looks like Schema changes doesn't affect Data view.

I tried it on 1.0 and from the current source code taken from the master brunch;

The only time I have succeed was 1.0 version when I have extended the Page class, but after switching the Data view and returning back to Schema view and modifieng the class and adding some new one Data no longer changed to fit the changes of the Schema. After i cleared the db and tired to reproduce it through install and exec:exec, I never got the Data view displaying my custom entities

**Comment by vigorouscoding** [comment]
we discussed the issue here https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/structr/XcbirZsBFxY and found a solution.

closing
