### ISSUE TITLE
Clone Page Functionality not working correctly in snapshot # 46

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#333]
With snapshot 1.1-46 an attempt to clone a page does not work correctly.

i have a relatively simple test page that i cloned.  the result did not appear or behave similarly to the original.  investication of the rendered result of the two (master and clone) pages revealed the following differences:
content type not coming across appropriately (?)

![image](https://cloud.githubusercontent.com/assets/8261783/6149415/8ed6ad06-b1bd-11e4-91c8-f9e0df7b5bbb.png)

also the node link values for Script tags not being preserved.

![image](https://cloud.githubusercontent.com/assets/8261783/6149462/f1b9a0b8-b1bd-11e4-97f2-ad6997c3a970.png)

and the attributes of input tag not comping across
![image](https://cloud.githubusercontent.com/assets/8261783/6149922/f301af26-b1c0-11e4-93f2-68ff9b1edb1b.png)

Along with the pencil edit functionality, until we have some type of revision/version control on pages, this cloning is critical functionality.

-Thanks.

**Comment by vigorouscoding** [comment]
looks to be a duplicate of https://github.com/structr/structr/issues/329

does this still happen with the current master?

**Comment by eric-schleicher** [comment]
Unclear, is there a snap that embodies that?

I run the .deb snaps. This is #46.  I see there are some fresher.  Will try
again.

Eric

**Comment by vigorouscoding** [comment]
unless the snapshot is less than two days old the problem should exist.

the fix that i wrote is just two days old (see https://github.com/structr/structr/issues/329#issuecomment-73487976)

the next snapshot should fix this problem

**Comment by amorgner** [comment]
@eric-schleicher, would you mind testing again with one of the most recent snapshot (52+)? Thanks!

**Comment by eric-schleicher** [comment]
Awesome!  Verified Working Correctly in 1.1-52
