### ISSUE TITLE
Inconsistent URI normalization (singular/plural)

### ISSUE THREAD

**Issue by amorgner** [structr/structr#335]
Normalization of the different URI parts are not consistent.

Example: The class ``TestObject`` creates the following valid REST endpoints:

    /test_object
    /test_objects
    /TestObject
    /TestObjects

A remote attribute ``RemoteObjects`` would create the following valid REST endpoints:

    /test_object/<id>/RemoteObject
    /test_objects/<id>/RemoteObject
    /TestObject/<id>/RemoteObject
    /TestObjects/<id>/RemoteObject

This is not consistent as a possible plural 's' seems to be removed.

**Comment by vigorouscoding** [comment]
while we are looking at this... is the pluralization/normalization really necessary? it is definitely nice and makes queries feel more natural, but if I wanted to break things, I could (whichI is a bit of a stretch... I'm aware)

Like first create a type "Test" and then create a type "Tests".
Or create a type "TestTest" and then create a type "test_test".

Now, when you create a Node for "Test" in the CRUD, the same node will show for "Tests".

Allowing the creation of a type which would clash with an already existing endpoint should be forbidden...
The only other solution (I can think of right now) would be to remove normalization and pluralization.

**Comment by cmorgner** [comment]
+1 for removing pluralization if it doesn't break anything else

Am 15. Februar 2015 22:48:59 MEZ, schrieb Kai Schwaiger <notifications@github.com>:
>while we are looking at this... is the pluralization/normalization
>really necessary? it is definitely nice and makes queries feel more
>natural, but if I wanted to break things, I could (whichI is a bit of a
>stretch... I'm aware)
>
>Like first create a type "Test" and then create a type "Tests".
>Or create a type "TestTest" and then create a type "test_test".
>
>Now, when you create a Node for "Test" in the CRUD, the same node will
>show for "Tests".
>
>Allowing the creation of a type which would clash with an already
>existing endpoint should be forbidden...
>The only other solution (I can think of right now) would be to remove
>normalization and pluralization.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/structr/structr/issues/335#issuecomment-74438988

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by eric-schleicher** [comment]
Just on the rest side for the base entities?  Or are we talking about using
normalised name for remote attributes as well?

E

**Comment by amorgner** [comment]
We should be careful here, not breaking existing functionality is #1 priority.

This issue is _only_ about fixing the bug that the valid URI requires to manually remove the trailing 's', seems that there's an automatic de-pluralization going on somewhere.

A general discussion about URI notation and mapping to class/attribute names, I'd rather see on the mailing list. There are quite a lot of things to be taken into account, and I think this is something for 2.0.

**Comment by amorgner** [comment]
Just realized that this bug is invalid. There's no trailing 's' being removed.

Any of these basic notations will be accepted:

    test_object
    Test_object
    test_Object
    Test_Object
    TestObject
    testObject

For the first URI part, all plural notations are resolved and normalized to its singular notation, even most irregular nouns like ``busses/buses => bus`` or ``women => woman``, using the [PlingStemmer](http://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/javatools/?sword_list[]=plingstemmer&no_cache=1) library.

For the nested (attribute) part, there's no conversion to singular, but the case mapping rules apply as well.

Sorry for the confusion.
