### ISSUE TITLE
Non-existing REST endpoint for nested attributes doesn't result in 404

### ISSUE THREAD

**Issue by amorgner** [structr/structr#336]
A non-existing REST endpoint of the pattern

    /test_objects/<id>/foo

should give a 404 if there's no remote attributre named ``foo`` in the ``TestObject`` class.

At the moment, the endpoint returns a 200 OK with an empty result collection.

**Comment by eric-schleicher** [comment]
Yay!

**Comment by amorgner** [comment]
Fixed, there's also a test for that now: https://github.com/structr/structr/blob/master/structr-rest/src/test/java/org/structr/rest/test/NestedResourcesTest.java#L34
