### ISSUE TITLE
Unwanted 'UNDEFINED_RELATIONSHIP_TYPE' nodes by #Shema

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#337]
I recall a conversation (but couldn't find the corresponding issue) indicating that the issue with plumb.js  triggering the spontaneous creation of unwanted schema relationships had been corrected.

So i'm not sure if this is a regression, or if the work to correct the issue didn't have the desired effect.

![image](https://cloud.githubusercontent.com/assets/8261783/6215032/cf5fcdf6-b5b1-11e4-8eb4-e798a35d92d4.png)

When this occurs it also invalidates the layout of the Shema, which is a bit annoying.

the resolution for me when this occurs is to run the following Cypher Statement(s) Typically from the dashboard or from the neo4j web admin.  

##### This statement to find the offending records
```match (n)-[r:IS_RELATED_TO {relationshipType:"UNDEFINED_RELATIONSHIP_TYPE"}]-( m ) return r;```

##### This statement purges the offending records.
```match (n)-[r:IS_RELATED_TO {relationshipType:"UNDEFINED_RELATIONSHIP_TYPE"}]-( m ) delete r;```

**Comment by vigorouscoding** [comment]
we fixed another cause of this problem.
this seems to be the root cause so we hope it will not happen anymore.

thanks for reporting!
