### ISSUE TITLE
Spaces in enum format string impact proper functioning in Data Editor

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#340]
is the schema editor, on the entity dialog, application exhibits a behaviour that is technically understandable, but likely confusing to most end users:

a format string of "youtube, sketchfab" produces unexpected behavior in the data editor.

The drop down enumerates correctly, but subsequently fails since the string are not identical
![image](https://cloud.githubusercontent.com/assets/8261783/6217042/93a8955a-b5c4-11e4-8a62-2c02ba4096b1.png)

changing the definition of the format string to "youtube,sketchfab"  (with no spaces) does however work correctly.  

it looks like inconsistent trimming behavior between validation and the UI (populating the dropdown UI)  in the application.

A user should not have to be so detailed, especially when validation is intelligently trimming the valid values

**Comment by vigorouscoding** [comment]
i just commited a small fix for this. (8bc6c830c40b459044fe6a87ead9c568ab78d8b8)

the dropdown values are now trimmed which fixes this behavior.
it also means that it is now impossible to add whitespace-only strings as enum values... (admittedly that doesnt seem too useful in the first place)

**Comment by eric-schleicher** [comment]
Thanks
