### ISSUE TITLE
Dashboard cannot run REST queries

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#342]
I'm having some issues with the dashboard.

About a week ago (on a previous build) i started to learn more about the dashboard and how to query information in the graph.  I've recently tried again, and run into an issue.

Last known working dashboard (for me) was in 1.1 snapshot 46 or 47.  The behavior demonstrated in this video is consistent between 1.1 snapshot 50 and 1.1 snapshot 51.

See Attached Video:
http://youtu.be/pxjHyQvp5mg

I captured a few permutations of trying to get a REST query to run and opened the developer console to inspect for error(s)...  which is shown in the video.  Although not shown in the video, I also did the same series of actions in firefox with an identical result (getting the reconnecting dialog).  This is not running locally, but in remote datacenter and with a good connection between sites

Please Advise, 

Would like to use it again, was learning quite a bit

I was hoping that this might change when following Axel's advise on how to clear up some issue from previous .deb file updates.  (written up in #341)  ...But unfortunately the issue persisted.

-Eric

**Comment by amorgner** [comment]
Confirmed, will look into it now.

**Comment by amorgner** [comment]
Fixed with 4fc04a9226992336aee312726b58eb90956438be. Fix will be included in next snapshot, to be released within the next 2 hours. Thanks for reporting.

**Comment by amorgner** [comment]
Snapshot 52 contains this fix: https://oss.sonatype.org/content/repositories/snapshots/org/structr/structr-ui/1.1-SNAPSHOT/

Please retest and close, thanks.

**Comment by eric-schleicher** [comment]
Confirmed Fixed.  Thanks!
