### ISSUE TITLE
No Shared Components

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#344]
Just noticed that in Snapshot 52 my shared components are now visible.   Widgets are however visible.

![image](https://cloud.githubusercontent.com/assets/8261783/6333559/e4aa7a44-bb42-11e4-922a-7f5e647b8f9e.png)

I took a backup, and restored a previous (along with snapshot 51) and observed the same result.

Javascript console show the following error:

![image](https://cloud.githubusercontent.com/assets/8261783/6333549/c8d5ec22-bb42-11e4-9694-bd06b6099c89.png)

I am blocked unless there is a previous snapshot that i can go back to.

**Comment by vigorouscoding** [comment]
same here - we fixed it a moment ago. thanks for reporting though!

https://github.com/structr/structr/commit/0b2c8df8782654023b4308d65ccb7a7ef3754b79

**Comment by vigorouscoding** [comment]
and since there is no new snapshot yet i'll reopen the issue - sorry for closing hastily!

**Comment by eric-schleicher** [comment]
well...  this is weird....   it took about 5 minutes for my rollback to  build 51 for them to showup.

**Comment by vigorouscoding** [comment]
yes, the error was introduced 3 days ago, so the snapshots before that worked just fine.

**Comment by amorgner** [comment]
I'm deploying a new snapshot right now.

**Comment by amorgner** [comment]
Should be fixed in snapshot 53.

**Comment by eric-schleicher** [comment]
Comfirm Fixed.  Thanks!
