### ISSUE TITLE
Internationalization of every string value feature request

### ISSUE THREAD

**Issue by Eljah** [structr/structr#345]
I'm not an expert of grahp databases, but it looks like it would be possible to add one of the most important features of CMS to the structr.

Every text label in html node and every String attribute of custom class should have more than one language. Depending on user's culuture, the structr-ui should provide the string value in the correct language. And of course the special editor on the structr ui's admin side that can specify the value in each language.

**Comment by amorgner** [comment]
Thanks for the feature request. In general, I agree that having more multi-language features than there are now would be great, but I don't think that it's a good idea to allow multiple values for each String attribute.

If I understand your request correctly, your suggestion would mean that we'd have different values of the same attribute, one for each language. This would make it very difficult to select or filter objects by a certain value. You would be at least required to have consistent and complete translations for each attribute and each language, and your database and indexes would increase in size.

For internationalization of data, it seems to be good practice to have multi-language support only on the display level and use a single, language-independent value for each attribute on the code/logic level.

Any other opinions?

Regarding HTML elements - you can put a combination of ISO locales in the fields 'Show for locales' and 'Hide for locales' to determine whether a node should be visible for a specific combination of locales. Just create multiple versions of the same page section and show/hide each of them for the desired locales. While not the user-friendliest feature, it works and gives you the flexibility to have completely different layout for each language which is useful in many reald-world cases.

There are more internationalization features on Structr's roadmap, but it's difficult to put them in the right place, so user feedback is highly appreciated!

**Comment by Eljah** [comment]
Hi Axel!
Currently I'm not sure where I  can find 'show/hide for locales' in structr-ui (I haven't checked the latest code, so may be it ia the newset feature). I agree that that's okay for some applications.

The workflow I'd like is a bit more complicated:

1. I'd like you to intrduce some kind of new Java object being used, say, MultilanguageString, and add it to the standard types of the Schema. 
2. MultilanguageString would be the graph object itself and the tree of it should allow such kind of workflow
- there is a root culture/laguage of multilanguage string, for example English
- there are two first-order children of multilanguage string, large national languages, say, Russian and German
- there are second-order children, the child of the first child, the regional languages, say Sorbian and Tatar
The MultilanguageString would analize the locale and culture of the requested value and return
1) if there are all 5 translations for the MultilanguageString the default English String for the English of French locales, Russian and German for the Russian and German locales, Sorbian and Tatar for the Sorbian and Tatar locales
2) if there are only English, Russian and German translations, ther English and French locales show English text, Russian and German show correspndingly Russian and German and the Sorbian and Tatar lcales are showing German and Russian text correspondingly
3) if there is only default English text, all locales are showing only English text

As for the usage of the MultilanguageString, there would be

1) text labels in html (the language structure may be shown directly in the html elements tree, that would be very convinient)
2) the usage instead of usual Java string as field of the objects that I can design in schema (wtih possiilities of user-friendly editing of them in structr-ui)

for me, the graph localization would be very promising and very convinient thing not ever introduced to any of CMS I have seen before.

**Comment by vigorouscoding** [comment]
You can find the show/hide conditions for locales in the edit dialog of any DOM node (see the attached screenshot)

![screen_shot_2015-03-09_at_09_58_04](https://cloud.githubusercontent.com/assets/3099108/6552194/91b253f0-c643-11e4-9901-6c9d8b98c4ce.jpg)

**Comment by Eljah** [comment]
Kai, thanks for the answer!

Yes, that's make possible almost all possible internationalization on the html/dom level (but unfortunately still not in the most user-friendly way). As for me, the internationalization of text in the data objects has more priorities for the real usage cases.

**Comment by vigorouscoding** [comment]
It seems you know your way around Java - how would you like to contribute to structr by creating a fork of it and implementing your idea. When it is done and has unit tests you can send a pull request. If the code meets the requirements and does not break anything else (i.e. run "mvn test" and dont see any errors) then the chances are pretty good that you will see your idea implemented in structr.

I think that your idea is pretty nice and that way you'd be able to shape the feature to your needs (well... while keeping it useful for others as well ;) )

**Comment by Eljah** [comment]
to add some more desirable behavior of the MultilanguageString:

when I add it to the object, I define the tree of languages in the Schema, say

root (English)
\- German
    \-- Sorbian
\- Russian
    \-- Tatar

Then I'm populating the translations of the texts to my objects without thinking about the language hirearchy and the fullness of the translations of all texts into all langauges. Say, my UI will display 5 text textareas (or one textarea and language select dropdowns) and I will fill them according to translations I'm currently have to the time.

More use cases:

1) for the current example I have only English translation and Tatar translation. So, English, Russian, German, Sorbian and any other locales should show English text, and the Tatar locale should show Tatar text (note, not to show Tatar for the Russian locale)
2) for the current example we have only Russian text and Tatar text. So, for English, German, Sorbian, any other and of course Russian locale the Russian text will be shown, for the Tatar locale the Tatar one.

**Comment by Eljah** [comment]
Okay, I'll try to implement it by myself (since I'm still doing my first steps with graph databases)

**Comment by amorgner** [comment]
Thanks Kai for pointing this out.

Let me add to Kai's statement about implementing it in Java and the option you do it yourself. Of course that's a valid choice as we always welcome Pull Requests. But considering that this would be an extension which is far from being trivial in any direction. Take into account the many places where this would have implications: Basic data model, indexing, user interface, existing and new tests, to name just a few.

I'd rather continue the discussion here and hear some more opinions of Structr users (and developers of course), before deciding anything.

I don't want to discourage you from trying yourself, but if I should estimate the efforts to do it myself or with the Structr team, I'd come up with something between one and three months.

Another option how to implement this would be not in the Java code basis of Structr, but just using the custom data model itself. You could relatively easy create your own variable classes and map the multi-lingual attributes to the graph. Infact, this would be the preferred way I'd recommend today.

**Comment by amorgner** [comment]
In recent snapshots, we introduced attribute labels, at least for local attributes. These labels can be used for internationalization/localization of attribute values.

You could create four attributes, for instance textEN, textRU and textDE. Then set an appropriate label to name the field (like Text, текст etc.) and put the different values in it.

To display the locale-dependent attribute, you could create a Function property named just "text" and put something like this into it:

	{
		var obj = Structr.get('this');
	 	var locale = Structr.get('locale').slice(0, 2);
	 	  	 	/* RU > EN > DE */
	 	  	 	var default_order  = ['ru', 'en', 'de'];

	 	  	 	var field_mapping = {
	 	  	 	 		'ru': 'textRU',
	 	  	 	 		'en': 'textEN',
	 	  	 	 		'de': 'textDE'
	 	  	 	};
	 	  	 	
	 	  	 	/* get the locale order for the current user/locale */

	 	  	 	var user_order = [locale];
	 	  	 	default_order.forEach (function (l) {
	 	  	 	 		if (l != locale) {
	 	  	 	 			user_order.push(l);
						}
				});
	 	  	 	var localizedName = null;
	 	  	 	user_order.forEach (function(l) {
	 	  	 	 		if (localizedName == null && obj[field_mapping[l]] != null) {
	 	  	 	 		 		localizedName = obj[field_mapping[l]]; 		
	 	  	 	 		}
	 	  	 	});
	 	  	 	
	 	  	 	return localizedName;
	}

Does that help?

**Comment by Eljah** [comment]
Hi Axel! The solution seems to be okay to solve the internationalization problem.

I need to upgrade to the latest solutions first. Could you provide me a tutorial for database backup that I would like to do before the upgrade? Then I'll try with this update and internationalization solution.

**Comment by amorgner** [comment]
Creating a backup of your Structr data is very simple:

1. Stop the instance
2. Make a copy of the directoriey ``db/`` and ``files/``
3. Start the instance

To restore the backup, just stop the instance again and replace the current folders with the backup, then start again.

BTW, we've changed the way localization works again. We removed the attribute labels from the schema and replaced it by a loosely coupled implementation.

Maybe @vigorouscoding can explain a bit more how it works. :-)

**Comment by vigorouscoding** [comment]
The current way localization can be done is by creating entities of the builtin type ````Localization```` and calling the (currently undocumented) ````localize()```` function.

## Localization

Localization has 4 properties which are of interest:

- ````name````  This is the key that will be used to look up localizations
- ````domain````  Will be used to make localizations more specific
- ````locale````  The locale for which the localization is intended
- ````localizedName````  The localized string itself

*Currently there is no dedicated UI in Structr-UI for Localizations. You can create the entities in the CRUD area ("Data").* ***If the Localization type does not show up you need to first create a "Resource access grant" und "Security".***

## The localize() function

````localize(key[, domain])```` takes a mandatory key and an optional domain parameter: 
- ````key```` corresponds to ````Localization.name````
- ````domain```` corresponds to ````Localization.domain````

- The current locale of the request/user is used (see next section)
- If only ````key```` is provided the first matching instance of Localization will be returned where ````Localization.name == key && Localization.locale == currentLocale````. If none is found the key itself will be returned.
- If ````key```` and ````domain```` are provided the function will return the first Localization instance with ````Localization.name == key && Localization.domain == domain && Localization.locale == currentLocale````. If none is found the function will fall back to the behavior where only ````key```` is provided.

## Current locale

The current locale of the user is auto-detected like this (in descending priority):

1. Parameter ````locale```` in the current request (for example: http://localhost:8082/?locale=en_US)
2. The Locale of the User (for logged in Users... the User type has a new String property ````locale```` where the user-defined locale can be stored)
3. The locale of the browser requesting the resource.
4. The system locale of the server (should not be used because the browser should have a locale)



## Basic usage

If you wanted to globally localize boolean values for example you would do something like this:

1. Create 2 intances of ````Localization````:
````
{
	name: “true”,
	domain: null,
	locale: "en_US",
	localizedName: “Yes",
},
{
	name: “false”,
	domain: null,
	locale: "en_US",
	localizedName: “No",
}
````

2. Everywhere where you output boolean values you would need to do this
````
${localize(boolVariable)}
````

## Using "domain"

This takes the basic example one step further by adding a domain to the localization

1. Create 4 (or x) intances of ````Localization````:
````
{
	name: “true”,
	domain: null,
	locale: "en_US",
	localizedName: “Yes",
},
{
	name: “false”,
	domain: null,
	locale: "en_US",
	localizedName: “No",
}
{
	name: “true”,
	domain: "l33t",
	locale: "en_US",
	localizedName: “Hellz yeah!",
},
{
	name: “false”,
	domain: "l33t",
	locale: "en_US",
	localizedName: “Hell no!",
}
````

2. Everywhere where you output boolean values you would need to do this
````
${localize(boolVariable, domain)}
````

--------------------


We think this decoupled approach gives the user a maximum of flexibility to localize their apps.

Hope this clears things up! :)

**Comment by amorgner** [comment]
Thanks @vigorouscoding for this in-deep explanation. I'll close this issue, as I think @Eljah's questions are covered. @Eljah if you're not satisfied with the proposed solution, or have ideas on how to improve localization/internationalization, feel free to reopen this ticket, or create a new one with specific questions/requests.
