### ISSUE TITLE
improve visibility for nodes' tree

### ISSUE THREAD

**Issue by Eljah** [structr/structr#346]
Right now it is possible to set up the overlying node as invisible, while the underlying node visible. Such kind of visibility settings makes both nodes invisible.

The improvement would be to mark the underlying node as 'de facto invisible' in the tree is the overlying node is set to be invisible.That would improve the user experience of nodes' tree.

**Comment by eric-schleicher** [comment]
are you sure about that.   i don't think that this works the way you're thinking. 

A parent with not visible can have a child that is visible.

**Comment by amorgner** [comment]
Eric is right. @Eljah please take into account that you can access any tree node in Structr by its UUID, like e.g. ``http://localhost:8082/47103731168f47589ccb74f37e4d8adc`` to use it as a partial.

To workaround the difficulties you had regarding the visibility, I think it's good practice just set the visibility top-down for all nodes with the 'recursive' switch, and test the visibility from the command line with curl.

Closing this for now, as there's a good reason for the way it works now.

**Comment by Eljah** [comment]
okay, what actually means if parent is invisible and child is visible? what kind of html should be in the output?

**Comment by Eljah** [comment]
actually, hof the simple cms-workflow the feature makes some stress for the designer since it is not intuitive

**Comment by amorgner** [comment]
It's a tree, so if the parent is invisible, all children are invisible, too.

Besides visibility, there are more levels of access control, e.g. user/group-based access rights, or boolean show and hide conditions, or languages, which can be applied to every single page element. This makes Structr very flexible but puts some burden on the developer, I understand what you mean, but designwise, we put flexibility before easy-of-use. However, there are plans for a more user-friendly, web-designer friendly UI, so your input is highly welcome.

**Comment by Eljah** [comment]
yes, I understand the advantage of flexibility over easy-to-use. that's why I'm asking not tor the rule that makes all children of invisible parent invisible, but some kind of marker or icon or reminder, visible for the designer to inform about the final visibility. just add new colours of your already existing key icon!

**Comment by amorgner** [comment]
What I could think of is different background colors based on visibility/accessibility, and a new vertical tab (like Active Elements), highlighting/showing only the visibility aspects of a page tree.

Would you like to help us here and create a (graphical) suggestion how it could look like and work?

**Comment by eric-schleicher** [comment]
How would this be different between the key icons in the current implementation?  e.g.  right now the state of the key (IMHO) clearly indicates the accessibility of the node.

This one seems pretty intuitive to me, and i rather like the ad-hoc recursion in the security dialog.

**Comment by Eljah** [comment]
![image](https://cloud.githubusercontent.com/assets/2749858/6547592/8f1e8a74-c5ed-11e4-95dd-4759708c6bcf.png)

Let's imagine I have a large number of element stacked. And the uppest which is a body on th ecurrent screenshot was marked to invisible for some group;

Then  have to scroll down to work with underlying child elements like that:

![image](https://cloud.githubusercontent.com/assets/2749858/6547608/d7c93512-c5ed-11e4-8c72-8939c077f968.png)

And the parent element, invisible for some grup is no longer in the visible part of my tree. The only thing I want is to have, say a little red dot in the place of key icon marking that somewhere in the tree there is an invisible parent.
