### ISSUE TITLE
Not able to login (using admin/admin as username and password)

### ISSUE THREAD

**Issue by poojacmore** [structr/structr#347]
I am not able to login to the dashboard. I have followed all the steps mentioned in the read me file, after cloning the github project.
Everything is working fine except the login page.
Can you please tell me, which file initializes the login credentials?
I tried to look into file structures also, to find the login credentials. Could not find it.
Please help me.

**Comment by vigorouscoding** [comment]
Hi, are there any error messages in the log file? Do you get to the login form at all? Please share your logs/server.log file.

**Comment by poojacmore** [comment]
Hi Kai,
I dont have any any file in logs folder.
Yes I am getting the login window. But when I enter admin as username and
admin as password, it is throwing wrong username and password error.

Please help me.


Regards,
Pooja

**Comment by poojacmore** [comment]
Hi Kia,

I am getting something like this in my terminal,

INFO: New connection with protocol 13
Feb 25, 2015 9:56:35 PM org.structr.core.auth.AuthHelper
getPrincipalForPassword
INFO: No principal found for eMail admin
Feb 25, 2015 9:56:35 PM org.structr.websocket.command.LoginCommand
processMessage
INFO: Could not login admin with admin


Regards,
Pooja

**Comment by vigorouscoding** [comment]
Ok - it looks like you do not have a user "admin" in the database.
The most likely cause is that you dont have a seed file or the seed wasnt imported...

Please check if a seed.zip file is in your folder - if it is not present please download it from here: https://github.com/structr/structr/raw/master/structr-ui/seed.zip and place it in the "structr-ui" folder.

Then restart structr.

----

If the seed-file is present, remove the folder "db" and "files" and restart structr.



I hope that helps.

**Comment by poojacmore** [comment]
Hi Kia,
It really helped me...
Thank you so much.. :)

Regards,
Pooja
