### ISSUE TITLE
Relationship Cardinality challenge with ResourceAccess?

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#348]
# Problem/Issue

Test | Cardinality  | Relationship URI | Response | Result | Expected
------------- | ------------- | ------------- | ------------- | ------------- |  -------------
1 | 1:1 (desired)  | HasImageBasedVisualization | 200 | No Result | Data
2 | 1:1 (desired)  | HasImageBasedVisualizations | 200 | No Result | Error or (no error and data)
3 | 1:n (not-desired)  | HasImageBasedVisualization | 200 | No Result | Error or (no error and data)
4 | 1:n (not-desired)  | HasImageBasedVisualizations | 200 | Result | Data

Test Number 1 cannot be made to return result as desired/expected when model set to 1:1 relationship

It would be nice is the system is going to be cardinality aware, that it 404 or 40X when request does not match relationship, or be entirely indifferent to plurality.  beyond this issue, it's highly confusing and very difficult to build a mental model of the relationships between signatures, relationsihp URI plurality, attributes in view, and node visibility.  It's a lot to sift through to debug.

## TL:DR version below:
----
I have a situation where a resource access signature works when relationship cardinality is set to 1:n.  but does not when set to 1:1 (the modelers design intent).

for context here is the relevant portion of the domain model:

![image](https://cloud.githubusercontent.com/assets/8261783/6421607/6ed5beb4-be85-11e4-804f-30f870967bdc.png)

***Both*** of these Entities have two views.  The **public** view listing (just) *id*, and *type* and a **default** view with all of the attributes.

There are Three instances (nodes) of **ImageBasedVisualization** data; each related to a single **Variable**.  These data nodes are visible to both public and authorized users and are owned by the 'admin' user.  

Here are the relevant resource access entries:
 - Variable/HasImageBasedVisualization
 - Variable/HasImageBasedVisualization/_Default

When this relationship is set to 1:1, hitting the rest endpoint with cardinality matched (singular) URI: 
```
example.com/structr/rest/variables/33e286cefd9d475b8841a56f48f8302f/HasImageBasedVisualization/default
```
Produces the following result:
![image](https://cloud.githubusercontent.com/assets/8261783/6421490/664aae2c-be84-11e4-9d20-6a69bda103ff.png)

I believe this to be in error,and am expecting one node representing the ImageBasedVisualization. related to the variable with the stated ID that.

With the relationship set to 1:1, willfully pluralizing the URI (HasImageBasedVisualization**s**), also returns an empty 200 result.  This however is very counter-intuitive, based on the relationship cardinality (1:1) and the request.  I was expecting some form of 400 due to the cardinality mismatch...  Or, in the scenario that i got a 200, to at least get the relevant data (which is known to exist)
```
example.com/structr/rest/variables/33e286cefd9d475b8841a56f48f8302f/HasImageBasedVisualizations/default
```

![image](https://cloud.githubusercontent.com/assets/8261783/6421531/b66df0da-be84-11e4-9b95-b391555c656c.png)

Going to #Schema and changing the relationship between these two entites **to** 1:n (which is not the desired cardinality) results in a result with records (as expected)...  But only when when providing the pluralized Relatinosihp URI segment.  when providing the Singularlizes version, i get no error, no result.

I should be able to set 1:1 relationship and use the singularized relationship URI segment.

Please advise.

**Comment by eric-schleicher** [comment]
Bump.

**Comment by eric-schleicher** [comment]
@vigorouscoding or @amorgner is there more detail i can provide on this one?  this one will start to hurt in about a week.

**Comment by amorgner** [comment]
@vigorouscoding has already reproduced it and created a fix. I'm currently trying to reproduce your and Kai's results and testing the fix.

**Comment by vigorouscoding** [comment]
I just committed/pushed the fix for this issue. When the next snapshot is available please retest this issue and close if resolved.

thanks for bringing this to our attention!

**Comment by eric-schleicher** [comment]
confirmed fixed.  Thanks!
