### ISSUE TITLE
Not able to connect things in mobile application

### ISSUE THREAD

**Issue by poojacmore** [structr/structr#350]
I have followed the demo application provided on website. But facing some issues.
I am struggling in creating a new entry in database.
How to impose constraints on each database field for validation?
Please help me.

**Comment by vigorouscoding** [comment]
Ok - a couple of questions beforehand:

> Not able to connect things in mobile application

- Do you mean in the schema editor?
- And do you mean that you are using a tablet to edit the schema?

> I am struggling in creating a new entry in database.

- do you mean a creating a new Type in the schema?
- or do you mean adding a data entry (in the "Data" tab) to an existing type

> How to impose constraints on each database field for validation?

- what kind of property are we talking about?
- Screenshots would be perfect to see what you are trying to do and possibly help you better

Thanks!

**Comment by poojacmore** [comment]
Hi Kai,
sorry as I didn't mention what I am working on.
I have attached the form file which is my view, and the schema file which
is the only table in my database right now.
I want to successfully create one record in the database, with proper
connections.
In relational databases we first create connection with database and then
add values to respective attributes accordingly.
But I am not getting how to deal this simple thing in Structr.
Please help me, I am developing this application for my master thesis.


Regards,
Pooja

**Comment by vigorouscoding** [comment]
Hi Pooja,

sadly the attachments seem to have gotten lost... at least I can't see them. If you made screenshots you can just drag'n'drop them into the text-field on github.com. They will automatically be uploaded.


From the details you provided I tried to make a small step-by-step guide how to create data types, connect them and add data through structr-ui.
I hope that helps! If so we can close this issue I guess :)


![step_1](https://cloud.githubusercontent.com/assets/3099108/6488496/34ea2d22-c298-11e4-80d7-f4584795fb6d.jpg)
![step_2](https://cloud.githubusercontent.com/assets/3099108/6488503/39f61c7c-c298-11e4-8606-ac695e961f77.jpg)
![step_3](https://cloud.githubusercontent.com/assets/3099108/6488504/3bc076ce-c298-11e4-986e-598a74767c2c.jpg)
![step_4](https://cloud.githubusercontent.com/assets/3099108/6488508/3d4d84be-c298-11e4-8267-dfc60fa5023d.jpg)
![step_5](https://cloud.githubusercontent.com/assets/3099108/6488510/3f439d44-c298-11e4-83a1-7d58a54e777a.jpg)
![step_6](https://cloud.githubusercontent.com/assets/3099108/6488513/4206d2a8-c298-11e4-9bd5-49cbb732e4f4.jpg)
![step_7](https://cloud.githubusercontent.com/assets/3099108/6488514/448acd4a-c298-11e4-93c6-50e4870729bd.jpg)
![step_8](https://cloud.githubusercontent.com/assets/3099108/6488516/471c1bae-c298-11e4-8054-df8071360360.jpg)
![step_9](https://cloud.githubusercontent.com/assets/3099108/6488520/49976d2a-c298-11e4-8c2d-e38103e0dca7.jpg)

**Comment by poojacmore** [comment]
Hi again,
I have figure out how to add table in Structr, but my problem is different.

My forms.html file is,

<div content-for="title">
  <span>Forms</span>
</div>


<div class="scrollable">
 <div class="scrollable-content section">
   
   <form action="" id="" name="form1">
     

     <div bs-panel title="Create new User">

       <input
        bs-form-control
        id="uname"
        type="text" 
        ng-required
        ng-model="app_user.name"
        label="Name" 
        label-class="col-xs-3 col-sm-2 col-lg-1" 
        class="col-xs-9 col-sm-10 col-lg-11"
        placeholder="User Name"
       />
       
       <input
        bs-form-control
        id="uaddress"
        type="text" 
        ng-model="app_user.address"
        label="Address" 
        label-class="col-xs-3 col-sm-2 col-lg-1" 
        class="col-xs-9 col-sm-10 col-lg-11"
        placeholder="Address"
       />
       
       <input
        bs-form-control
        id="utelno"
        type="text" 
        ng-model="app_user.tel_number"
        label="Contact Number" 
        label-class="col-xs-3 col-sm-2 col-lg-1" 
        class="col-xs-9 col-sm-10 col-lg-11"
        placeholder="Contact Number"
       />
       
        
         <input 
        bs-form-control
        ng-required
        id="uemail"
        type="email" 
        ng-model="app_user.email_address"
        label="Email-Address" 
        label-class="col-xs-3 col-sm-2 col-lg-1"
        class="col-xs-9 col-sm-10 col-lg-11" 
        placeholder="Email Address"
        />
         
       <input 
        bs-form-control
        id="ueducation"
        ng-required
        type="text" 
        ng-model="app_user.education"
        label="Education" 
        label-class="col-xs-3 col-sm-2 col-lg-1"
        class="col-xs-9 col-sm-10 col-lg-11" 
        placeholder="Education"
        />
       
       
  
       
       <input
        bs-form-control
        id="uoccupation"
        ng-required
        type="text" 
        ng-model="app_user.occupation"
        label="Occupation"
        label-class="col-xs-3 col-sm-2 col-lg-1"
        class="col-xs-9 col-sm-10 col-lg-11"
        placeholder="Occupation"
        />  
       
       

       <switch
        bs-form-control
        id="upaperstatus"
        ng-change="switchChanged()"
        ng-model="app_user.paper_published"
        ng-click="switchClicked()"
        label="Published paper before"
        label-class="col-xs-3 col-sm-2 col-lg-1"
        class="col-xs-9 col-sm-10 col-lg-11" 
         >
        </switch>
       
       
       <div>
  <div ng-show="app_user.paper_published">
    <span>
      <input
        bs-form-control
        id="uexpertise"
        type="text" 
        ng-required
        ng-model="app_user.expertise_area"
        label="Area of Expertise"
        label-class="col-xs-3 col-sm-2 col-lg-1"
        class="col-xs-9 col-sm-10 col-lg-11"
        placeholder="Expertise Area"
        />  
    </span>
  </div>
</div>
<div>
  
  <div class="check-element animate-hide" ng-hide="app_user.paper_published">
    <span>
       <input
        bs-form-control
        id="uinterest"
        type="text" 
        ng-model="app_user.interest_area"
        label="Interest area"
        label-class="col-xs-3 col-sm-2 col-lg-1"
        class="col-xs-9 col-sm-10 col-lg-11"
        placeholder="Interest Area"
        />  
      </span>
   
    
  </div>
</div>
       
       
        <div class="form-group">
                <label for="pwd">Password</label>
                <input id="pwd"
                       type="password"
                       ng-required
                       class="form-control"
                       placeholder="Password"
                       ng-change="onChange()"
                       ng-model="app_user.password">
            </div>
       
       <input
        bs-form-control
        id="upwd"
        type="password" 
        ng-model="pp_user.password"
        label="Re-enter password"
        label-class="col-xs-3 col-sm-2 col-lg-1"
        class="col-xs-9 col-sm-10 col-lg-11"
        placeholder="Re-enter password"
        />  
       
       
     </div>

     
     
     
      
    <div bs-panel class="form-actions">
      <div content-for="navbarAction" duplicate>
        <button class="btn btn-large btn-success" ng-disabled="form1.$invalid" ng-click="addNewUser(app_user)">Create New User</button>
      </div>
    </div>
   </form>

 </div>
</div>


<div class="panel panel-danger" ng-show="showReqs">
    <div class="panel-heading">
        <h3 class="panel-title">Password Requirements</h3>
    </div>
    <div class="panel-body">
        <ul>
            <li ng-repeat="req in reqs">{{ req }}</li>
        </ul>
    </div>
</div>
 


and my current table for App_User looks like,

App_User
Local Attributes
address	String	
education	String	
email_address	String	
expertise_area	String	
interest_area	String	
name	String	
occupation	String	
paper_published	Boolean	
password	String	
tel_number	String	
Methods
Views
Remote Attributes

This is present under schema section.

Please guide me how can I insert record inserted from Form.html
How can I connect my data inserted in form textfields to the back-end.
Need help in writting the .js file function of 
<button class="btn btn-large btn-success" ng-disabled="form1.$invalid" ng-click="addNewUser(app_user)">Create New User</button>
addNewUser() function with Structr

Please see if you could help me.
And sorry if it is a silly question.


Regards,
Pooja

**Comment by vigorouscoding** [comment]
Structrs security model is prohibiting you from just posting to /structr/rest/invoices.

You need to create a "Resource Access Grant". (See the screenshot below)
Just search for the Grant with the signature "App_User" and add the Grants you want to add. This needs to be done for any resource you want to read from/write to.
(If you just want to test this you can just add all grants... but before you deploy the application into the wild you **need** to think about security. Add Grants for specific users etc.)

![screen shot 2015-03-05 at 10 48 32](https://cloud.githubusercontent.com/assets/3099108/6502642/a6cab208-c325-11e4-9171-9af3a62e09f8.png)

**Comment by poojacmore** [comment]
Hi Kai,
I have changed the security setting for my particular table.
But still I am not able add the record from front-end to back-end.
Can you please explain me a bit about how this function is written?

var scrollItems = [];

  $http.get('/structr/rest/tasks').
  success(function(data, status, headers, config) {

    scrollItems = data.result.map(function(task) {
      return task.name;
    });
    $scope.scrollItems = scrollItems;
  }).
  error(function(data, status, headers, config) {
    console.log(data, status, headers, config);
 });

under this link.
https://structr.org/blog/example-application-with-mobile-angular-ui


Please reply,

Regards,

Pooja

**Comment by amorgner** [comment]
Hi, sorry to interfere here, but please note that GitHub issues should only be used for bug reports and feature requests, as stated here: https://structr.org/community

For general questions, please post on Structr's mailing list/forum: https://structr.org/forum
In the forum, there are a lot more people able to help (as here on GitHub people are mostly developers, and in the forum also users).

Furthermore, your questions are a little beyond the scope of Structr and more related to JavaScript/AngularJS, so I would suggest to create a either a forum thread or a post in the comments section of the blog post you mentioned: https://structr.org/blog/example-application-with-mobile-angular-ui#disqus_thread

I hope you understand that we have to close this issue for the above reasons.
