### ISSUE TITLE
Not able to create manual entry in schema object 

### ISSUE THREAD

**Issue by poojacmore** [structr/structr#352]
Hi,
I have two tables which are not connected to each other in Structr schema.
In one table when I click on the create new App_User(App_User is name of my object). I do get the new entry window, but after filling all values when I try to save them, I am getting 
{Not found code 404} error
I have added schema access to this object.

This was giving me problem, so I created new object (Researchers) with same attributes but with different name.
In this case I am getting another problem, I can edit the entries but only two attributes of that object. I have 10 attributes in that object. But I am not able to edit them with create new Researchers, even if I edit then they are appearing as NULL in export CSV file.

Please help.
This is the my Schema object.
![view](https://cloud.githubusercontent.com/assets/11183873/6519166/d6fb01a4-c3b0-11e4-94e3-c84e83d7c5ed.png)

As you can see, in next picture, when clicked on edit option in Researchers I am getting just name and address to edit or add in the new record,
![fieldsaremissing](https://cloud.githubusercontent.com/assets/11183873/6519226/b1ba984a-c3b1-11e4-8da1-0c65b1c796b4.png)

**Comment by eric-schleicher** [comment]
Hi poojacmore,

Ive developed the following naming best practice(es), and dont get the
errors that your showing here, but recall them from experimenting earlier
on.

Entities: names should be TitleCase.
They should also be singular.  Avoid words with complex/counter-intuitive
plural spellings.

E.g.

Loaders
DesignPhotos
WillfulParticipants

Be descriptive in your names.   Remember that you can inherit and extend
the entities that you create, so think top down.

(Inheritance)

Image -> DesignImage
Image -> ProfileImage

File -> Font.

Your relationships will be contextual,  easy to understand and efficient.

Atrribute names should be camelCase

E.g

emailAddress
telephone
nameLast

Relationships should be CAPS_WITH_UNDERSCORE

E.g

(Person) HAS (Weapon)
(Video) DEMONSTRATES (product)
(Image) DEPICTS (emotion)
(User) USES_AVATAR (ProfileImage)

If you do this, the auto naming of the remote atrribute (in the entity
dialogs) will be quite good.

Hope this helps.

Eric

**Comment by poojacmore** [comment]
Hi Eric,
I have followed your suggestions, but still getting the same error.
{Not found:code 404}
When I am clicking on the save button getting this error in red color.
![problem](https://cloud.githubusercontent.com/assets/11183873/6519720/ade73f46-c3b8-11e4-99ed-51a7a6f1256c.png)

What can be the problem?

**Comment by poojacmore** [comment]
Is it possible to drag the html file from FILES menu to the PAGES menu? and yes then can you please tell me how?

**Comment by amorgner** [comment]
@poojacmore Please note that this is not the right place for this kind of questions and discussions.

Any kind of "how do I" and "how to" questions which are not related to malfunctions or missing features in Structr don't belong here.

**Comment by eric-schleicher** [comment]
@poojacmore would like to help you on the google group, can you post question(s) there....  

I'm not sure why dragging from file to page is a normal action.

**Comment by poojacmore** [comment]
Hi Eric,
I have joined the group. But I am not able to start any topic. :(
Can you please help me in that?
How I can create new discussion in group?

Regards,
Pooja

**Comment by amorgner** [comment]
@poojacmore You're now approved to post in the google group.

On the above: Please check the name of your custom type, it's plural (AppUsers), but should be singular as Eric wrote.

Yes, it's possible to drag files from the Files section onto a page, but HTML files would just be included as an ``<a>`` link to download that file. I can't think of a case where this makes sense.
