### ISSUE TITLE
Not able to load my Data and Type section

### ISSUE THREAD

**Issue by poojacmore** [structr/structr#353]
I had problem inserting new record in Data section.
I was getting 
Not found code 404 error
I tried to save record 3-4 times.
And after that all of a sudden, my DATA section and TYPE section are not working at all.

![datasectiondown](https://cloud.githubusercontent.com/assets/11183873/6520038/2b6e84c0-c3bd-11e4-8dde-1379bd5ea541.png)

Please guide me how I can get these things back to work.

Regards,
Pooja

**Comment by amorgner** [comment]
This is probably the same naming issue Eric explained in https://github.com/structr/structr/issues/352#issuecomment-77499074.
