### ISSUE TITLE
visible flags of relation

### ISSUE THREAD

**Issue by Eljah** [structr/structr#354]
![image](https://cloud.githubusercontent.com/assets/2749858/6590941/c8247788-c7c9-11e4-864d-151b4dc4183e.png)

I haven't checked the latest snapshot code but in what I'm actually having in 1.1-SNAPSHOT build 266e5 (my fork) the relation created by default doesn't have any visible to public and visible to authenticated user values by default in schema editor. That's why I had problems with displaying the data associated through the data binding with the relation. If there are no such flags in the relation, structr suppose them to be... mmm... default and doesn't return the relation data to the public user (but returns it to the admin one).

I have fount the hack - I have added the boolean flags visibleToAuthenticatedUsers and visibleToPublicUsers manually in the Schema editor. That would be enough to make relation working in the same manner as objects are working.

I think it would be more friendly to the user (despite it is not a problem to find out this hack for the advanced user) to create such flags for all relations by default too.

**Comment by eric-schleicher** [comment]
i can't help you with your primary problem, but you can certainly define an onCreate Entity Method with the following code to make your new nodes visible:
```
(
set(this, 'visibleToPublicUsers', true),
set(this, 'visibleToAuthenticatedUsers', true)
)
```

**Comment by amorgner** [comment]
@Eljah Has your question been satisfactorily answered? Please try a recent snapshot, and if you're still experiencing problems, feel free to open a new issue so we can support you further.

**Comment by FitsnerAS** [comment]
Thanks, it works
