### ISSUE TITLE
Feature Request: SFTP Access

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#355]
As a user, I would like to be able to use SFTP to connect to Structr's internal file system.  I would like to do this because FTP:

- Is not secure (transmits unencrypted passwords)
- Uses unpredictible ports from server back to client that cannot easily be incorporated into data center firewall rules.

rationale:
- I would like to edit Javascript resources in a Desktop IDE where i have the associated benefits i cannot do this over FTP because of the networking environments.

**Comment by cmorgner** [comment]
This could be done using jsch which we already used in one of our projects:
http://www.jcraft.com/jsch/examples/Sftp.java.html

**Comment by eric-schleicher** [comment]
Sweet.  while the browser based editors are nice for coloring, I need to be doing that work in an IDE.  this would allow that.

**Comment by eric-schleicher** [comment]
@cmorgner can you take a guess at how long this would take someone to implement?  It's enough of a pain point for me now that i'll try and get someone to implement it.  I'm wasting huge amounts of time not being able to use an IDE and my effort to get intellij working/connecting to my development instance  have failed.  an SFTP interface to structr files would just eliminate this problem

**Comment by amorgner** [comment]
Hi Eric, let's discuss this. I'll contact you.

**Comment by eric-schleicher** [comment]
OK

**Comment by amorgner** [comment]
Would it be an option to just add TLS/SSL support to FTP (it's called FTP over SSH or FTPS)? https://en.wikipedia.org/wiki/FTPS

In this case we would just enable TLS support for the existing FTP server implementation (https://mina.apache.org/ftpserver-project/configuration_ssltls_support.html) which would be relatively easy, compared to what it means to add a complete new server implementation based on SSHD (https://mina.apache.org/sshd-project/index.html).

**Comment by amorgner** [comment]
According to this https://www.jetbrains.com/idea/help/creating-a-remote-server-configuration.html, you can use FTPS with IntelliJ IDEA 14.

**Comment by eric-schleicher** [comment]
I'm in the process of moving everything but user content out of Structr's file system to avoid some of the issues driving the original submission.  This is not a high priority for me since I'm almost done with that. moving to angular also reduces the need for this as a specific solution while things are being developed.

that being said, the main challenge I was having was "data center networking" where the very little/no control over what ports get used once an FTP connection is established interfered with my networking rules.  I'm not sure if TLS changes this, but SFTP definitely does as it tunnels through a single port).
