### ISSUE TITLE
Filtering over REST interfaces not working with nested URI(s)

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#356]
see: 
![image](https://cloud.githubusercontent.com/assets/8261783/6728569/faa7c268-cde7-11e4-98ed-96230d7f5cd0.png)

response contains results, but is not filtered per the request

Played around with a few different paths to try and get a filtered result but didn't reach a successful result.

**Comment by eric-schleicher** [comment]
bump.   snapshot no. 60 still impacted by inability to filter on subtree attributes.

**Comment by amorgner** [comment]
This should work with recent snapshot versions (I think no. 70+), at least in my simple test case with 1.1-SNAPSHOT no. 74:

      axel@dev0 ~$ curl -HX-User:admin -HX-Password:admin localhost:8082/structr/rest/foos/25b3830c676f4bf9bf0496058cdfdaf3/bars
      {
         "query_time": "0.000697507",
         "result_count": 2,
         "result": [
            {
               "id": "d18090feb9034efe98d9b13b98e26a4b",
               "type": "Bar",
               "currentStatus": false,
               "name": "Bar1"
            },
            {
               "id": "c7217f933d4e4cc281665bb8cd3ce988",
               "type": "Bar",
               "currentStatus": true,
               "name": "Bar2"
            }
         ],
         "serialization_time": "0.000045703"
      }
      axel@dev0 ~$ curl -HX-User:admin -HX-Password:admin localhost:8082/structr/rest/foos/25b3830c676f4bf9bf0496058cdfdaf3/bars?currentStatus=true
      {
         "query_time": "0.000785364",
         "result_count": 1,
         "result": [
            {
               "id": "c7217f933d4e4cc281665bb8cd3ce988",
               "type": "Bar",
               "currentStatus": true,
               "name": "Bar2"
            }
         ],
         "serialization_time": "0.000032489"
      }
      axel@dev0 ~$ curl -HX-User:admin -HX-Password:admin localhost:8082/structr/rest/foos/25b3830c676f4bf9bf0496058cdfdaf3/bars?currentStatus=false
      {
         "query_time": "0.000946020",
         "result_count": 1,
         "result": [
            {
               "id": "d18090feb9034efe98d9b13b98e26a4b",
               "type": "Bar",
               "currentStatus": false,
               "name": "Bar1"
            }
         ],
         "serialization_time": "0.000029633"
      }

Could you please try again and update this issue?

**Comment by eric-schleicher** [comment]
sorry for the delay in getting back on this one...

This is still an issue as of structr logo1.1-SNAPSHOT build 634bb (201506230124), which i believe is 70+   

I have yet to update to latest, but will check again once i do that.

**Comment by vigorouscoding** [comment]
I'll close this as this is pretty old and should be fixed for quite some time now.
