### ISSUE TITLE
Changing Content Type on simple content Node doesn't enable Save Button

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#358]
When editing a "simple" content node, if the text has remained the same, but the select for the 'content type' is changed, the save button(s) don't re-enable.

The obvious workaround for this is the change a character, like adding a space (which is what i generally do), but it may potentially confuse new users who don't understand that the dialog is checking the content text against the currently saved version.

either updating the content type immediately, **or** enabling the save button after a change in the select would seem to make sense.

**Comment by amorgner** [comment]
On each change of the select element, the new content-type is comitted, independently from the content, no need to save anything.

What's missing is the typical green blinking to confirm the successful status change.

I just added this (and also to the "Line Wrapping" switch) in 67b9fa60c3a40e1e5502eb925c030746e0783840
