### ISSUE TITLE
Feature Request: Make the selection of option on the node easier and less susceptible to mistakes

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#359]
I submit the following example as a proposal to change the UI for selecting action on nodes from: 

![image](https://cloud.githubusercontent.com/assets/8261783/7094877/4e8d8e96-df7a-11e4-8385-b129ccf84370.png)

to something along the lines to this.

![image](https://cloud.githubusercontent.com/assets/8261783/7100160/8774aed4-dfc4-11e4-84b2-4cca733702cf.png)

http://codepen.io/eric-schleicher/pen/yydvya

**Comment by amorgner** [comment]
Thanks, Eric! I really like this one, makes sense. Shouldn't be too hard to implement, let's see... :-)

**Comment by eric-schleicher** [comment]
for reference, this was derived from this:

http://creative-punch.net/2014/02/making-animated-radial-menu-css3-javascript/

**Comment by eric-schleicher** [comment]
here is a similar one for consideration as well.  

http://dabblet.com/gist/3979221/cb69c5e8ccf0745fff2c94b47b27b108931f1a15

**Comment by cmorgner** [comment]
@amorgner, what's the status of this issue?

**Comment by cmorgner** [comment]
I think part of the problem can be solved with the no-so-new-any-more resizable pages tree view flyout feature.

**Comment by amorgner** [comment]
Correct. The width of the flyout can be increased.

A circular tooltip would make sense in the graph browser but not in tree or table like views.
