### ISSUE TITLE
Ability to serve static content via symlink?

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#362]
I'm not sure if it's specifically bad practice, but I would like to be able to serve static content from another folder on the system, which happens to be (inside) a git repository that i clone down onto the server over a symbolic link.  

My objective is easily manage frontend compponents/frameworks like jquery, etc externally to structr.

For backup/restore & maintenance reasons specifically would like to avoid copying/moving that file structure into the /usr/lib/structr-ui/structr folder.

My (validated) understanding of this is that by default, structr will server static assets from /usr/lib/structr-ui/structr folder.

I created a symlink in this folder pointing to the folder that physically houses the static resources I would like to serve.  I was disapointed to discover that Jetty will serve physical files, but not follow links (as noted [here](https://wiki.eclipse.org/Jetty/Howto/How_to_serve_symbolically_linked_files)

In reading through to larn more aobut this insight, it appear that jetty can be configured to allow for this, but that there may be some security implications.  It also seems that in order for this to be enabled, it would have to be incorporated into the main structr project and possibly as a setting configured through the structr.conf.

Interested in this type of functionality...  or the perhaps the ability to link structr directly to a git repository to pull and store (but not access in realtime via GET function) files from a Git(hub) Repository.

Thanks!

**Comment by amorgner** [comment]
Hm, what you describe sounds like you want to extend the functionality of Structr itself by including external libraries etc., and not content in Structr.

It's true, Jetty serves the static resources the Structr backend UI needs to run from the mentioned folder, but static resources of the custom content in Structr is served through a servlet which is controlled by Structr's metadata.  The files itself are stored in the files/ folder (filename is the File node id).

Do you want to server static resources for your own content pages, or extend Structr?

**Comment by eric-schleicher** [comment]
I wanted to use bower to manage Javascript & CSS framework  dependencies that i use in shared components, but do that outside of structr (and inside git). 

In this example, HTML of the shared components (HTML contents)would refer 'directly' to files in a subfolder of '/structr/ ,expecting them to be statically served.

So in concept the practice would be to create/manage package.json via bower and have that in git.  then clone the repo locally on the server, run the install locally (to download) the dependencies, and then have a symlink from where Structr serves static files to the actual location of the folder.  I would also be able to remap this as needed and test changes a bit cleaner.

Keeping these file physically out of the usr/lib/structr-ui/structr folder also keeps them out of my backups.

The objective was to have a boilerplate/static resources managed in git and to use structr's "file system" just managing user content.

-Eric

**Comment by eric-schleicher** [comment]
this would be clever, but sounds like its a bigger deal to implement as it would require non-trivial changes...  it's just not that important..  Closing

**Comment by cmorgner** [comment]
This is in fact possible with the latest snapshot, you can use the new exec() built-in method to call a script registered in the structr.conf like this:

my.exec.key = cat /tmp/test.txt

And do the following in the content element:

${exec('my.exec.key')}

and it will display the contents of the file.

This is a very experimental feature though..

Best,
Christian


Am 2. November 2015 21:07:25 MEZ, schrieb Eric Schleicher <notifications@github.com>:
>this would be clever, but sounds like its a bigger deal to implement as
>it would require non-trivial changes...  it's just not that important..
> Closing 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/structr/structr/issues/362#issuecomment-153142301

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
