### ISSUE TITLE
rudamentary auto layout

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#363]
Upgrade Time yay!

oh wait.  
![image](https://cloud.githubusercontent.com/assets/8261783/7602056/324378a4-f8d4-11e4-9531-f2ba1419f73a.png)

it dawned on me that this expeirence is particularly tedious because you cannot select multiple entities or otherwise move more than one thing at a time.

no real expectation on this, just would be nice for it to guess a layout that isn't purely diagonal.

**Comment by ravensorb** [comment]
I agree with this one :)  I have this happen regularly.  It would also be nice to see a little more "collision" detection on overlapping relationships and their respective labels.

**Comment by amorgner** [comment]
We tried auto-layouting, but it's a science in itself.

What Structr does in the most recent snapshots is saving the layout in the backend.  There's a (hidden) String property on the User entity named 'localStorage' where each schema node's position is stored.

If the layout seems broken/reset, you can try the following:

1. Logout
2. Clear the browser's local storage
3. Login again

**Comment by eric-schleicher** [comment]
I'll leave this open for someday

**Comment by amorgner** [comment]
See #296

**Comment by eric-schleicher** [comment]
Closing per @amorgner 's reference to 296.
