### ISSUE TITLE
Too many pages listed on pages tab

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#364]
See the following UI goof in 1.1 snapshot 64.
I've seen it previously (but much more infrequently) in prior builds, but this one seems particularly afflicted, this happens very regularly many times a day.

 \<CTRL\> + R page refresh cleans it up.

![image](https://cloud.githubusercontent.com/assets/8261783/7711117/442fafe4-fe1d-11e4-880b-bf4a977d5eba.png)

Just doesn't work as well as other parts of system, leaves the user with lower percepton of app quality.

**Comment by amorgner** [comment]
It's a (known) timing problem when you have many pages and a somewhat slow connection, will be fixed in one of the next snapshots.

In the meantime, reducing the number of pages displayed with the pager element (above the pages in the Pages Tree tab) might help.
