### ISSUE TITLE
Support for OAuth Token via REST API login

### ISSUE THREAD

**Issue by ravensorb** [structr/structr#369]
Allowing OAuth authentication via the web ui is a create start, however it would be nice to also be able to use this same token and validate/login a user via the REST API.  This could be as simple as extending the current login API to support an additional attribute called for the oauth token with the result being identical to the current login process.

**Comment by derkaiserreich** [comment]
Structr now supports authentication via JWKS. See https://docs.structr.com/docs/handling-user-sessions?highlight=jwks#authenticating-jwks-provider for more information. 

Closing the issue, since it is resolved.
