### ISSUE TITLE
system and user namespace collisions:  the Id/UUID Attribute

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#371]
I do not have a clear recommendation or course of action to propose for the following observation save that Dogmatically, Structr should not pollute the user's namespace.  While in many ways it's totally appropriate for Structr to use such an attribute for a critical internal function, but at the moment the system i quite inflexibly if other data being presented to the system already has reserved the attribute name.  this is further exacerbated by the inability to change the datatype of the attribute.

Structr uses an attribute called 'Id' on every entity to canonicaly identify that node in the graph.  Under general circumstances this is just fine, however I have discovered some problematic aspects of this in a scenario where an external system is required to post to a endpoint powered by a structr REST resource.  In this case me (the user) is not empowered to change the incoming data's attribute names prior to it being POSTed.

Here is a capture from the web log

````

POST /structr/rest/blahblahblah_webhook_events/ HTTP/1.1
Host: api.example.com
Content-Length: 161
Accept-Encoding: gzip,deflate
X-Forwarded-Proto: https
X-Forwarded-For: 255.255.255.255
User-Agent: Apache-HttpClient/4.3.3 (java 1.5)
Connection: keep-alive
X-Forwarded-Port: 443
Content-Type: application/json; charset=UTF-8

{
   "store_id":875498765432876543,
   "producer":"stores/1heewkhrp3osav",
   "scope":"store/order/created",
   "data":{
      "type":"order",
      "id":101
   },
   "hash":"40a50026b26a2e143281d793eadec40e6825b879"
}

HTTP/1.1 500 Internal Server Error
Date: Tue, 23 Jun 2015 04:59:46 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: JSESSIONID=1p2ukqbnk2dfo15vrnywwom09e;Path=/
Content-Type: application/json; charset=utf-8

{
  "code" : 500,
  "error" : "JsonSyntaxException in POST: java.lang.Long cannot be cast to java.lang.String"
}
````

The issue being highlighted here is that the JSON payload being provided is immutable.  It cannot be change so that it does not **conflict with Structr's use of the 'Id' Attribute in the data sub-object.**

One possible workaound is to use an 'onCreate' method to shuffle around the values and transform the input and regenerate a suitable UUID for the ID value, but this is untested at the moment.  

In the conversation of whether Strcutr should/can segregate the namespaces:

If no way to separate them is attainable, the Entity Editor dialogs should not allow the addition of an "override" attribute with a name that is the same as a critical system attribute and a different data type.  Right now it allows this option, but when the dialog is closed and subsequently reopened, it's apparent no data type change was made, and the form is inconsistent (with duplicate entries, now of type string)

**Comment by amorgner** [comment]
There's no simple answer to this.  The external data you describe also uses "type" and "id" in the global/user namespace, and the type of both fields differ.  This can and will happen sooner or later in real-world setups, so this is a real issue, thanks for reporting!

Changing (or prefixing) Structr's system attributes would help, but would also produce ugly attribute keys like `structr::id' or 'structr::type', and it would also mean that a large part of Structr's backend UI had to be reworked, and probably any custom Structr frontend/mobile app as well.  In addition, Neo4j probably will introduce attribute key namespaces in the future (at least their user base is asking for this feature since years).

So IMHO, the ideal solution would be a flexible mapping/masquerading, converting attributes at input/output, maybe bound to a certain schema view, or implementing something to enforce fixed system-wide conversion rules.

As Structr's de-/serialization is already nicely encapsulated in just a few classes/methods, it wouldn't be too hard hopefully.

**Comment by eric-schleicher** [comment]
i commonly encounter data that i would like to import into structr that has pre-existing 'id' attributes.  

Is there a staightforward way to remap inbound attribute to something else in the core model?

**Comment by cmorgner** [comment]
If the IDs are in the correct format (`string: [a-fA-F0-9]{32}`), you can use them directly in Structr. If not, I'd recommend to use an `originId` field, which requires a preprocessing step prior to import. There is no preferred / recommended way to do this with Structr, but we do write import scripts / transformators all the time.

**Comment by eric-schleicher** [comment]
@cmorgner this presumes that the recipient has the ability to modify.  the two cases i experiences were service calls coming in from other organizations, neither of which i could have change their interfaces/payload.  

If the ability to re-map  the value in-between post and commit, then i think this is achievable.

**Comment by amorgner** [comment]
@eric-schleicher Maybe you can set the id by using the ```set_privileged``` function in the ```onSave``` schema method (just a guess, didn't try it myself yet)?

**Comment by eric-schleicher** [comment]
I have another integration coming in the next month where I do not control the namespace of the inbound data, it resurfaces that challenge(s) presented by Structr locking up very common and generally highly identifying attribute names like *'id'* and *'name'*.

If there is a way to use set_privileged to re-map the attributes i think i'm going to need to do that.  

if in method code, i take the value of the presented 'id' (a external systems unique identifier) and copy it over to an 'external_id' (that i create on the entity), will i just need to generate a uuid for the this.id and use set_priveledged on that?

Something like ?
``` 
(
set(this, 'external_id', this.id),
set_priveleged(set(this), 'id', uuid())) 
)
```

Ideally I need to import this JSON data without preprocessing.  It would be ideal to present it to Structr as in @amorgner blog entry [create-graph-structures-from-deeply-nested-json-documents](https://structr.org/blog/create-graph-structures-from-deeply-nested-json-documents).

I'm not sure how to ensure structr will handle determining uniqueness as entites are presented when the source system uses their own 'id' as the unique identifier.

I would post this in the group, but I'm doing it here as i contend that Structr should not be forcing document data it handles to be pre-processed.  It should be able to handle the modifications inline, or not have the requirement (at all).  This would be a requirement for any doc-store functionality.

**Comment by amorgner** [comment]
@eric-schleicher Did you notice that there's a new concept in Structr called "Virtual Types"? The description (https://support.structr.com/article/233) is a bit thin yet but we're using this in client projects successfully.

**Comment by eric-schleicher** [comment]
@amorgner .  This sounds quite interesting, but agree that the KG article is too thin to properly conceptualize how to use it.  if there is a short way to explain with an example, perhaps i can help with learning it and writing documentation.

**Comment by cmorgner** [comment]
@eric-schleicher just fyi: we just updated the KG article on virtual types: https://support.structr.com/article/233

**Comment by amorgner** [comment]
@eric-schleicher Does the Virtual Types feature help you? Or do you have requirements which are still not met by this? If so, please let us know, maybe we can extend and improve the Virtual Types.

**Comment by eric-schleicher** [comment]
This looks *very* promising, but I haven't had a chance to circle back to this as i worked around it previously.  @cmorgner thanks for updating the KG article.  I will attempt to use this on the [Structrify](https://github.com/eric-schleicher/Structrify) model where this can be used to maps the IDs used in the input data to an extId value.

**Comment by cmorgner** [comment]
What's the status of this issue? I think virtual types can be very useful here, we successfully used the concept in some of our own projects.

Please review and comment or close, thank you!

**Comment by eric-schleicher** [comment]
I've come to accept that structr reserves prime attribute names for itself.  I see no problem in closing, if VirtualTypes are the chosen method to support the transformation/mapping of attributes coming through the REST layer.
