### ISSUE TITLE
SSL issue when trying to run mvn install -DskipTests

### ISSUE THREAD

**Issue by jrgleason** [structr/structr#372]
So my employer has a self signed certificate it uses to ease drop on employee conversations. This becomes a problem as most SSL communication gets rejected unless you configure the SSL to not be strict about certificates. It appears that is what I am running into here....

>Failed to execute goal on project structr-core: Could not resolve dependencies for project org.structr:structr-core:jar:1.1-SNAPSHOT: Failed to collect dependencies at org.neo4j:neo4j-spatial:jar:0.14-neo4j-2.2.3: Failed to read artifact descriptor for org.neo4j:neo4j-spatial:jar:0.14-neo4j-2.2.3: Could not transfer artifact org.neo4j:neo4j-spatial:pom:0.14-neo4j-2.2.3 from/to neo4j-contrib-releases (https://raw.github.com/neo4j-contrib/m2/master/releases): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

Any idea what I can do to get around this?

**Comment by amorgner** [comment]
Can you try the solution proposed here? http://stackoverflow.com/questions/21252800/maven-trusting-all-certs-unlimited-java-policy

**Comment by amorgner** [comment]
@jrgleason is this issue still open for you?

**Comment by amorgner** [comment]
Closing this issue as we try to focus on our 2.0 release, and I think this isn't directly related to Structr's code or functionality.

@jrgleason If this still hinders you from using Structr, please post your question in our group/forum over here: https://structr.org/forum
