### ISSUE TITLE
1.1.0 seems to be failing on windows

### ISSUE THREAD

**Issue by jrgleason** [structr/structr#373]
I have installed 1.1.0 and when I try to start it I get...

>java.lang.IllegalStateException: The Neo Server running is of unknown type. Valid types are Community, Advanced, and Enterprise.

Also it appears to not even start until I try to hit Neo

**Comment by cmorgner** [comment]
Can you please post the full server.log? How do you start Structr? What version of Java do you use?

The error message is know to not have any impact on Structr itself, so I suspect something else is wrong.

**Comment by jrgleason** [comment]
Do you want the whole log or just the stack trace? Running on windows per instruction set here...

https://docs.structr.org/installation-and-configuration-guide#Windows Manual Installation

Seems to work after I restarted but not until and I still get the error.

**Comment by cmorgner** [comment]
The whole log file would be better if that's possible.

**Comment by jrgleason** [comment]
https://gist.github.com/jrgleason/ad3e2010a4059a2dea01

**Comment by cmorgner** [comment]
There seems to be nothing wrong with the start of Structr itself, as you can see from the lines
```
Jul 13, 2015 1:59:32 PM org.structr.core.Services initialize
INFO: Initialization complete
```

Can you please try to access http://localhost:8082/structr?!

**Comment by jrgleason** [comment]
yeah after I restarted that isn't the issue I am trying to kill the error message

**Comment by amorgner** [comment]
Just ignore the error message. As it's a Runtime exception, it's not possible to catch it.
