### ISSUE TITLE
NPE when relating nodes in #crud

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#374]
I receive the following error when relating two (specific types of) entities in the data editor.
```
Jul 16, 2015 8:16:14 PM org.structr.core.property.FunctionProperty getProperty
WARNING: Exception while evaluating function property name.
java.lang.NullPointerException
```

these two are in a n:n (many/many relationship

Neither of the two entities being related have 'function attributes', but one does inherit from type:File

Note really sure what's going on.  This is in version: 1.1-SNAPSHOT build 634bb (201506230124)

**Comment by amorgner** [comment]
Could you please supply a bit more of stack trace? Something with line numbers wuld help to track down the root cause.

**Comment by eric-schleicher** [comment]
sorry, if it re-occurs i will make sure to capture the entire section.  this was on a previous build.

I'll close and re-open if it happens again.
