### ISSUE TITLE
Support for indexing custom properties via UI or API

### ISSUE THREAD

**Issue by ravensorb** [structr/structr#375]
It would be very helpful to be indicate which properties on custom entities should be indexed.  Without this right now searching on most custom properties does not work at all.

**Comment by cmorgner** [comment]
Can you give an example please? The custom properties on any entity are indexed by default, i.e. all dynamic properties are indexed and searching should be possible on any dynamic field.

**Comment by ravensorb** [comment]
Sure, there are several right now that do not work correctly.  For example, try to do a filtered search on Size, Height or Width on Image or Video.  All result in an error indicating that the properties are not indexed.

in addition to that, there may be times when there is no need to index a dynamic property as it will be used for display info only.  For example, say I have a "weather" entity that has a "description" property that is a string.  This is not something that really needs to be indexed -- it is more likely that high/low temp properties would be useful instead.  That said, someone else may have a different feeling and what a freetext search to be possible on the "description".  This would allow me to disable it and save on the performance and it would allow someone else to enable it and leverage it (accepting the performance impact).

**Comment by cmorgner** [comment]
Image and VideoFile are built-in entities, you can override them and modify the indexing behaviour if you use the latest snapshot.

**Comment by ravensorb** [comment]
I thought the same thing when I saw one of the commits.  However, I just grabbed 85 and this is what I am seeing

http://i.imgur.com/V5EF0ZK.png

Is it possible there is an "upgrade" process that didn't execute?

**Comment by cmorgner** [comment]
No, the inherited properties of a built-in entity are not modifyable in the schema editor. You have to create your own type and set the `extendsClass` field to org.structr.dynamic.Image. After that, you can create `size`, `width` and `height` properties etc.

**Comment by ravensorb** [comment]
I tried that too -- here is an image of a custom entity that extends the base Image

http://i.imgur.com/2MqHfPV.png

**Comment by cmorgner** [comment]
Yes, the next step would be to override the size, width and height fields...

**Comment by ravensorb** [comment]
Ok, what am I missing?  I don't see any place in the UI to indicate that they should be indexed.

**Comment by cmorgner** [comment]
Ah sorry, you need to use the latest Structr version from the master branch. I think there is not yet a snapshot of this.

**Comment by ravensorb** [comment]
Ahh, that explains it :smile:
