### ISSUE TITLE
Feature Request: Cleanup old Session IDs

### ISSUE THREAD

**Issue by ravensorb** [structr/structr#377]
I have noticed during testing that Session IDs related to a user simply accumulate and are never cleaned up.  It might be nice to store a little more information with each session id (created on, last updated on, and expires on) and then periodically clean up the expired ones.

Note:  Right now, I have a test user with over 300 session ids.  It is starting to make some of the REST calls take a long time to load :smile:

**Comment by amorgner** [comment]
Agreed.

Problem is that the session management is handled by the servlet container (Jetty) at the moment. In Structr, we're only storing the session ids as String[] attribute with the User entity so Structr can validate an incoming session id against the set of stored session ids based on existence only, not time.

We could store session information as Session objects/nodes. This would allow us to handle session expiry in Structr directly but would of course inflate the storage space per user. OTOH, persistent sessions (a Jetty feature, saving session info in the sessions/ directory) are enabled, so if you have lots of sessions there's a noticable lag on startup/shutdown to load/save all sessions.

Thoughts? @cmorgner @vigorouscoding

**Comment by eric-schleicher** [comment]
If the (expiry) date of the session was create was tracked when having a maintenance method/task would be quite straightforward to clean up

**Comment by amorgner** [comment]
Exactly, and the interesting question is where to store the session creation date. At the moment, Jetty stores it internally so we don't have access to this information at the application layer. We need to move the session info to the database, but I'm not sure about the implications in terms of size/performance.

**Comment by ravensorb** [comment]
What about creating a small custom driver for the Jetty Sessions that allows for storing them directly in neo4j (http://www.eclipse.org/jetty/documentation/current/session-clustering-jdbc.html)?

**Comment by amorgner** [comment]
Thanks for this hint! The sessions are already stored in Neo4j/Structr, so creating a custom driver for Jetty could be a solution.

**Comment by ravensorb** [comment]
I was thinking more about this recently.  Could this also be used to help support things like OAuth over REST apis?  If the "session" data became a entity with attributes (even if not exposed), then additional attributes could be added like "client IP", "last access", and even "auth token" and "auth token expiry". with this information it could be a lot easier to implement user based oauth via rest as well as application based oauth.

**Comment by vigorouscoding** [comment]
I just implemented a feature which removes old session IDs of a user upon authentication of said user. This currently happens on each request. I think this can be moved to the login method - I'll investigate further and report back here.

**Comment by ravensorb** [comment]
Hmm, wouldn't that cause an issue if the users are logging in to the web and via REST?  I currently have a mobile app that caches the session ID so that the user doesn't need to log in every time they launch the app.  That same user can also log in via the Web site to review their data.  If you wipe out all session ids except the current logged in one -- that would be a pretty big loss of functionality :smile:

**Comment by vigorouscoding** [comment]
That would be a problem, yes. "old" in my previous comment meant sessions which do not exist anymore (but the sessionId still hangs around on the user object) or which have reached a timeout after the user last used the session. So this should not be an issue I think.
(btw: we always like to see structr in action. is the app public?)

**Comment by vigorouscoding** [comment]
I just moved the code to the login method(s) so that it is not executed upon every request and also renamed the function to `clearInvalidSessions` to prevent confusion.

**Comment by ravensorb** [comment]
Cool, I'll give it a try and see if there is any impact.

As for the app -- its not public yet (however it is getting really close).  I still need to come up with a few more workarounds for some things in structr that are not fully ready for primetime :)

**Comment by amorgner** [comment]
Clean-up of old sessions works, closing this.
