### ISSUE TITLE
Parsererror in CRUD hides data

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#378]
I sporadically encounter situations where the crud editor will not show data for an entity despite my knowledge that there are records.

upon opening the browser console, I can see the following error

```
Unexpected end of input
    at Object.parse (native)
    at m.parseJSON (http://blahserver.com/structr/js/lib/jquery-1.11.1.min.js:4:15739)
    at Pc (http://blahserver.com/structr/js/lib/jquery-1.11.1.min.js:4:18120)
    at x (http://blahserver.com/structr/js/lib/jquery-1.11.1.min.js:4:21525)
    at XMLHttpRequest.b (http://blahserver.com/structr/js/lib/jquery-1.11.1.min.js:4:25897)
```
typically a full refresh of the page will resolve the issue, but many time i need to perform an explicit "empty cache and hard reload" to clear the issue up.

This is with chrome Version 44.0.2403.130 on Windows.
Structr VErsion: 1.1-SNAPSHOT build 0578b (201507301213)

**Comment by amorgner** [comment]
Just had the parsererror for the first time. It happens when the network connection is interrupted. It seems to go away after a while.

I think we can add a retry, and if it doesn't recover, Structr should show an error message, explaining what's happening, and of course retry in the background.

**Comment by amorgner** [comment]
The latest snapshot contains an automatic retry after 1 sec, this is the just the first measure we're taking. Could you please upgrade and see if this error still occurs?

**Comment by eric-schleicher** [comment]
Would like to very much, as soon as i can get a backup of my server i'll update.

**Comment by amorgner** [comment]
Any news here?

**Comment by eric-schleicher** [comment]
running 1.1-SNAPSHOT build e61cd (201508171231)  I haven't seen the the parse error message (frequently or possible at all)...  however there are still times where i still see missing links for relationships that i know to exist.when browsing the data editor.

I'm trying to correlate to any other observations.

**Comment by eric-schleicher** [comment]
Nevermind.  same build as above: 

![image](https://cloud.githubusercontent.com/assets/8261783/9826907/7dd986fa-5892-11e5-90f4-7bd825ed3719.png)

and some additional detail:

![image](https://cloud.githubusercontent.com/assets/8261783/9827080/b73c3928-5893-11e5-9058-2e2cc6bc70c8.png)

**Comment by eric-schleicher** [comment]
Some additional commentary on this. i've been able to preproduced a consistent fix for this scenario when it does occur.  

normally, once this occurs.  It's required to close all tabs (and windows under the profile) and then re-open structr to get the main menu navigation or the data display in crud to work again.

However:  In my instance, i have a standard login form. if I: 

1) Enter the url of that login page directly into the address bar, 
2) without logging out...  login in from that form 
3) then enter the backend url (/structr)

Everything (menu and crud display)  immediately works again.

Intuitively it seems like there is a problem with the session, since creating a new context seems to immediately rectify the issue.

**Comment by eric-schleicher** [comment]
I'm closing this because it's my understanding that the parse error is a soft error due to latency issues and the fact that the issue being observed here isn't actually related.  

It turns out that the number of shown entries for an attribute follow on a page level as discuss in issue #392

**Comment by amorgner** [comment]
Kai probably fixed the issue causing this: https://github.com/structr/structr/commit/33a007c40dcb007ea050c6b63f7dcd9ff76422dd
