### ISSUE TITLE
Feature Request:  Closable Tabs in CRUD Editor

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#379]
MY model has grown quite large, and it's become quite (space) ineffecient to show all of the entities all of the time in the crud editor.  I lose about 1/3-1/2 of the vertical real estate on my screen to > 6 rows of entity tabs.

It would be very nice to have type-in selector somewhere in this UI to "load" a given entity and then be able to close it if not needed.  this would great improve the usability and appearance.

**Comment by vigorouscoding** [comment]
This is something that was nagging me as well. I just pushed a commit (f4e886d77b94e4b71b0704e89a9ce261e568a6d2) which solves this.

We now a couple of controls in the CRUD and Types view:
- "Hide inactive tabs" button
    - simply does what it says. it hides the inactive tabs and saves that state. if you leave the crud/types and return it will be restored
- "Show all tabs" button
    - the inverse of the above
- "auto-hide inactive tabs" button
    - this activates the auto-hide mode. when a tab is selected the inactive tabs will be automatically hidden. To switch tabs you need to click the "Show all tabs" button.

**Comment by eric-schleicher** [comment]
Nice will try ASAP.
 
Thanks @vigorouscoding
