### ISSUE TITLE
geo query by lat/lon and not do a geocode query

### ISSUE THREAD

**Issue by grimace** [structr/structr#382]
if a user has a lat/lon, i.e. from a click on a map, and wants to do a geospatial query of structr Location objects around, withinDistance, within; this would be better then having to supply address,street,city, etc...

**Comment by amorgner** [comment]
@cmorgner We should include this in 2.0.

**Comment by amorgner** [comment]
@cmorgner Could you please check this issue against the latest development in the `structr-geo-transformation-module`?

**Comment by cmorgner** [comment]
This is implemented in commit 37f7f72, please test and close.

REST example with latitude/longitude:

    GET /MyLocation?latlon=3.33,5.55&distance=20

REST example with geocoding

    GET /MyLocation?street=Teststreet&city=München&county=Germanydistance=20

**Comment by vigorouscoding** [comment]
This has been working for quite some time now. It's documented under https://docs.structr.com/docs/rest-guide#distance-search
