### ISSUE TITLE
Corruption of Neo4j Store

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#384]
I've experiences two separate corruption events in my store.  this problem expresses itself when a (hot) backup cannot be brought back online.

The procedure being used follow roughly the following steps

With Structr Running, Perform a zip  of the entire /usr/lib/structr-ui folder

On the restore system, a sudo rm -R /usr/lib/structr-ui is performed to clear out the application folder.
that zip file is moved to this system 
the zip archive is extracted (-d option) where it is creates an populates /usr/lib/structr-ui folder.

then ```sudo service struct-ui is performed```

the log for structr after probiding ample time is as follows:
```
Aug 25, 2015 12:19:42 AM org.structr.core.Services initialize
INFO: Reading structr.conf..
Aug 25, 2015 12:19:43 AM org.structr.core.Services getResources
INFO: Found 0 possible resources: []
Aug 25, 2015 12:19:45 AM org.structr.module.JarConfigurationProvider scanResources
INFO: 3 JARs scanned
Aug 25, 2015 12:19:45 AM org.structr.core.Services initialize
INFO: Starting services
Aug 25, 2015 12:19:45 AM org.structr.core.graph.NodeService initialize
INFO: Initializing database (./db) ...

```

No additional log entries ever appear.

Inspection of the db/messages.log show that the store required a recovers (which is apparently not possible on community edition, due to no tools with this distribution?).

**Comment by cmorgner** [comment]
Might be related to https://github.com/neo4j/neo4j/issues/4957. Please update to Neo4j 2.2.4 as the bug should be fixed there.

**Comment by amorgner** [comment]
@eric-schleicher Please keep in mind that the way you create a "hot backup" is not officially supported by Neo4j. It might work with small databases while not being written to, and ideally very fast disks (SSD). If you create the ZIP and the database files are being changed while creating the ZIP, you will probably end up in an inconsistent state.

We strongly recommend using Neo4j Enterprise Edition which is fully supported by Structr.

**Comment by eric-schleicher** [comment]
positive news to hear that i can run enterprise, but to do so will i need to make my own build of structr-ui?

**Comment by amorgner** [comment]
You can build it yourself, but we also provide pre-built bundles to our commercial customers.

**Comment by eric-schleicher** [comment]
I'm in the process of joining the startup program with Neo. is some instruction on running with enterprise in any of the documentation?

**Comment by eric-schleicher** [comment]
@amorgner  in this case, i still have a running store (the system hasn't been shutdown). so i CAN shut down the service normally, backup the system in another fashion.  My concern (based on the previous event) is that if i shutdown the system, it will not start again.

looking for the best way to save the export/save the data prior to a shutdown (sweating a bit here).

**Comment by amorgner** [comment]
If you shutdown the system before copying the store files, Neo4j doesn't have to recover.

With the above mentioned bug fixed in Neo4j 2.2.4, the system will startup fine again.

**Comment by amorgner** [comment]
Btw, we are official Neo4j reseller and provide discounted bundles of Structr and Neo4j EE. :-)

**Comment by eric-schleicher** [comment]
:| 

I'm not sure if i'm articulating the current issue correctly.  Based on previous experience, when i stop the service, the store will be corrupt and will not be recoverable.

The situation described here does't help much since this store won't restart (if stopped) and is running 2.2.3

**Comment by eric-schleicher** [comment]
or is the statement that simply starting with 2.2.4 will enable neo4j to recover the store?  2.2.3 is not capable.

**Comment by cmorgner** [comment]
You can try to export the store using the "sync" maintenance command:

POST /maintenance/sync '{mode: export, file: store.zip }'



Am 25.08.2015 um 18:40 schrieb Eric Schleicher:
> :| 
>
> I'm not sure if i'm articulating the current issue correctly.  Based on previous experience, when i stop the service, the store will be corrupt and will not be recoverable.
>
> The situation described here does't help much since this store won't restart (if stopped) and is running 2.2.3
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/structr/structr/issues/384#issuecomment-134665706


-- 
Christian Morgner
CTO Structr (c/o Morgner UG) · Hanauer Landstr. 291a · 60314 Frankfurt · Germany
Phone:   +49 163 2536088
Twitter: @cmor_

http://structr.com

**Comment by amorgner** [comment]
> or is the statement that simply starting with 2.2.4 will enable neo4j to recover the store? 2.2.3 is not > capable.

Yes

**Comment by eric-schleicher** [comment]
Update: 2.2.4 (community)was not able to recover the store.

exact same messaging as before.  failure due to negative index value.

my next best path is to run @cmorgner recommendation.  If that looks successful then i'll attempt a restart.

**Comment by amorgner** [comment]
Did you try to recover a corrupt store (from a "hot backup") or a cleanly shutdown database?

**Comment by eric-schleicher** [comment]
This is the recovery recovery attempt from the two previous (hot) backups that were (distinct events, but) identically corrupted.  

I cannot shut it down until I've either safely exported critical data or performed an online backup.  I took a week to recompute the data loss last time.

**Comment by amorgner** [comment]
One thing you can try is to create a new hot backup, but make sure the instance is not used.

- Don't shutdown the database
- Make sure noone can access the instance (temporarily disable HTTP network connections on the server)
- Create a fresh copy of the database store files
- Try to recover the copy

This will increase the probability of creating a recoverable databasse copy.

**Comment by amorgner** [comment]
I assume the issue could be fixed by using the Structr export/import tool, so closing this issue here.

**Comment by eric-schleicher** [comment]
Not sure if should re-open this one, or open a new issue.  I've I've been able to run the mainentance/sync command successfully, however i've not been able to import this into a fresh instance of structr.

Please advise and will post the logs in the appropriate issue.
