### ISSUE TITLE
Link to Windows installation button on README.md is broken

### ISSUE THREAD

**Issue by msoule** [structr/structr#387]
The links to the windows installations instructions is broken. Here is the link:

https://github.com/structr/structr/blob/master/windows%20installation%20instructrions

I have found it here:

https://github.com/structr/structr/blob/8a124faf934ca57d6b3b7e69ad1af685f3b1a206/docs/markdown/installation-and-configuration-guide/00_installation/03_windows-manual-installation.md

**Comment by amorgner** [comment]
Thanks for reporting, you're absolutely right. I just fixed it.
