### ISSUE TITLE
Hanging comma in JSON Post to create node with relationsihps results in Additional Matching Node with no Relationsihps

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#389]
Not 100% sure this is a bug or a quirk:

I'm posting data via rest and am observing that when creating a node with two link to different objects i get suprising result.

(Backer)-[HAS]->(BackerReward)-[HAS]-(RewardConfig)

on BackerRewad there are two notion attributes:
- backer (which references hasBacker)
- configuration  (which reference hasRewardConfig)

the following is the JSON i'm posting 

```
[
  {"backer":{id:"0bca05ed08aa49119d6bf9392377d766"},"configuration":{id:"9e65752eca7b406bb8140d8f6b8a10e6"}},
]
```

This is the result
```
{
    "result_count": 2,
    "result": [
        "aae4922f82d64344ba9c64ba588f8a55",
        "cabc08792a87410fb4addf86526769d0"
    ],
    "serialization_time": "0.000008156"
}
```

I expected to get one result.
inspection of the two nodes create reveals that one of them has the relationships populated as expected/desired, the other does not.

![image](https://cloud.githubusercontent.com/assets/8261783/9563963/d7f693c8-4e4a-11e5-86e5-81f3608d9bc9.png)

alternatively i has tried posting with this JSON
```
  {"backer":"0bca05ed08aa49119d6bf9392377d766","configuration":"9e65752eca7b406bb8140d8f6b8a10e6"},
```

When entering this i notices the hanging comma.

when i removes it, i got  a single once entity which was expected.

so not sure if the second node creation is purely a result of the rest service being accommodating of non-strict JSON?

**Comment by amorgner** [comment]
Interesting. :-)

The JSON specs don't allow a trailing comma, so strictly speaking, this is not a bug, just wrong usage. But I can imagine what's happening inside Structr: As the comma separates objects, Structr thinks that there's another object after the trailing comma and creates an empty object of the given type, at least as long as the type doesn't have any mandatory fields which could prevent empty objects from being created.

**Comment by eric-schleicher** [comment]
closing because this is a quirk.  not important.
