### ISSUE TITLE
CRUD "gives up" displaying certain related nodes

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#392]
Trying to help nail down why the crud editor fails to show related nodes (fairly regularly)

I have a number of entities there i'm certain each node (row entry in # Crud) has an established relationship to another Entity.  When reviewing this data in  # Crud, regularly i will see what looks like the browser "gives up" on showing the related nodes of an entry.

Here is an example:
![image](https://cloud.githubusercontent.com/assets/8261783/9921423/6b99e5bc-5c92-11e5-9d99-c65984d4a028.png)

In this case it appear to 'give up' after an entry with multiple relationships

in considering the (following) "empty" row, clicking on the edit (pencil) icon for the row brings up the node editor dialog.  This dialog accurately reflects the related node(s) as expected. Please see following behavior:
![image](https://cloud.githubusercontent.com/assets/8261783/9921455/a618eb2a-5c92-11e5-96ab-ce40f048722b.png)

This example show a single related node (expected).  exploring the matter further I click the (+) icon to add *another* related node (known to have been created previously).  In the inbuilt search function pulls up the node to link, I click it and then close the node editor dialog.

The change immediately displayed (in the main # crud interface),and now (correctly) shows both relationships (the one it didn't show originally as well as the one i just added).
![image](https://cloud.githubusercontent.com/assets/8261783/9921502/0ce05dca-5c93-11e5-93d7-0e0567c096a8.png)

At first it appeared that perhaps if an entry (row) had many relationships, subsequent entries might not display correctly, but paging through an entity with dozens of pages (@ 10 per page)  I was able to identify other instances where the view "gave up" on showing the related nodes where the immediately preceding entry only had one related node.

![image](https://cloud.githubusercontent.com/assets/8261783/9921539/6bba47f2-5c93-11e5-9754-bc8ceac7d049.png)

The browser console does not report any errors.

I think this is very important functionality and having to inspect single nodes to ensure their display is actually correct degrades the user experience and makes using the interface error prone/difficult.

**Comment by cmorgner** [comment]
I think you're actually seeing a bug that has to do with the paging of related nodes in CRUD. Can you please try to increase the number of nodes displayed in the paging controls of the particular column and hit enter? Or click on the next page button.

Am 17. September 2015 02:00:22 MESZ, schrieb Eric Schleicher <notifications@github.com>:
>Trying to help nail down why the crud editor fails to show related
>nodes (fairly regularly)
>
>I have a number of entities there i'm certain each node (row entry in #
>Crud) has an established relationship to another Entity.  When
>reviewing this data in  # Crud, regularly i will see what looks like
>the browser "gives up" on showing the related nodes of an entry.
>
>Here is an example:
>![image](https://cloud.githubusercontent.com/assets/8261783/9921423/6b99e5bc-5c92-11e5-9d99-c65984d4a028.png)
>
>In this case it appear to 'give up' after an entry with multiple
>relationships
>
>in considing the (following) "empty" row, clicking on the edit (pencil)
>icon for the row brings up the node editor dialog.  This dialog
>accurately reflects the related node(s) as expected. Please see
>following behavior:
>![image](https://cloud.githubusercontent.com/assets/8261783/9921455/a618eb2a-5c92-11e5-96ab-ce40f048722b.png)
>
>This example show a single related node.  exploring the matter further
>I click the (+) icon to add *another* related node (known to have been
>created previously).  In the inbuilt search function pulls up the node
>to link, I click it and then close the node editor dialog.
>
>The change immediately displayed (in the main # crud interface),and now
>(correctly) shows both relationships (the one it didn't show originally
>as well as the one i just added).
>![image](https://cloud.githubusercontent.com/assets/8261783/9921502/0ce05dca-5c93-11e5-93d7-0e0567c096a8.png)
>
>
>At first it appeared that perhaps if an entry (row) had many
>relationships, subsequent entries might not display correctly, but
>paging through an entity with dozens of pages (@ 10 per page)  I was
>able to identify other instances where the view "gave up" on showing
>the related nodes where the immediately preceding entry only had one
>related node.
>
>![image](https://cloud.githubusercontent.com/assets/8261783/9921539/6bba47f2-5c93-11e5-9754-bc8ceac7d049.png)
>
>The browser console does not report any errors.
>
>I think this is very important functionality and having to inspect
>single nodes to ensure their display is actually correct degrades the
>user experience and makes using the interface error prone/difficult.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/structr/structr/issues/392

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by vigorouscoding** [comment]
My approach would be to set the number of displayed rows to 1. This way the paging for columns should work as expected/intended.

**Comment by eric-schleicher** [comment]
see following screenshot
![image](https://cloud.githubusercontent.com/assets/8261783/9936386/927956a8-5d10-11e5-89f0-7335ea1f0a83.png)

the 'rewards' attribute is a notion representing the same information as the hasBackerRewards column.

I also tried the following:
Number of records for the page (20)
Number of records for rewards column (18)
number of records for the hasBackerRewards column (10).

The counts ended up matching, with the hasBackerRewards showing fewer total related nodes implying that the textboxes on each remote attribute are page level, not entity level.  Just confirming that.

If that's the case, the page/row mismatch is confusing but explains a lot.

Is that a UI quirk, or intentional behaviour?

**Comment by eric-schleicher** [comment]
Should i close this one?  I at least understand the behavior.  seems more on the bug side vs quirky.

**Comment by amorgner** [comment]
No, please leave it open. This is a bug we'll fix until 2.0.

**Comment by amorgner** [comment]
We recently changed the CRUD behaviour and also fixed a nasty bug which caused the REST server to not return a JSON body under some weird conditions.

Can you try again with the latest snapshot version?

**Comment by eric-schleicher** [comment]
The original Issue is Resolved
