### ISSUE TITLE
Import of backup  file doesn't preserve labels from inherited types

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#393]
After importing a  backup  made with the /maintenance/sync command I've observed that the "ancestry" labels on entities aren't preserved through the import process.

Example:
In a Schema there is an entity called "Variable".  Generally nodes are not created of this type, but this entitiy has a number of relationsihps to other entitied in the schema.  In this pattern, there are a series of "child" entities that extend "Variable", specifically so that they can inherit the relationships.

These Child entitied represent sub classes of type "Variable". examples are "VariableString", "VariableColor", "VariableFont", "VariableVector" and so on.  

When creating data, the system creates node of the sub classes, not the super class.  so along those lines, there are no "Variable" nodes in the system just node created in the child classes.  This is a very powerful feature of Structr, and allows for a very elegant patter of managing relatinships inheritance.

In this example the import completes successfully and all of the nodes and their relatinships are appropriately represented in Structr-UI.  However when querying the data directly from Neo, it appears that the 'parent class labels are not applied to the restored system as evidenced in the following screenshots.

Here you can see that the nodes returned when querying the parent class retrieves the child classes (24 of type *VariableString* and 1 of type *VariableTextDraw*).  This indicates that the nodes have two sets of labels.  One from their instantiated variable subclass and one from the parent class allowing them to be retrieve by either
**From the originating source system**

![image](https://cloud.githubusercontent.com/assets/8261783/10025492/6c769420-6111-11e5-9748-fa476aff7c07.png)

However in the target (restored) system, the same query (retrieving by the parent class) returns no results.  
  
![image](https://cloud.githubusercontent.com/assets/8261783/10025605/f2d1cb48-6111-11e5-9483-db824bfbf826.png)

They are retrievable by querying them directly by their child class *only*

![image](https://cloud.githubusercontent.com/assets/8261783/10025750/aacf0094-6112-11e5-976c-03a60a0367fe.png)

It was brought up that the /maintenance/createLabels REST command could be used to rebuild the labels from the schema definition.  A test of that did not produce a change in the query behavior.

Looking here to establish an effective workaroudn to re-apply the labels, or more optimally ensure that the restore process maintain the labels when using the export/import command(s).

This was done on a clean/fresh instance running snapshot 1.1-87 of the debian build.

**Comment by eric-schleicher** [comment]
Bump on this one, since the maintenance/sync backup functionality is in effect broken since:  restored data != to backed up data. 

IMHO a confidence shaking data consistency bug.

**Comment by amorgner** [comment]
As a workaround, just rebuild the index after import and all labels will be automatically added and the inheritence structure will be clean again, see #405.

We'll fix it in the sync tool as well.

**Comment by amorgner** [comment]
The above comment is partly wrong: By rebuilding the index you can only make the primary label appear again but not the inherited labels.

You need to issue the `createLabels` command for the particular type(s) to add all labels after the import:

`post maintenance/createLabels '{"type": "VariableString"}'`

@eric-schleicher Could you please re-test and report back? Thanks.

**Comment by amorgner** [comment]
Should be fixed by https://github.com/structr/structr/commit/e8b793028e5bb86eedf75d5807e7cb415123ded4.

**Comment by amorgner** [comment]
New snapshot is deployed.
