### ISSUE TITLE
Node edit dialogs take inordinate amount of time to open when node has high number of relationships

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#395]
\* and that relationship has long string attribute(s).

Background
(a:ProductConfiguration)<-[APPLIES_TO]-(b:ConfigurationSnapshots)

Entity 'b' has a string field called configurationPayload which is a text document (SVG).  this attribute is included in the /_Default view (and of course the _Ui View).

Within the store I have about 50 (a:ProductConfiguration).  Most of them have just a handful of relationships, but a particularly popular one has throusands of (b:ConfigurationSnapshots).

Opening the (a:ProductConfiguration) with many related (b:ConfigurationSnapshots) appears to result   UI is transferring an incredible amount of data before successfully opening the dialog.

From the design of the dialog, the related nodes attributes have limiters, but it would appear that much data is being processed (clearly far more than the specified (default:10) limit in the dialog.

Unfortunately it's not a short term option to migrate the long string fields to a file object. but i'm wondering what is causing this behavior.  initially i though that perhaps the node edit dialog was requesting an expensive sort of the related nodes and that it just took a long time to render the data (with the results constrained to some sorted but limited list of related nodes)...  so I uses a network traffic monitor to watch the behavior when opening the dialog on this one (a:ProductConfiguration) and observed that total amount to data being transferred strongly implies that all of the data is being send over to the client prior to being culled to the user definable limit.

I don't believe that i can remove the "offending" attribute from  _Ui view...  or can I.  I could conceivably handle the display of this attribute in a specifically named view that would include it where needed, but most of the (ui) really doesn't need to be able to see this.

looking for what options i have in the short term (hacks included), and to provide some insight on the drag structr-ui can present to users when doing unnecessary work under the covers.

**Comment by eric-schleicher** [comment]
Bump.   This is definately a bug.

in Crud, opening a node with a high number of relationship (and target node having a large text attribute) results in the all of the data (in this case 100s of MB) being transferred to the client before opening the dialog.

Pic for attention
![image](https://cloud.githubusercontent.com/assets/8261783/10344327/6ab2bb60-6cd7-11e5-9c8e-56d1ef014306.png)

**Comment by amorgner** [comment]
We recently changed the CRUD behaviour. Would be interesting if you see progress here with one of most recent snapshots.

**Comment by eric-schleicher** [comment]
I'll try to check on this in the next week and report back.

**Comment by eric-schleicher** [comment]
I have not see the same issue for some time.  i have however also redesigned portion of the system to not store such large text blobs.

Don't think this is an issue any more
