### ISSUE TITLE
Include Resource Grants in schema snapshot

### ISSUE THREAD

**Issue by ravensorb** [structr/structr#397]
In order to help making it easier to backup/store schemas -- it would be great if the basic resource grants (even if they were set to no access) could be included in the schema snapshots.  This would save a rather large amount of time in terms of setting up access to the custom views that are part of each entity.

**Comment by eric-schleicher** [comment]
Agreed. 

I've been performing backup/imports for the most part to make sure that i can get a system spun up quickly, but the resource access isn't part of any code control that i have.  it's a bit awkward.

Integrating ResourceAccess into the schema snapshot (or along side it) would allow for both to be managed in step with eachother.

@ravensorb  how do generally go about restoring the schema snapshot?

**Comment by ravensorb** [comment]
Another option might be to auto-create a Resource Grant for any view that is created -- they would mean all we need to do is set it up correctly rather that re-creating them all.

**Comment by ravensorb** [comment]
@eric-schleicher right now the only thing I have come up with for a restore is reset the database, import the schema, and then script the rest which is very difficult and time consuming to maintain right now.

**Comment by eric-schleicher** [comment]
If you use the maintenance rest command to backup the resource access
entries come along for the ride.

When I change the values.  I test by changing in the ui, and then add that
to. A curl script.  This script gies in my git repo along with the schema
snapshot json.

I have yet to import the schema from the json without error however.
Leaving me reliant on backup imoort delete to setup a fresh environment

Eric

**Comment by ravensorb** [comment]
that makes sense -- however don't you then need to remove the data if you want to be able to build a fresh environment?

**Comment by eric-schleicher** [comment]
Yes, I then run a post delete with no id to nuke each entity.

**Comment by ravensorb** [comment]
That works -- although I am still puzzled as to why this is not included in the the snashot?

**Comment by amorgner** [comment]
@ravensorb Could you please try again with the latest snapshot? Thanks.

**Comment by ravensorb** [comment]
@amorgner I will give it a try this weekend.  Thanks!

**Comment by ravensorb** [comment]
Was this ever implemented?  I just updated to 2.1.0-SNAPSHOT build 1a149 (201611121209) and  do not see any sort of resource grants in the snapshot at all

**Comment by vigorouscoding** [comment]
The resource grants are auto-created (and -removed) so the basic version of the requirement works.

The more advanced version would be using the deployment command. In the admin shell (Press Ctrl-Alt-C and cycles modes until you are in the AdminShell mode) you can export the whole application including schema, resource access grants, pages, files, etc.
Depending on the size of the application this might take some time and require quite a bit of disk space.
Using the same Admin Console a stored export can be re-imported.
