### ISSUE TITLE
Audit log?

### ISSUE THREAD

**Issue by Joshfindit** [structr/structr#402]
Does Structr support an audit log of changes that users make?
If so, how do admins access it?

**Comment by amorgner** [comment]
Not automatically. There's a REST endpoint (``/structr/rest/log``) for logging events which creates log nodes in Neo4j, but using this for any change users make would quickly lead to an immense database size.

You could also log to a file by using the built-in ``append`` function, see https://docs.structr.org/#IO Functions.

**Comment by vigorouscoding** [comment]
As this issue roughly coincides with the time we introduced a feature (back then called) "auditLog" which is now called "changeLog".

It can be turned on via the structr.conf switch `application.changelog.enabled`.

A structr instance started with that switch set to `true` will record any changes made to objects and stores them in a property `structrChangeLog`. Currently the change objects are stored as one JavaScript object per line.

For implementation details please refer to `GraphObjectModificationState.java`
**Note though**: This feature is undocumented as of now and may be subject to change.

**Comment by amorgner** [comment]
Please use our mailing list/group (https://structr.org/forum) for questions like this. Closing this, 
assuming Kai gave a satisfying answer.
