### ISSUE TITLE
Upload Endpoint returns 500 when multiple concurrent uploads (but works)

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#410]
...but still works.

Screenshot showing the HTTP 500s.  in this case they're being handed back to a javascript upload component, but never the less Structr is returning a 500.

![image](https://cloud.githubusercontent.com/assets/8261783/11048981/db03082a-86ef-11e5-8191-d5c7c5523bc2.png)

here is the content of the message, which happens to leak that this is related to  Neo deadlocking 

**Note**:  *The user logged in is an administrator, since the type of asset being uploaded has to be overridden to a different (sub)class of type image.*

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /structr/upload. Reason:
<pre>    org.neo4j.kernel.DeadlockDetectedException: ForsetiClient[9] can't acquire ExclusiveLock{owner=ForsetiClient[4]} on NODE(546), because holders of that lock are waiting for ForsetiClient[9].
 Wait list:ExclusiveLock[
Client[4] waits for [4,9]]</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
 was created

```

**Comment by amorgner** [comment]
The exception comes from Neo4j's deadlock detection. In Structr we can detect those and try again, but apparently there's a place in the code where it doesn't happen.

Can you reproduce the behaviour reliably? Then we could setup a test and fix it.

**Comment by eric-schleicher** [comment]
Yes, using the drop zone upload widget without queuing  reliably causes
this.

I can point you to where to reproduce

**Comment by amorgner** [comment]
I couln't reproduce it at all with latest dropzone version and the following settings:

      $('#upload-area').dropzone({
          url: '/structr/upload',
          uploadMultiple: true,
          parallelUploads: 8,
          complete: function() {
            if (this.getUploadingFiles().length === 0 && this.getQueuedFiles().length === 0) {
              location.reload();
            }
          }
        });

**Comment by eric-schleicher** [comment]
Hm. 

This error occurs, but the functionality works... So i'm not sure if the uploader is automatically trying again.   this isn't impacting, but when i have a chance i'll check to see if there isn't another problem that i can resolve on my end to clear up the error.  closing.  pending re-evaluation
