### ISSUE TITLE
feature request: Ability to download Snapshot JSON from admin UI

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#412]
It's nice that the Schema Snapshots dialog lets you save the snapshot.json.  It would be a nice improvement to be able to download the JSON file from the same dialog once it's been created.  

I managed a version of this file in my git repo and it's a few extra steps than are needed to SFTP the file off the system.

clearly a low priority, but also trivial to implement.

**Comment by ravensorb** [comment]
+1 for this request.  It would also be nice to simplify an upload process for a snapshot.  Right now the process of posting it as a file, getting the id, then "knowing" the relative path and using that is a bit complex for a simple process.

**Comment by amorgner** [comment]
This is implemented in the latest snapshot of today.
