### ISSUE TITLE
Removal of old ResourceAccess Signatures from Security UI Breaks CRUD

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#414]
After removing a number of old (unused) resource access entries through the security tab, the Crud editor stopped working ("types" as well FWIW).

Opening the inspector panel revealed the following error that would occur everytime I clicked an entity in CRUD

![image](https://cloud.githubusercontent.com/assets/8261783/11701816/b1315c1e-9e86-11e5-8c47-5c468d8fa2ee.png)

I tried a variety of approached to resolve the issue including:
- Refresh page (F5)
- Hard Reload
- Empty Cache and Hard Reload
- Logging out and back in.
- Closing all browser windows in the affected profile
- Clearing the Sessions on the server

I was finally able to resolve the issue by deleting the local storage data for that particular server.  this would imply that the UI is dependent on local storage and gets out of sync somehow when resource access entries are deleted through the UI.

I tested with another entry and the exact same thing happened and i was able to correct the issue by immediately purging the local storage and logging back in.

**Comment by amorgner** [comment]
Could you please provide the exact version number of your build? Thanks!

Structr's backend UI uses ``localStorage`` for a lot of things. We'll remove the usage over the next versions to get rid of such problems.

**Comment by eric-schleicher** [comment]
2.0-SNAPSHOT build fffb8 (201511172335)

**Comment by amorgner** [comment]
The usage of the browser's `localStorage` was entirely removed. Could you please try to reproduce this error with the latest snapshot?

Please note that resource access objects will be automatically removed upon renaming or deleting custom classes.

**Comment by eric-schleicher** [comment]
Can't reproduce.  presumed squashed/fixed.
