### ISSUE TITLE
Feature Request: Schema Improvements

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#415]
just for consideration

I have many (130+ and growing) entities in my schema, keeping the domain model organized and meaningful to view can be a challenge.  

Possible improvements that would make this easier:

Colored entities:
- Enable the user to set a color for an entity to differentiate it from others.  This add another dimension of readability to the graph and make the postition of the nodes less critical
- Enable the user create named "perspectives" or views of the domain model.  This basic functionality is present in the "Display Options" dialog, but there is just a single global setting.  allowing multipled would allow for schema to have TABS for sub-domains.  a user could create view with just specific subsets of entities.

**Comment by ravensorb** [comment]
This would be a great addition

**Comment by eric-schleicher** [comment]
FWIW, I just postet in the google group about this.  in the interim, I'm going to create an external utility to manipulate whatever data is require to  create and "switch" views in schema.   

The thought here would be to design the Graph Structures for `UserSchemaView` (or similar name) and related them to the existing entities.  that way i can create an external utility for my own purpose with now, but then there will be some workable metadata structr for the UI to support this type of functionality in the future.

@ravensorb I'll post back with whatever i come up with if you're interested

**Comment by ravensorb** [comment]
Sounds great!  Thanks

**Comment by amorgner** [comment]
@vigorouscoding has just added an option to store and apply schema layouts. It's not yet merged into master. There might be some more improvements to the schema editor to follow.

**Comment by vigorouscoding** [comment]
I'll close this as this is pretty old and there is functionality for this.
