### ISSUE TITLE
failure to delete  owner attribute from entity results in crash? (HEAP)

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#416]
Version: 2.0-SNAPSHOT build fffb8 (201511172335)
Please watch video (a least first few minutes)

This has happened a number of times and have correlated the two events. the failure to update the relationship and the heap error/crash.

Not sure what to call it.  

A (seemingly) random record refused to allow it's relationsihps to be edited.  for such records, editing the entity basic attributes of the entity work correctly but no relationship attribute can be modified.

**reproducing the error:**
It appears somewhat random whether an record is impacted and occurs on an excpetional basis but not entirely infrequently (perhaps 2 twice a week).  I don't have any anecdotal observations on whether there is anything specific about the relationships that the particular record is participating in that might be related to or driving the issue.  The ProductConfiguration does not have have any recursive relationships, though does use Notions attributes.

An attempt to delete a relationship from an affected record appears non responsive in the UI.  This is followed by degradation in performance and then a few minutes later by heap space error (as seen in image below)

[![http://img.youtube.com/vi/Ep2myFPhWHo/0.jpg](http://img.youtube.com/vi/Ep2myFPhWHo/0.jpg)](https://www.youtube.com/watch?v=Ep2myFPhWHo)

The task I'm performing in this video is removing 'admin' as the owner of these entries and setting an different user.  This is a representative sample task, just to reproduce the issue that I've experienced deleting other relationships previously (both through REST as well as through UI).

**about 25-30 second in* I attempt the remove the owner relationship (after previous success of same operation on other entries.)

Nothing happens. 

Then performance starts to degrade, and subsequent page refreshes start taking significantly longer followed by (unfortunately not caught in the video) of the heap error but screen captured below.

At one point it was observes that the browser windows was consuming ~1GB of memory.  A hard refresh and clear cache seemed to improve performance.

I let the system sit idle for a few minutes and was subsequently presented with the following error:

![image](https://cloud.githubusercontent.com/assets/8261783/11757667/3d1b8776-a018-11e5-8aac-28f2f6a1f8b0.png)

**Comment by amorgner** [comment]
The heap space exception is thrown if the JVM process runs out of allocatable memory. There should be a more detailed error message in the ``server.log``.

How much heap space is configured for your Structr instance on the server (it's the ``-Xmx`` parameter)?

**Comment by amorgner** [comment]
ping @eric-schleicher

**Comment by eric-schleicher** [comment]
@amorgner I checked and post install of 2.x it was xmx1g and xms1g.  I've changed the settings but would like to research this more.  waiting to see if i get anymore of these nodes that i can't modify.

I've had it happen on a system with xmx6g previously.

**Comment by amorgner** [comment]
Assuming the machine's physical memory is 8+ GB, a maximum heap size of 6 GB (``-Xmx6g``) should be sufficient. Please check again with at least 4 GB of JVM heap space, and if the error occurs again, we need the relevant part of the ``server.log`` file to investigate.

**Comment by eric-schleicher** [comment]
I have not had a repeat of this issue in recent month or so. the behavior in CRUD seems to be improved in general in recent builds.   @amorgner, Can leave this open or close it??

I don't typically run 8+ GB on my structr Instances.  FWIW i typically run in a VM with 4 GB total and ```xmx3g```

**Comment by amorgner** [comment]
I think we can close this because the main cause of the observed error can be explained by a too small heap area.
