### ISSUE TITLE
neo4j-shell client not installed when Build and run Structr from the source code.

### ISSUE THREAD

**Issue by pmualaba** [structr/structr#417]
The neo4j-shell client is not installed when Build and run Structr from the source code (mvn validate exec:exec or ./start or ./run.sh) I have to manually install a second instance of neo4j (sudo apt-get install neo4j=2.2.7) in order to have a neo4j-shell client available. Could you please adapt the pom.xml to activate neo4j-shell client in the build? Thanks!

**Comment by amorgner** [comment]
@pmualaba Is your request still valid?
