### ISSUE TITLE
Feature request: ability to "reset" name of remoteAttribute based on Current Cardinatlity.

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#418]
As I understand right now, once a user explicitly sets a remote attribute name, structr will not automatically rename it (to a matching plural tense) when the user subsequently alters the cardinality of the relationship.  

That makes sense, but it's fairly easy to set the focus in one of these boxes and have it interpreted as a "change" (green flash) when no actual change was made or intended.

It would be nice to have a "reset" or sync button to bring the remote attribute name into conformance with the cardinality of the relationship.

in the meatime, is there a way to spot check these values?  It looks like the SchemaRelationshipNode Entity is where this is stored, but in my implementation it's sort of random whether there is a source/target JSON name specified.  

If these values were to be deleted, would the system automatically revert to the default naming convention?

**Comment by vigorouscoding** [comment]
I just added a "reset name to default" button. The same functionality is now triggered when the field is emptied completely.
Under the hood the attribute is just set to zero and so the backend decides what the default name of the property should be (taking into account the cardinality).

**Comment by vigorouscoding** [comment]
I'll close this as the functionality is implemented - feel free to reopen if there is another problem
