### ISSUE TITLE
How can enable payment option like as paypal in Structr?

### ISSUE THREAD

**Issue by Arpit25** [structr/structr#420]
I am new in Structr and I want to implement Paypal in Structr. Is there any option to enable payment option in Structr? Please suggest me.How can I integrate Paypal in Structr?

**Comment by amorgner** [comment]
There's no standard option for PayPal or other payment system integration with Structr.

You need to write your own integration interface, and for PayPal you can use one of the PayPal SDKs (https://developer.paypal.com/docs/classic/lifecycle/sdks/). If you're familiar with Java, https://github.com/paypal/PayPal-Java-SDK is a good starting point.

Please note that questions like this should go to the mailing list/group (https://structr.org/forum) as GitHub is more for bug reporting and code/coding-related discussions.
