### ISSUE TITLE
Bug or Quirk: Service returns status 200 when json is itself quoted

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#422]
Scenario:
Meant to Post to structr/rest/maintentance/setNodeProperties
```{"type":"ProductConfiguration", "currentsStatus":true}```

actually posted 
```'{"type":"ProductConfiguration", "currentsStatus":true}'```

Server Responded with 200, even through technically the body is malformed (422), but the JSON is valid.

I initialy thought that it had performed the work because of the 200, but noticed quickly that is is didn't.

is there a "No work done" http code?

**Comment by amorgner** [comment]
What client did you use? And is it just a typo here that you wrote ``currentsStatus``?

There's no such error code. 200 just means "I could serve your request without errors".

**Comment by cmorgner** [comment]
The change in question looks like a valid modification and it neither a bug nor a quirk:

https://github.com/structr/structr/commit/3d404a23515c44b954f66e392586a87c168d5c73#diff-d438833155a065fe855b044cbc8958a2R721

@amorgner maybe we should make the resource handlers more strict in terms of what they accept (and not silently ignore invalid input)?!

**Comment by amorgner** [comment]
I doubt that the JSON accepted by the server was invalid. We can't say anything without confirmation about what exactly was POSTed and how (which client, exact HTTP request).

**Comment by amorgner** [comment]
Ok, after discussion with @cmorgner I understand that @eric-schleicher POSTed a JSON body starting with a quote which is indeed invalid JSON which wasn't clear to me initially.

JSON has to start with either ``{`` or ``[`` and correspondingly end with ``}`` or ``]``. We'll improve the error handling in Structr so that a 422 or 400 error is returned.

**Comment by eric-schleicher** [comment]
OK that makes sense.

The meta content of the payload was valid jason , but as you highlight here
it the single quotes  make it invalid.

Thanks!

**Comment by amorgner** [comment]
Should be fixed now, new snapshot about to be deployed.

JSON body beginning with quotes gives a 400 error now (invalid syntax):

```
curl -HX-User:admin -HX-Password:admin localhost:8082/structr/rest/SampleApplication -XPOST -d '"{"title":"foo"}"'
{
  "code": 400,
  "message": "Invalid JSON, expecting object or array"
}
```

Invalid semantics give a 422 error:

```
curl -HX-User:admin -HX-Password:admin localhost:8082/structr/rest/SampleApplication -XPOST -d '{"title":"foo"}'
{
  "code": 422,
  "message": "SampleApplication.description must_not_be_empty",
  "errors": [
    {
      "type": "SampleApplication",
      "property": "description",
      "token": "must_not_be_empty",
      "detail": null
    }
  ]
}
```

**Comment by amorgner** [comment]
Closing as fixed.
