### ISSUE TITLE
unchecking atribute in Configure Colums Behaves unexpectedly, incorrectly

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#423]
not sure if someone else can reproduce this.

in the Data ui, On the tab for an entity click the configure columns button in the action column.

find the column i wish to remove from the view (because it has very long text).  immediately the view behind the dialog does what it is supposed to, removing the fields from view...

however when you click the close button to close the modal dialog, the grid seemd to refresh and bring the hidden column back.

running 2.0 snapshot 8

**Comment by eric-schleicher** [comment]
this is intermittent.  a full refresh of the page, the column that's been hidden is correctly hidden.  so it looks like this is transient glitching.

**Comment by amorgner** [comment]
This can be a temporary issue in the transition from browser's localStorage to server-only storage of UI configuration. I saw this issue as well, and we've taken some measures to fix it.

I can't reproduce this problem with the latest build, so can you please try again with 2.0-SNAPSHOT no. 10 (build 4db74)?

**Comment by eric-schleicher** [comment]
this hasn't recurred in recent builds
