### ISSUE TITLE
browser console peppered with errors (pageSize=null)

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#426]
Looks like pageSize isn't defaulting correctly?  this in case were i don't think i've explicitly set a page size in the data editor.
![image](https://cloud.githubusercontent.com/assets/8261783/12800837/d2e43b7e-ca8c-11e5-864c-2692c57874eb.png)

has been occuring (kind of randomly) in a numer of builds..  this one is:
2.0-SNAPSHOT build 57e9f (201601062321)

**Comment by vigorouscoding** [comment]
I just pushed a fix for a problem I found.

This may already fix the problem but in case you still see errors like this, please do the following:

1. Start the debug mode by entering the following in the Browsers JavaScript console (a lot of messages will fly by)
    ```
    _Logger.initLogger("console");
    ```

2. Click the offending data type tab in Structrs "Data" section

3. Take a screenshot of the error messages. I'd be particularly interested in the object after the "Property: " and "Error: " messages. Please expand these like in the screenshot I've attached.

![screen shot 2016-02-04 at 09 29 49](https://cloud.githubusercontent.com/assets/3099108/12809772/0ab03112-cb22-11e5-9235-6be09a4ad368.png)



I hope this helps!

**Comment by eric-schleicher** [comment]
I have not seen this in recent builds...  closing
