### ISSUE TITLE
giving a relationship a relationship_type aka name in "Edit schema relationship" dialog

### ISSUE THREAD

**Issue by cons0l3** [structr/structr#433]
Dear structr-alists,

I am currently running "structr-ui-2.0-SNAPSHOT-201602241737.08822". The [data binding tutorial](https://docs.structr.org/tutorials/Data%20Binding%20and%20Editing%20Tutorial) shows the schema of a "Project" being connected to a "ProjectMember". I add the nodes Project and ProjectMember. I add the relationship between the two. If I edit the relationship via the "pencil" button, I have a popup window with the relationship details. If I click the "UNDEFINED_RELATIONSHIP_TYPE" I can write a relationship type e.g. "MEMBER". I can modify all other attributes. There is no save button, so I close the dialog. The relationship type aka name is not set to the relationship.

Workaround - took me a while to figure that one out - is to click left of the "pencil" of the relation in the schema view. then you can give the relationship its type and it is being saved.

Cheers
Carsten

**Comment by vigorouscoding** [comment]
Thank you for bringing this bug to our attention! I just fixed this problem in commit a6013490b3589539db64baddb471dbdcbd34939b. The next snapshot will contain this fix and we will be able to close this issue :)

**Comment by amorgner** [comment]
Snapshot is deployed, closing this issue.

**Comment by cons0l3** [comment]
test on #5403e4 successful. bug is fixed. hopefully i do not reopen the issue, since it is already closed.

**Comment by amorgner** [comment]
Thanks for the retest! You can always comment without reopening. Please feel free to reopen any time a fix doesn't work for you.
