### ISSUE TITLE
BUG: Cannot set type when creating related entity involved in inheritance

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#437]
I posted this in the group and in slack an haven't heard *anything*

In our system:

![image](https://cloud.githubusercontent.com/assets/8261783/14058042/f56f9f60-f2cf-11e5-9883-a14795086363.png)

ClipArtFile has a relationship to Shape ([HAS]).  Shape is an abstract class, I do not create instance nodes for this entity type.  There are two Concrete entities types in the system that inherit shape;  ShapePath and ShapeRect (others will follow).  These two sub types have (completely) different attributes, but both participate in the relationship defined for the (abstract) parent by extending Shape Entity.

I also have `Automatic Creation of Related Nodes` set to `Source to Target` on the relationship between ClipArtFile and Shape: 
![image](https://cloud.githubusercontent.com/assets/8261783/14058019/31df2d36-f2cf-11e5-94b1-ff00eb0d3704.png)

When I create a ClipArtFile node with the appropriate related node information in the JSON body (to create the related ShapePath nodes within a single transaction), the explicitly provided type attribute in the POST ( `hasShapes: [{"d":"blahblah", "type": "ShapePath"}]` ). the explicit declaration of the type is ignored and nodes of type: Shape are created instead.   In this critical case, as it seems this would be impossible to create the correct data through any other means (in a single operation with related entities that are extending other classes).  

The payload of the related entity look to be validating correctly under the covers, as posting with attributes that don't exist in either child (concrete) class produces an expected error.  

This results in a situation where data is created in the wrong class (the abstract) which results in non-shared attributes being hidden throughout the system.

I performed a `PUT` as an administrator to change the type and the data appeared as expected, but this is not a solution as it cannot be achieved within boundaries of the create transaction.

Please Advise

**Comment by vigorouscoding** [comment]
Actually this is not a bug - Structr has no concept of abstract classes or interfaces. But it is a very legitimate and reasonable way to make Structr more useful. Maybe it is even possible to enable that specific functionality in Structr without actually supporting abstract classes.
Interfaces are one the roadmap but right now the application programmer has to manage this him-/herself.

In your case that would mean adding a custom method to the `Shape` type which conditionally sets the type of the created objects. That way it should take place in the create transaction.

If you have only these two shapes this would look something like this - otherwise you'd have to have a nested if-else-construct.

	(
		if(
			( <condition for ShapePath> ),
			(
				unlock_system_properties_once(),
				set(this, 'type', 'ShapePath')
			),
			(
				unlock_system_properties_once(),
				set(this, 'type', 'ShapeRect')
			)
		)
	)

HTH

**Comment by cmorgner** [comment]
This is in fact a bug introduced by commit 3081e64068a488cd38b541e55c0812f296ae5719. The commit changed the way Structr handles *interface types*, i.e. if a user tries to create nodes with a type that is not a *class* in Java.

I'm currently looking into this and will - hopefully - come back to you with a solution.

**Comment by eric-schleicher** [comment]
@vigorouscoding my use of abstract and concrete are in a strictly logical modeling context.  I don't think that structr needs to have a explicit concept between them.  sure it would be nice, but even in my model i doubt i require it.  I would rather be able to color the nodes in the schema diagram.  FWIW I also have a number of examples in my domain model where the parent Entity isn't abstract so i don't this this would be often used

I see the steps there, but that seems like (redundant) extra work when the criteria literally would be `type="ShapePath"` to the set(this, 'type', ShapePath).

It makes sense to me that non-admin account shouldn't be able to arbitrarily assign a type on the primary entity being created, but i think that being able to explicitly set the related entity type allows for for validating 1 ) the attributes on the exact class and 2) non-shared relationships within the single commit

I'm rooting for this to be a bug as it would seem so straightforward to allow it.  

Thanks @cmorgner

**Comment by amorgner** [comment]
New snapshot is deployed containing this fix cf1ce55.

**Comment by eric-schleicher** [comment]
Awesome thanks!

**Comment by cmorgner** [comment]
What is the status of this? Did the fix work for you?

**Comment by eric-schleicher** [comment]
Will be testing this weekend, will advise.  Just got # 33 running

**Comment by eric-schleicher** [comment]
Confirmed fixed: 

Able to post to the parent related resource of ClipArtFile:

```json
{
  "name":"test-file-002.svg",
  "imageData":"PHN2Zz48L3N2Zz4=",
  "hasShapes":[
    {"type":"ShapePath", "d":"M25"}
  ]
}
```
Which explicitly set the type of the related item.

But I have a follow on question about validation.  I can be careful about how this functionality is used, but i think that it could more precise in how the validation work with an explicit type proviced for a related entity.  Should validation occur against the type that's provided?  
**Take for example:**
```json
{
  "name":"test-file-002.svg",
  "imageData":"PHN2Zz48L3N2Zz4=",
  "hasShapes":[
    {"type":"ShapeRect", "d":"M25"}
  ]
}
```
In the example schema, ShapePath has a `d` attribute but ShapeRect does not (it has x,y,rx,ry, height, width)

Currently this post succeeds, but result in 'hidden data'.  I think there is some argument that perhaps it shouldn't succeed since it's invalid against both the super and other sub entity subclass.

Further testing revealed that posting 
```json
{
  "name":"test-file-002.svg",
  "imageData":"PHN2Zz48L3N2Zz4=",
  "hasShapes":[
    {"type":"Shape", "e":"M25"}
  ]
}
```
It doesn't look like any validation is occuring on related entities when the create source_to_target is set.  any comment there...  

Closing because this is fixed, but can open another issue for the validation on the related entity if it's appropriate.
