### ISSUE TITLE
Many Many errors updating to latest snapshot and importing existing backup.

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#438]
_Note: I've attached the import logs to bottom the issue:_
As a follow-on from another issue that's been recently fixed, I just tried out the latest snapshot (2.0 - 32) snapshot hoping to benefit from the update.  Unfortunately many issues and not ultimately successful getting it up and running : (

Old version (201601062321)
New version (201603281759)

I did add the following section to the structr.conf per previous instruction due to the new file system uniqueness paradigm.

```log
# File System Uniqueness Settings
application.filesystem.unique.paths = false
```
Typically I: 
- Bring the backup over
- Remove the old structr (manually delete after dpkg -r structr-ui)
- Run `dpkg -i strucxxxxxxxxxxxx` to install the new snapshot
- Edit the /usr/lib/structr-ui/bin/config to give structr 3-4 GB of memory
- copy my structr.conf into place
- copy/replace the backup into `/usr/lib/structr-ui/` as `seed.zip`
- cross fingers
- sudo service structr-ui start

#### A few observations
_1) Incredibly Slow_
  - Previous snapshot (201601062321) takes about 2-3 minutes to restore a 100mb zip backup made with the maintenance resource.  This version took about 30 minutes, a **significant ** regression.

_2) Massive volume of errors in the structr.log_
 - Schema Service cannot compile schema 

Structr Starts afterwards an presents a seemingly valid schema with the custom entities, however interacting with the schema dialogs shows that all is not well underneath

![invalid-schema-dialog](https://cloud.githubusercontent.com/assets/8261783/14125881/615673c6-f5c2-11e5-9fac-01b5497239aa.jpg)

Additionally the custom entities are not present on the Data Tab.

![missing-152-entities](https://cloud.githubusercontent.com/assets/8261783/14125893/6f69f410-f5c2-11e5-8772-8537a441791d.jpg)

Attached are the logs from the initial import and the first two start cycles afte the fact.

#### Logs
[import-and-first-cycle-logs.zip](https://github.com/structr/structr/files/194425/import-and-first-cycle-logs.zip)

Available to help troubleshoot.  would like the use the new build(s).

**Comment by amorgner** [comment]
New snapshot with the fix 5616cf2 is deployed.

**Comment by eric-schleicher** [comment]
Thank you!

**Comment by eric-schleicher** [comment]
Resolved.  imports with 2.0-33 did not product errors.

Thanks!
