### ISSUE TITLE
Oops enum value of 'continue' fails schema compile

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#439]
2.0 - snpashot 33

I made a video...

also tried to the values in single and double quotes but not alas...  not to be.

it seems this problem doesn't affect if you enter spanish spelling ;)

[![no complete](http://img.youtube.com/vi/uK8_PyY3H-o/0.jpg)](https://youtu.be/uK8_PyY3H-o)

Also does this mean that values for enums can't have spaces in them?  or just can't be emptystring ( simple comma delimit)

**Comment by cmorgner** [comment]
This is not a bug, but a direct consequence of creating Java code (and compiling it) from database content at runtime. Neither type names, nor property names or enum constants can contain characters that are not allowed in Java identifiers.

Please use simple strings as enum constants and use the `Localization` class and `localize()` builtin method to localize those strings.

See https://support.structr.com/article/135 for more information on that.
