### ISSUE TITLE
Pass external Volume to structr/structr Docker session?

### ISSUE THREAD

**Issue by lonniev** [structr/structr#443]
Pardon me if this is the repo to ask the question.

Can a docker user pass a "-v" option to "docker run structr/structr" to get that dockerized structr instance to persist its data outside the docker context?

I want to prototype building a structr-managed UI for a Neo4j db and I'd like the work in progress to persist between docker sessions.

**Comment by eric-schleicher** [comment]
Either the [Google Group](https://groups.google.com/forum/#!forum/structr)  or the #Structr channel on the [Neo4j Slack](http://neo4j.com/blog/public-neo4j-users-slack-group/) would be the right place to ask.

If i understand your question correctly, even without external mounts, the data you create "inside" the docker will persist between docker sessions.   you should be able to start and stop the docker without losing anything (if you're doing a vanilla docker).  If you rebuild the container however you'll have a different instance.

**Comment by amorgner** [comment]
We'll update the Dockerfiles based on the 2.0 release soon, so closing this old issue for now.

**Comment by ravensorb** [comment]
Did this ever get solved?
