### ISSUE TITLE
Feature Request/Stemming from challenges setting types: Entity.imageData attribute for all types extending `File`

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#452]
In the effort to ensure that all of my file based asset nodes/files are instantiated in their permanent class, I would like to be able to upload files (base64) through the appropriate rest resource in a consistent way for all entities that extend `File`.

It appears that currently, types that extend `Image` can apply base64 encoded value to the resource which will in-turn write the corresponding file asset.  Understading the _relative_ inefficiencies of this approach (the base64 overhead), this is very useful pattern that can be consistently levied on all types that extend type `File`.  

see related [groups discussion thread](https://groups.google.com/forum/#!searchin/structr/imageData/structr/I64xP90lWjc/D3_DbiaUhsQJ)

Allowing this for all types ( that extend file) addresses a number of design challenges and allows for setting all of the necessary initial information in a within a single transactional boundary, using json/rest.

_Alternatively:_
It's not clear whether this is even possible (single transaction to upload file, as well as set local and remote attributes) with Form/Multipart data.  I did not see how to add complex data (not simple name=value elements) nor could I find a similar implementation that wasn't a system effectively using text/plain and handling their own interpretations of the field.  The curl [examples](https://support.structr.com/article/404) doesn't address this use case (setting remote attributes) specifically and i couldn't find a standard method in the RFC spec that would seem to map to how structure exposed the graph to write operations.

Right now I've sub-optimally set my Font class (and other file based assets) to inherit Image so that they will take an imageData attribute.  adding support for this across the the other `File` types would resolve a permanent and scaleable pattern.

An example:
POST to /structr/rest/Font with 
```json
{
    "name": "AlegreyaSans-BlackItalic.ttf",
    "contentType": "application/octet-stream",
    "fontFaceName": "Alegreya Sans Black Italic",
    "faceNameInternal": "Alegreya Sans Black",
    "type": "Font",
    "fontCollectionHas": [{"id": "73cf41f22e834912b29a3a85a72a59c9"}],
    "parent": {
        "id": "6d709df0fce248acba61726503b103e7"
    }
    ,
    "visibleToPublicUsers": true,
    "visibleToAuthenticatedUsers": true,
    imageData: "//BASE64_ENCODED_FILE_CONTENT//"
}
```

Hope to hear back sometime soon on a solution.

**Comment by cmorgner** [comment]
I think a generic `base64Data` property on the `File` type could work here with minimal impact, what do you think @amorgner, @vigorouscoding?

**Comment by eric-schleicher** [comment]
Awesome!  Thank you so Much.

**Comment by eric-schleicher** [comment]
@cmorgner any idea on when this will be available as a snapshot?

**Comment by eric-schleicher** [comment]
@amorgner ?  most recent snapshot i see is 2.0.2 #1 (5/3/2016) might there be a fresher one perhaps including this commit ?
