### ISSUE TITLE
File Resource Permission Issue

### ISSUE THREAD

**Issue by aruntd77** [structr/structr#455]
Hi,

I created the HTML page by importing it from web site page. If I login as admin and access the newly created page, then I get the page rendered page properly. However if I switch to anonymous user, the style sheets, js files and images are not rendered. I am seeing 404 errors in fiddler/developer tool.

I also went to FileSystem and granted visible to public and authenticated users, but no luck. 

Interestingly, the path for Anonymous user was set to root, but not to actual path of the css. For example 
If the authenticated user logs in the path for bootstrap.css is set to <root>/asset/css/bootstrap.css. But when anonymous user logs in the path is shown as <root>/bootstrap.css, which is obviously wrong.

Can you help me to solve this issue?

I am using version 2.0.1 structr. on Windows 7.

Thanks
Arun

**Comment by amorgner** [comment]
Could you please verify that all necessary permissions are also granted for all directories in the path of the mentioned files (`/asset/`, `/asset/css`) etc?

**Comment by ravensorb** [comment]
@amorgner wouldn't the issue be that the paths being output by structr are different?  I would expect them to be the same regardless of who logs in or am I missing something?

**Comment by ravensorb** [comment]
@amorgner do you mean check on resource grants of folder permissions on the base OS filesystem (not in structr)?

**Comment by amorgner** [comment]
The reason the paths are different is that the permissions (visible to public users) are set only for the files and not the containig folders. Effective path of a file is generated dynamically at runtime by walking up the ancestor tree, and the result is just the filename as the parent folders are invisible.

It's a good question if it's a bug or just strange behaviour. :-)

**Comment by amorgner** [comment]
@ravensorb No, it's not related to permissions on OS level.

**Comment by ravensorb** [comment]
@amorgner ok, so our install is a base install doing using sudo on linux.  I have a "data" and a "files" folder off the base structr folder. I don't have an "assets" or "assets/css". Where should I be looking?

**Comment by ravensorb** [comment]
@amorgner also is there a document that talks about OS filesystem permissions and what is recommended?

**Comment by amorgner** [comment]
@ravensorb It's about the folders in the virtual filesystem, not on OS level.

![img-009](https://cloud.githubusercontent.com/assets/291266/15574837/e8168472-234f-11e6-8849-4f976c50aa6d.jpg)

**Comment by amorgner** [comment]
On OS level, the operating system user who starts the Java process has to have read and write access to all directories and files in the structr main directory.

**Comment by ravensorb** [comment]
@amorgner ahh :)  That makes more sense.  The trouble there is we are having a different issue

![image](https://i.imgur.com/jAh3yi6.png)

We start getting this as soon as we import any html page and cannot seem to find a fix for it.

**Comment by ravensorb** [comment]
@amorgner also are the settings inherited or do we need to set them at every level in the folder structure

**Comment by amorgner** [comment]
See https://support.structr.com/article/49#uniqueness.

The Importer should append a timestamp to avoid the name clash:

![img-010](https://cloud.githubusercontent.com/assets/291266/15575074/499d30e6-2351-11e6-941c-29c90ddb8f8d.jpg)

Which version of Structr are you currently using?

**Comment by amorgner** [comment]
> also are the settings inherited or do we need to set them at every level in the folder structure

No, they are not inherited but you can set them recursively:

![img-012](https://cloud.githubusercontent.com/assets/291266/15575157/bffd744e-2351-11e6-9742-3e69e6063b38.jpg)

**Comment by ravensorb** [comment]
@amorgner  you know -- I really should look before posting! :grin:   Thanks.  As for the "clashes" -- it is not appending the timestamp.  Was it possible this was a bug in an earlier build?  We were running the January build until about 2 weeks ago.

**Comment by amorgner** [comment]
The change for the Importer was introduced on Jan. 3rd (https://github.com/structr/structr/commit/ee6235b346a640879ed5764c89b6e87e660d9bc9) and included in any snapshot/release built after that date.

**Comment by ravensorb** [comment]
ok, that makes sense -- we were importing files before that.  Is there any easy fix? or should we just delete all files and re-import?

**Comment by amorgner** [comment]
Delete and re-import will do. We're working on a tool to identify and fix rename duplicates, see https://github.com/structr/structr/issues/462

**Comment by amorgner** [comment]
@aruntd77 Can we close this issue?

**Comment by aruntd77** [comment]
Yes, please.

Thank you
Arun
