### ISSUE TITLE
UI doesn't detect keyboard onblur between fields, causing attempt to add redundant attributes (and compile error)

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#456]
In the Schema Entity dialog in the attribute secion, when moving the focus from field to field with the `<tab>` key, it's very common for the UI to interprets multiple change events and trigger multiple schema recompiles.  

It would make sense that the onBlur event for the field be captures and to lock out subsequent changes until the first recompile event is complete.  It looks like the form is making a meaningful attempt to prevent changes while a schema recompile is running, I just don't think that it's detecting keyboard driven onblur event to lock the form.

**Comment by cmorgner** [comment]
This issue should be fixed with the most recent schema ui changes. We will publish a new snapshot based on Neo4j 3.0 shortly.

**Comment by amorgner** [comment]
A snapshot has just been released, feel free to test and report back, thanks!

**Comment by vigorouscoding** [comment]
I just change the event from `blur` to `change` for content-type (visible for StringProperty), "Format" and remote property names.

**Comment by vigorouscoding** [comment]
I'll close this issue as this has been fixed for a while - feel free to reopen or create a new issue if there is another problem
