### ISSUE TITLE
Oops, empty graphgist url input allows click with no input.

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#457]
I just accidentally did this.  The UI allows the user to trigger (click) the import GraphGist operation with nothing in the input field.  The log shows that it just ended up re-indexing the system.  but not sure if you want that process to even run if the user hasen't supplied *any* input.

...filed under trivial.

**Comment by cmorgner** [comment]
This is an (undocumented) feature that allows you to start the schema analyzer without importing new data. But I agree that the ui should at least ask for user confirmation or display a warning message, so I leave this issue open.

Thanks for reporting!

**Comment by amorgner** [comment]
As @cmorgner stated, it's just an undocumented (and unsupported/hidden) feature, there shouldn't be any harm to the data.
