### ISSUE TITLE
thumbnail display consistency in Crud (SVG vs raster images)

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#458]
![image](https://cloud.githubusercontent.com/assets/8261783/15307449/e48e5dfe-1b87-11e6-8574-8d79871cdc49.png)

This is what SVG image files look like in CRUD.  When clicking on the node to see it's detail, it do see the image:

![image](https://cloud.githubusercontent.com/assets/8261783/15307470/212cdccc-1b88-11e6-974b-9f0a2d0420e9.png)

it would be nice to see a thumbnail size represnation of the image, much like with raster based images.

filed under 'fit and finish'

**Comment by amorgner** [comment]
Thanks for this feature request. Shouldn't be too hard to do.

**Comment by amorgner** [comment]
Should be fixed, will be containted in the next snapshot.
