### ISSUE TITLE
Provide a tool to identify duplicate file system entries.

### ISSUE THREAD

**Issue by amorgner** [structr/structr#462]
There should be a maintenance command to find and modifiy/repair duplicate/multiple filesystem entries. The solution is to rename all but the first entry by appending a unique character sequence, like for example the object UUID and/or the current timestamp (with millisecond resolution).

Definition: Duplicate/multiple filesystem entry are duplicate/multiple files or folders with the same path.

Background: There's a switch to enable the enforcement of path uniqueness in Structr. Before the introduction of this switch, it was possible to create files and folders with identical name in the same folder/path.

**Comment by vigorouscoding** [comment]
The initial version of the new "Find Duplicates" functionality is now available in the current master.

It allows the user to identify duplicate filesystem paths and enables him/her to rename the offending files/folders or delete files (deletion of folders is not supported as this might result in more than the user bargained for).

If necessary more functionality to auto-rename all offending files/folders could be implemented though this would pose new challenges. A single postfix/prefix is not enough for cases where more than 2 files/folders have identical paths so the postfix/prefix.

For now the functionality supports a more hands-on approach as this will probably not be used very often (switching between allowing and disallowing duplicate filesystem paths should not be too common IMO...)

**Comment by Joshfindit** [comment]
Is it possible to abstract the files by one layer, and do something like `(fileObject)-[:HAS_FILENAME]->(filename.css)`, then traverse over this relationship when calling/serving the file?

This would allow for files to be de-duplicated and versioned as `fileObject` could have SHA1/MD5 hash along with it's UUID.
This would also allow intuitive flexibility for having the same file across multiple folders.

Full disclosure, this is not my idea; this is basically the trend that disk-based filesystems are moving towards.

**Comment by vigorouscoding** [comment]
As the main feature request of this ticket has been implemented quite a while ago I will close this ticket. Feel free to open a new issue if the de-duplication strategy outlined in https://github.com/structr/structr/issues/462#issuecomment-272667272 should be considered for future releases of structr.
