### ISSUE TITLE
Resetting of resource grants after re-compiling dynamic schema

### ISSUE THREAD

**Issue by l-1** [structr/structr#464]
As far as I know re-compiling triggers adding dynamic resource grants, but it overrides previous setting (e.g. on Class/_Ui - GET for authenticated users, after re-compiling all checkboxes are unchecked). That issue makes it impossible to get access to nodes of those classes in Edit Mode.

This issue is reproducible on a clean installation.

It would be great if resource grant's settings would be saved after re-compiling.

Structr version: 2.0.2-SNAPSHOT build fd1d6 (201605181524)

**Comment by amorgner** [comment]
Confirmed.

**Comment by eric-schleicher** [comment]
question, so i understand the taxonomy on resource grants...  are dynamic resource grants different than the ones administered in the structr-ui on the security section?

**Comment by l-1** [comment]
@eric-schleicher As far as I understand, Security section contains both static and dynamic resource grants + manually entered. But after re-compiling triggered by schema change some of dynamic resource grants (like Class/_Ui) are resetted to default value (Bitmask = 0).

**Comment by amorgner** [comment]
This bug should be resolved with 184a3ebebc9534eb01f119946bcc26c47780b6de. Please note that the commit is not yet merged into the master branch.

**Comment by l-1** [comment]
Finally got a snapshot and checked it. Problem is solved. Thanks!
