### ISSUE TITLE
Docker build for 2.0 version?

### ISSUE THREAD

**Issue by vielmetti** [structr/structr#472]
I'm looking at 

https://hub.docker.com/r/structr/structr/

and the provided Docker build there refers to the 1.0.0 build.

Issue #443 refers to a forthcoming Docker update for 2.x, is this otherwise available?

**Comment by amorgner** [comment]
We'll release a new Docker file along with the upcoming official snapshots of the 2.1 release.

**Comment by ravensorb** [comment]
Any chance of including docker builds on more of an automated basis (so we can build from the source tree if we need)?

**Comment by amorgner** [comment]
Docker builds are automated. All tags can be found here: https://hub.docker.com/r/structr/structr/tags/
