### ISSUE TITLE
Unrestricted access to files via FTP

### ISSUE THREAD

**Issue by l-1** [structr/structr#473]
Non-admin users can see, read and write files that aren't visible nor to public, nor to authenticated users, owner is admin and no access rights linked to these non-admin users or anybody else except admin.

_Structr version: 2.0.2-SNAPSHOT build e0f39 (201608111839)_

**Comment by amorgner** [comment]
Will be fixed with commit 4eb52ab5be9d7d27f8212d714d6f5e819789d04c.

**Comment by amorgner** [comment]
@l-1 Could you please test again with the latest snapshot release?

**Comment by l-1** [comment]
I've checked it using _structr-ui-2.1.0-20160929.080622-14 snapshot_. Even gone clean. But the problem is still there.

**How to re-create a problem**:

1. Create a user (i.e. 'user').
2. Create a folder (i.e.  'folder') in Structr FS, which shouldn't be visible to 'user'.
3. Create a file ('file').
4. Connect via FTP to Structr to remote dir '/folder' using 'user' credentials.
5. Now 'user' can see and modify 'file'.

**Comment by vigorouscoding** [comment]
I just tested this with the most recent version of structr and can not reproduce this bug.
could you please retest with your setup?

also some question to maybe get closer to a solution:

- can the user also see the files via REST? (when the Resource Access Grant exists)
- is there maybe a onCreate method on file/folder which sets visibility flags?

**Comment by vigorouscoding** [comment]
I just tested this once again and can not reproduce the behaviour - if you have a way to reproduce the behaviour in a fresh installation of structr, let us know and I'll take another look.
