### ISSUE TITLE
Idea: On Data Screen, allow for filtering out non custom entities

### ISSUE THREAD

**Issue by ravensorb** [structr/structr#480]
In the previous UI version it used to be possible to include/exclude ALL of the entities in the "Data" view -- now it seems we get very long list that we need to scroll through to try to find out custom entities.  For example, I am seeing entries for
- PRE
- Q
- S
- Rp
- Rt

![structr-ui-datatab-entitylist](https://cloud.githubusercontent.com/assets/2222472/20248838/3cb55bf2-a9ba-11e6-93c3-622fc8e5466f.png)

none of which are entities I created 

Note: this is a occurring in clean install of 2.1.0-SNAPSHOT build 1a149 (201611121209)

**Comment by vigorouscoding** [comment]
This feature is quite young (5 days) and these filters were in development - but I'm glad to know that they are useful :)

I just committed the newest version with the reworked (and hopefully improved) old functionality.

![screen shot 2016-11-15 at 11 25 13](https://cloud.githubusercontent.com/assets/3099108/20302183/918d2430-ab26-11e6-916a-bdec3af67f41.png)
