### ISSUE TITLE
enum data type can't have special words.  like boolean

### ISSUE THREAD

**Issue by eric-schleicher** [structr/structr#485]
oops... see below

**Comment by eric-schleicher** [comment]
the manner of data entry here is unescaped and fails when certain words are use that programmers like.

This is not valid:
![image](https://cloud.githubusercontent.com/assets/8261783/21001668/970d72a4-bcd6-11e6-95dd-e9bec858fee4.png)


This is valid:
![image](https://cloud.githubusercontent.com/assets/8261783/21001628/66be064a-bcd6-11e6-82b9-54b175bcd38c.png)


filed under FYI.

**Comment by vigorouscoding** [comment]
This is a known limitation - I think this is what is meant by **"Thus enum values have to be valid Java identifiers."** in the support article https://support.structr.com/article/329

I will update the article to highlight this more.

**Comment by vigorouscoding** [comment]
I'll close this as the documentation is better now and I added a warning message and an error explanation message in the schema area.
