### ISSUE TITLE
Allow token authentication to the API

### ISSUE THREAD

**Issue by Joshfindit** [structr/structr#487]
Even if we could add a "Token" type, connect that to a user, and have the endpoint accept it as a form of authentication, that would be fine by me.

Token authentication is all the rage since it allows easy access for applications without storing password, and safely revoking any devices that may be compromised.

**Comment by vigorouscoding** [comment]
Have a look at our documentation on the built-in OAuth support https://support.structr.com/article/175

I hope this will resolve this issue

**Comment by amorgner** [comment]
See also #369.

**Comment by derkaiserreich** [comment]
Structr supports authentication of users via JWTs now. See https://docs.structr.com/docs/handling-user-sessions?highlight=jwt#authentication-json-web-tokens for more information. 

Closing the issue since it is resolved.
