### ISSUE TITLE
UI change request: If only a few items are returned in the JSON explorer, expand all

### ISSUE THREAD

**Issue by Joshfindit** [structr/structr#488]
The UI available at http://127.0.0.1:8082/structr/rest/Artefact/public was a pleasant surprise.

I find as I'm learning, that I regularly have to expand individual children and sub-children using the tiny `+` (or the plus at the top-right).
I'd request that if there's only a few, then automatically expand at least the first-level child objects.

**Comment by vigorouscoding** [comment]
Good idea - I just added this functionality for five or less objects in the current master. If you are building from source you could just pull and compile to get this feature.

**Comment by vigorouscoding** [comment]
I just made a couple of tweaks and hope this will add a level of intuitiveness to the JSON HTML output. Thank you for the feedback!

**Comment by vigorouscoding** [comment]
I'll close this as the original issue has been resolved and the add-on feature also works. Hope you like it!
