### ISSUE TITLE
Unable to create relationship

### ISSUE THREAD

**Issue by cyrilthank** [structr/structr#489]
i get the below message when i try to create a relationship by clicking the bottom connector  of sourceto the top connector of target

MachineUNDEFINED_RELATIONSHIP_TYPEVM_Machine.null compiler_error: duplicate class: org.structr.dynamic.MachineUNDEFINED_RELATIONSHIP_TYPEVM_Machine

also i am not able to delete the file/folder/page etc..

i am using structr-ui-2.1.0-SNAPSHOT-201611121209.1a149

**Comment by cmorgner** [comment]
Hi,

in the future, please use to the [Structr Google Group](https://groups.google.com/d/forum/structr) for help and support regarding the Structr user interface.

The error message indicates that there already is a relationship between the two objects `Machine` and `VM_Machine`. There can only be a single relationship of the same type, and the type defaults to `UNDEFINED_RELATIONSHIP_TYPE`, so you have to modify the relationship type of the first relationship before you can create another one between the same two objects.

Does that help?

**Comment by whatSocks** [comment]
It would be nice to have a more user-friendly error message in this case.

**Comment by vigorouscoding** [comment]
I just added a more user-friendly error message.

> also i am not able to delete the file/folder/page etc..

Those types are built-in types and can not be deleted. `File` and `Folder` are the foundation of the built-in file storage system, `Page` is the top-level class which allows you to build HTML pages and so on.

I'll leave this open for feedback on the error message part - thanks for your feedback!

**Comment by vigorouscoding** [comment]
I'll close this issue as the error message is nicer now and we also added a visual aid for the user to be able to spot undefined relationships easier in the schema editor.
