### ISSUE TITLE
URI redirection issues

### ISSUE THREAD

**Issue by mmosemmle** [structr/structr#493]
The 'URI redirection from remote source' issues flagged by lgtm.com:
https://lgtm.com/projects/g/structr/structr/alerts/
seems vulnerable.
The first two may be susceptible even though the redirect parameter is prepended with '/' (see http://homakov.blogspot.co.uk/2014/01/evolution-of-open-redirect-vulnerability.html) and the last one does not have any slash prepending to it. Thanks.

**Comment by cmorgner** [comment]
Hi, thanks a lot for this very interesting hint! We're trying to resolve all the issues mentioned in the report.

**Comment by mmosemmle** [comment]
Thank you very much for the prompt reply and thanks for looking into this!
