### ISSUE TITLE
Exchange folder always fails on Windows

### ISSUE THREAD

**Issue by bryonvaughn** [structr/structr#494]
I can't for the life of me get any I/O functions to work using the sandboxed exchange folder, and a quick look at the code makes me think it might have something to do with the "wrong" slash being concatenated to the path variable in the getSandboxFileName() function.

I don't have a full build environment setup, or I would test it out locally, but if somebody could take a look, or let me know if there is some trick to get it working on Windows it would be very helpful.

**Comment by vigorouscoding** [comment]
I just verified the problem under Windows 10 - the read/write/append functions were not working correctly.
You identified the problem correctly and I made some changes there. The next snapshot/release will contain
the fix and hopefully you will be able to use those functions.
Thanks for your bug report and if you find anything else, please let us know!

**Comment by vigorouscoding** [comment]
I see you added a thumbs-up emoji so I guess this issue is resolved - closing
