### ISSUE TITLE
return then save doesn't save on the table widgets

### ISSUE THREAD

**Issue by whatSocks** [structr/structr#497]
<img width="654" alt="screenshot 2017-05-12 14 32 46" src="https://cloud.githubusercontent.com/assets/2731744/26011790/77d97bc0-3720-11e7-8fee-9d7d2cf8994e.png">

I spent a long time trying to figure out why I wasn't saving. I'm used to `return` = save, but here it seems to mean "make new line and don't save even after I hit the `save` button". 

**expected** flow while using one of the default configurable table widgets that comes with edit capability:

<img width="283" alt="screenshot 2017-05-12 14 50 02" src="https://cloud.githubusercontent.com/assets/2731744/26012374/512b4614-3722-11e7-9179-e6651af15b71.png">

* I add the widget to my page and do not modify it
* i preview the widget and press the edit button on a row
* i pick a field and type into it and press return
* data is saved and updated (assuming validation passes)

**actual flow**

* I add the widget to my page and do not modify it
* i hit edit button on one row
* i pick a field, type into it, and press save (since I know that pressing return won't work)

results (nothing happens): 

<img width="1241" alt="screenshot 2017-05-12 14 40 34" src="https://cloud.githubusercontent.com/assets/2731744/26011996/1635fc6c-3721-11e7-867a-2d638cbee833.png">

* I go to the widget and modify the `edit binding` of the `edit` button:

<img width="338" alt="screenshot 2017-05-12 14 42 01" src="https://cloud.githubusercontent.com/assets/2731744/26012042/363f709c-3721-11e7-943d-0b51c66c8a44.png">

* i go back to the preview and try again to edit the `name` field and press save
* it saves
* i go back to the preview and try again to edit the `name` field and press return
* it doesn't save

**Comment by whatSocks** [comment]
it would be nice to have access to the code for these widgets to be able to solve this faster.

**Comment by cmorgner** [comment]
Ok, I just spent some time testing this. The public view of the User entity contains id and type, which Structr submits when you hit the Save button. The backend then responds with a 422 because id and type are system properties and must not be modified.

The short solution would be to use a separate edit view that only contains those properties that the user is allowed to modify.

The long solution would be to prevent the 422 from happening when the submitted values are identical to the ones in the database, although I think that the error is intentional because system properties must not be editable in a form.

Paging @amorgner @vigorouscoding what do you think?

**Comment by amorgner** [comment]
@cmorgner As far as I know the 422 is intentional in this case, but we could modify the behaviour in the way you proposed. Also, `structr-app.js` could filter the system properties from the set being sent to the backend.

**Comment by whatSocks** [comment]
IMO this seems more like a UX problem

 It would be OK (or at least much less frustrating) from a UX perspective:

* if the error message told the developer that ID etc are not editable 
* read only fields were color coded or something in the schema > User node view
* There was a warning or help text about this on the view that says "append widget", since there is a reasonable expectation for widgets to work out of the box

**Comment by vigorouscoding** [comment]
I would not change the behaviour of structr-app.js to filter out system properties as these variable names can be useful when sending data to custom schema methods via this functionality.

adding more info to the error message would my favourite solution as this looks like (as far as i can tell without reproducing the error step by step) a developer error. Changing the widget might help as well as this seems to be the source of the problem.
ignoring the unchanged values might also be a viable solution... but adding more verbosity to the error message looks (at first glance) like a less invasive solution.

**Comment by whatSocks** [comment]
@cmorgner what about return + save vs just save?

**Comment by whatSocks** [comment]
realized this is a duplicate of #466
