### ISSUE TITLE
[feature request] Are you sure on Remove

### ISSUE THREAD

**Issue by whatSocks** [structr/structr#498]
```
$('.delete_icon', div).replaceWith('<i title="Remove" class="delete_icon button ' + _Icons.getFullSpriteClass(_Icons.delete_brick_icon) + '" />');
```

I've deleted so much work by accident :(

**Comment by cmorgner** [comment]
Just fyi, if you remove an element from the page tree, it will be placed in the "Unused Elements" flyout on the right, you should be able to find it and move it back into the page.

**Comment by whatSocks** [comment]
:O so that's what that thing is for!

**Comment by vigorouscoding** [comment]
Since the action is reversible (by manually retrieving deleted nodes from the "Unused Elements" flyout) I'll close this issue.
We are also in the concept phase of a "undo" functionality in the pages area - similar to #477
