### ISSUE TITLE
[bug?] create user via admin (works) vs via web frontend (fails silently) with unsupported parameter combination/count

### ISSUE THREAD

**Issue by whatSocks** [structr/structr#500]
I'm creating users via the frontend UI as an admin user.  I enter a name and password to create new users which can then log in. If User has a "bad" onCreate function (see image for a *toy* example), creating new users fails via admin but not frontend. 

* If I create a new user via the Structr admin (name and password only), I'm able to log in with this user in an incognito browser.
* If I create a new user via the frontend (name and password), the user is not created and fails silently. 

<img width="884" alt="screenshot 2017-05-16 12 25 06" src="https://cloud.githubusercontent.com/assets/2731744/26117116/6c67ed42-3a33-11e7-8b89-0136439c8807.png">

console error when creating via any method:

18:36:07.710 [qtp215619848-39] WARN  org.structr.core.function.Functions - set(): unsupported parameter combination/count in "db76ae0442f24ece9fa81e1e893270ab". Parameters: [db76ae0442f24ece9fa81e1e893270ab, visibleToPublicUsers, null]. Usage: ${set(entity, propertyKey, value)}. Example: ${set(this, "email", lower(this.email))} 

The error message seems to imply that ` visibleToPublicUsers` is set to `null`, but that is not the case for the users created via the admin: 

<img width="456" alt="screenshot 2017-05-16 12 40 24" src="https://cloud.githubusercontent.com/assets/2731744/26117526/db81db6a-3a34-11e7-9920-a8f6a169a75b.png">

wishlist:

* more informative console message? I might have typoed on an onCreate function and now wouldn't know to look there
* clarification about why admin can create new Users on one platform but not the other
* an error message on the frontend so I know create user failed

I also tried like this with similar results:

<img width="886" alt="screenshot 2017-05-16 12 43 39" src="https://cloud.githubusercontent.com/assets/2731744/26117685/4ee3fb10-3a35-11e7-9ac4-645a38841f45.png">

**Comment by ckramp** [comment]
> 18:36:07.710 [qtp215619848-39] WARN org.structr.core.function.Functions - set(): unsupported parameter combination/count in "db76ae0442f24ece9fa81e1e893270ab". Parameters: [db76ae0442f24ece9fa81e1e893270ab, visibleToPublicUsers, null]. Usage: ${set(entity, propertyKey, value)}. Example: ${set(this, "email", lower(this.email))}

This implies that the given parameter is null and not necessarily that `visibleToPublicUsers` is being set to that value. It is set in the _Data_ section, because you have the higher prioritised `onCreate02 ` function that is being called prior to `onCreate03`. The faulty one will abort execution during the `set` call and will not change the value of `visibleToPublicUsers`.
Is the _X_ in `visibleToPublicUsersX` intentional? You won't be able to set attributes via `set()` that you haven't specified in the _Schema_.

Getting feedback in the frontend for your creation call is possible. When requesting an object to be created a _POST_ is sent to a specific _REST_ endpoint e.g. `/structr/rest/User`, the reply will contain a status code that indicates whether the transaction was successful or failed and you can use that to display messages in the frontend.

**Comment by whatSocks** [comment]
This is what my setup looks like now and I can't create new users :( 

<img width="906" alt="screenshot 2017-06-22 15 42 05" src="https://user-images.githubusercontent.com/2731744/27452737-bef170e2-5761-11e7-9419-d6a8b7c3aef6.png">

**Comment by ckramp** [comment]
The `onCreate `functions look good. If I had to take a guess, I'd say it might be a permission problem. Have you checked the network tab on your browser developer console when sending the `POST `request to create the entity?

**Comment by whatSocks** [comment]
it says this and it seems like i'm sending an empty payload somehow 

```
Request URL:http://localhost:8082/structr/rest/User
Request Method:POST
Status Code:422 Unprocessable Entity
Remote Address:127.0.0.1:8082
Referrer Policy:no-referrer-when-downgrade
```

**Comment by ckramp** [comment]
Try double checking your Edit Mode Binding configuration for the elements used to create the entity in your html form.

**Comment by whatSocks** [comment]
It's the default from the widget library:

<img width="280" alt="screenshot 2017-06-22 16 12 29" src="https://user-images.githubusercontent.com/2731744/27453815-a79a1e36-5765-11e7-9b7e-14e4518fb3c6.png">

<img width="329" alt="screenshot 2017-06-22 16 12 39" src="https://user-images.githubusercontent.com/2731744/27453819-aa655630-5765-11e7-8ee4-769b37c67810.png">

**Comment by whatSocks** [comment]
I'm also running 623d987 since I couldn't get the current master to build.

**Comment by ckramp** [comment]
For the latest versions, you'll have to grab the snapshots from [here](https://structr.org/download).
The configuration looks right. Usually the server should repond with more than just the `422 Unprocessable Entity` message. There should be a more detailed error description in the body of the response.

**Comment by whatSocks** [comment]
ah found it, though I'm not sure where I'm going wrong since it seems to be configured correctly. 

```

errors
:
[{type: "User", property: "name", token: "must_not_be_empty"}]
0
:
{type: "User", property: "name", token: "must_not_be_empty"}
property
:
"name"
token
:
"must_not_be_empty"
type
:
"User"
message
:
"Unable to commit transaction, validation failed"
```

**Comment by ckramp** [comment]
Looks like your `POST `request doesn't carry the name attribute in it's payload. Could you please post full screenshots of the configuration pages for the _Edit Mode Binding_ tabs that you posted earlier?
