### ISSUE TITLE
[bug] no success green glow on add Principal to group

### ISSUE THREAD

**Issue by whatSocks** [structr/structr#501]
On other menus, once something has happened successfully they usually glow green. When I add a Principal to a group (whatever that is), nothing happens to indicate success. 

<img width="890" alt="screenshot 2017-05-17 15 06 28" src="https://cloud.githubusercontent.com/assets/2731744/26171363/b3f201c2-3b12-11e7-8170-81cd2d954454.png">

**Comment by vigorouscoding** [comment]
hehe, this issue got auto-closed because my commit-message said "fixes #501".

I just committed some code which adds the green glow to the element :)
