### ISSUE TITLE
[bug] editing the name of a group via web frontend deletes the members of a group?

### ISSUE THREAD

**Issue by whatSocks** [structr/structr#502]
setup: only `admins` and `members` of the group "moderators" can view and edit the group "moderators"

Story in pictures:

admin uses web frontend to rename group and everything is fine. 

UI (admin logged in) notice that user grape is a member of moderators
<img width="1001" alt="screenshot 2017-05-17 15 09 23" src="https://cloud.githubusercontent.com/assets/2731744/26171556/5aaedca6-3b13-11e7-8af2-69cbf6f615ca.png">

in the admin
<img width="1115" alt="screenshot 2017-05-17 15 09 41" src="https://cloud.githubusercontent.com/assets/2731744/26171579/72393d3a-3b13-11e7-9afa-ac670c29783a.png">

admin starts to edit and saves and all is well. `moderators` is now called `moderators 2` and all the members are still the same. 

<img width="999" alt="screenshot 2017-05-17 15 09 52" src="https://cloud.githubusercontent.com/assets/2731744/26171606/8c5c6cc8-3b13-11e7-8b54-a073d5141b8e.png">

<img width="1030" alt="screenshot 2017-05-17 15 10 39" src="https://cloud.githubusercontent.com/assets/2731744/26171653/c0688d62-3b13-11e7-80ed-80ad1eea7e48.png">

grape, a member of the moderator group logs in 

<img width="988" alt="screenshot 2017-05-17 15 10 16" src="https://cloud.githubusercontent.com/assets/2731744/26171618/976a116a-3b13-11e7-8d3d-57cae690867c.png">

grape edits and saves the name of the group, it is now called `moderators 3`. Notice that the members area is blank now (maybe this is where they get deleted?):

<img width="989" alt="screenshot 2017-05-17 15 10 31" src="https://cloud.githubusercontent.com/assets/2731744/26171835/5c54ab52-3b14-11e7-8c61-d31b238a88fa.png">

The table vanishes (since user `grape` has been removed from `moderators` group). 

<img width="989" alt="screenshot 2017-05-17 15 10 46" src="https://cloud.githubusercontent.com/assets/2731744/26171673/d4864212-3b13-11e7-96eb-a1d6151db70b.png">

over in the admin, I see my group, empty of members:

<img width="1099" alt="screenshot 2017-05-17 15 10 59" src="https://cloud.githubusercontent.com/assets/2731744/26171709/f4364da0-3b13-11e7-8c4f-57a10ecd6fca.png">

**Comment by ckramp** [comment]
The problem seems to be that _grape_ does not have permission to see the other members of the group and when the table gets rendered the field stays empty. If you enter _edit mode_ afterwards and save, it will assume the _empty_ members list is what the value is supposed to be and just overwrite it.
So the user can write to the group and read it's regular attribute, but not the related User-entities of the group.
Per default the groups are set up to not expose all members to each other, so that a user can be part of a group, but does not have access to all the data of each member.
A quick workaround to this would be adding an `onSave` method to the type _Group_ that loops over all members of the group and grants them the permission to see every other member of the group.

**Comment by whatSocks** [comment]
grape does have permission to see the other members of the group:

<img width="1338" alt="screenshot 2017-06-22 15 53 15" src="https://user-images.githubusercontent.com/2731744/27453021-ebdc7664-5762-11e7-9b05-c3d7881bcbc6.png">

once I hit "edit" the list of members vanishes. 

Maybe a better question is how do I make the moderators group have the same rights as the admin?

**Comment by ckramp** [comment]
Hm.. Just a thought: Click on the key symbol next to your page in the tree view, select 
> Apply visibility switches recursively?
and toggle visiblity for authenticated users and try again on your non-admin user. 
Sometimes during development it's forgotten to set visiblity for certain elements, especially if they are added later on in the project.
It's strange, because as you pointed out, the user can see the members and it's just the edit mode hiding them.

**Comment by whatSocks** [comment]
Moderators should be able to edit things in the row. They can edit the name of the group, for example. 

<img width="897" alt="screenshot 2017-06-22 16 17 32" src="https://user-images.githubusercontent.com/2731744/27453999-5f7566b4-5766-11e7-91ce-cbd6d428ff32.png">

<img width="352" alt="screenshot 2017-06-22 16 18 46" src="https://user-images.githubusercontent.com/2731744/27454032-7ba4157e-5766-11e7-9a2f-c4569fdea0e4.png">

Maybe it's because the content of the row is built like this? This is from the widget library. 

```
${if(is_collection(get(Group, property.jsonName)),join(extract(get(Group, property.jsonName), 'name'), ','), if(is_entity(get(Group, property.jsonName)), get(get(Group, property.jsonName), 'name'), get(Group, property.jsonName)))}
```

**Comment by ckramp** [comment]
I'm not entirely sure, if the Access Rights are evaluated in regard of visibility within the page in that context. Have you tried setting the visiblity for authenticated users on that page? It's just for the html elements itself and won't influence what user can view what data, but just which html elements can get rendered into the page for the specific user.

**Comment by whatSocks** [comment]
I tried this for the whole page and toggled the top two "visible to X users" buttons with "apply recursively" checked. However I notice that the green success glow only happens when you edit the  top two "visible to X users" buttons, not when editing the table with the read / write / et cetera checkmarks. 

<img width="888" alt="screenshot 2017-06-22 16 42 08" src="https://user-images.githubusercontent.com/2731744/27454979-d13037ae-5769-11e7-8538-51db54c04ace.png">

**Comment by ckramp** [comment]
The green flash is just an UI feature and doesn't mean the changes in `Access Rights` won't get registered. Did setting the whole page to visible change anything and did you make sure to check `Apply visiblity switches recursively?` before doing so?

**Comment by whatSocks** [comment]
I just tried again

- opened menu
- applied check
- unchecked everything on moderators row
- re-added moderators row and checked everything
- closed menu
- opened new incognito window
- logged in as member of "moderators" group
- no change

**Comment by ckramp** [comment]
What I'm suggesting only applies to the `Visibility `area of the form. 
Basically:

1. Check option
2. Uncheck both visibilities
3. Check both visibilities
4. See if it behaves differently

If that does not help, it'll be hard to diagnose further without access to the instance.
If you need further help with the problem, you could export the application and send me the files, so I can import the app locally and test it myself.

**Comment by whatSocks** [comment]
<img width="544" alt="screenshot 2017-06-23 14 22 37" src="https://user-images.githubusercontent.com/2731744/27495314-7ac851d8-581f-11e7-983a-fe4ca66c218f.png">

I solved not being able to edit, I overlooked the warning about this access grant.
