### ISSUE TITLE
mvn clean install -DskipTests fails on Jarsigning Structr Core

### ISSUE THREAD

**Issue by mdonges** [structr/structr#504]
[INFO] --- maven-jarsigner-plugin:1.2:sign (sign) @ structr-core ---
[WARNING] Enter Passphrase for keystore: 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Structr ............................................ SUCCESS [  0.720 s]
[INFO] Structr Database Driver API ........................ SUCCESS [  1.848 s]
[INFO] Structr Neo4j Bolt Driver .......................... SUCCESS [  2.356 s]
[INFO] Structr Core ....................................... FAILURE [  7.427 s]
[INFO] Structr REST ....................................... SKIPPED
[INFO] Structr UI ......................................... SKIPPED
[INFO] Structr Modules .................................... SKIPPED
[INFO] Structr XMPP Module ................................ SKIPPED
[INFO] Structr Media Module ............................... SKIPPED
[INFO] Structr API Builder ................................ SKIPPED
[INFO] Structr File Access Module ......................... SKIPPED
[INFO] Structr Text Search Module ......................... SKIPPED
[INFO] Structr Data Feeds Module .......................... SKIPPED
[INFO] Structr CSV Module ................................. SKIPPED
[INFO] Structr Binaries ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.636 s
[INFO] Finished at: 2017-05-24T13:43:09+00:00
[INFO] Final Memory: 84M/620M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jarsigner-plugin:1.2:sign (sign) on project structr-core: Ausführung von '/bin/sh -c cd /home/dev/trainingsInstance/structr/structr-core && /usr/lib/jvm/java-8-openjdk-amd64/jre/../bin/jarsigner -keystore /someuser/.structr/structr.keystore /home/dev/trainingsInstance/structr/structr-core/target/structr-core-2.1.0-SNAPSHOT.jar structr' fehlgeschlagen - Ergebniscode (1) -> [Help 1]
[ERROR] 

last build I could successfully execute was: after git checkout fb5496c

git log --pretty=format:"%h - %an, %ar : %s"
1f46333 - Christian Morgner, 3 hours ago : Fixes copying of modules into structr-ui directory, removes some old scripts from distribution packages, fixes distribution packages.
ee3529b - Christian Morgner, 6 hours ago : Merge branch 'master' into licensing
357ad68 - Christian Morgner, 22 hours ago : Fixes dependencies and logging for core and all modules, no duplicate libraries any more.

fb5496c - vigorouscoding, 23 hours ago : Feature: Search for the supplied value in the input field instead of simply listing all objects of the type Feature: Add inexact searching to SearchCommand

1355d9c - Christian Morgner, 24 hours ago : First steps towards unified dependency management in parent POM, work in progress.

all newer builds fail with me...

**Comment by amorgner** [comment]
Yes, that's intended behaviour. Starting from now, we encourage users to download and use binary distributions built and signed by us.
