### ISSUE TITLE
/structr/rest/maintenenance/deploy import on Windows fails

### ISSUE THREAD

**Issue by bryonvaughn** [structr/structr#505]
Hi again,
I'm finding that it might have been a mistake to plan to use Structr on a Windows based server, as this is the second issue I have found that seems to be isolated to the Windows platform.

Whenever I attempt to perform an import using the maintenance deploy rest function, it fails with the following error during the shared components portion of the import:

JsonSyntaxException in POST: org.neo4j.driver.v1.exceptions.NoSuchRecordException: No more records

I tried the same import on an OSX dev system and it works fine, so I think we have another case of some difference in either file names or paths that are specific to Windows.  Just curious, but are you doing any dev/delivery on Windows systems?

**Comment by amorgner** [comment]
To be honest: Not much. The entire Structr team and almost all of our customers use Unix (OS X, Linux) as operating systems. Most developers in the community don't use Windows either.

On Windows, we recommend to use Docker. We'll release new Docker images/Dockerfiles together with 2.1 very soon.

**Comment by bryonvaughn** [comment]
Thanks for being frank on this.  We aren't married to Windows, it just happened to be what we had available for testing out the platform.  Do you still want reports of Windows-specific issues, or are you thinking that the Windows will be "officially" supported only through Docker/virtualization?

**Comment by bryonvaughn** [comment]
Last note on this:
I dug into the logs on the OSX system where the import worked fine, and compared it to the fail on Windows, and found the offending SharedComponent.  The bit that caused problems for Windows was here:
...

<td>
...
Stripping out the private reference allowed it to run through Windows without issue.

Not sure if any of this is worth trying to fix, but there it is.  Problem solved for me, though I'm not sure how that element ended up with the private tag in the first place.

Cheers!

**Comment by vigorouscoding** [comment]
I do believe this was due to problem in how line endings were handled.
If you still have the old export around you could try with the most recent development snapshot and I think it should work.

If not, could you provide us with the export (or just the offending files) so we can debug this further?

**Comment by bryonvaughn** [comment]
After stumbling upon a few other issues that seemed to only occur on Windows, we changed our sandbox to OS X and haven't had problems like this.  I'm sorry, but I don't have a copy of the offending version of the file to share for debugging.

As far as we are concerned, the issue can be closed.
