### ISSUE TITLE
Could not initialize class org.structr.dynamic.Project

### ISSUE THREAD

**Issue by miebakso** [structr/structr#506]
When i change 

Rest Qery to Cypher Query
it works fine 

Project?sort=name

to 

MATCH (n:Project)-[]->(m:ProjectMember) RETURN { id:n.id, name:n.name, projectMember:m, description:n.description, asd:n.asd} AS project Order By n.name

but when i change back, it wouldn't work

**Comment by vigorouscoding** [comment]
A couple of questions to pin down the problem:

- Which version of structr are you running?
- Can you provide the server.log so we can have a look?
    (I just created the custom type `Project` in an empty Structr instance and everything worked as expected)
- If you could also attach a schema snapshot (Schema->Tools->Snapshots->Create Snapshot)
    (the resulting snapshot can be downloaded by clicking the new link in the table below the `Create Snapshot` button)

**Comment by miebakso** [comment]
i am using version 2.0.1

is there any link to easy tutorial for structr? i am new and finding a hard time using structr and the structr document is not so clear to me.

this is the zip for server.log and snapshots
[snapshots&serverlog.zip](https://github.com/structr/structr/files/1060074/snapshots.serverlog.zip)

**Comment by vigorouscoding** [comment]
Thank you for the info!

First of all I can recommend that you upgrade to the newest version - we just released a new stable version (2.1.1) yesterday which includes **a lot** of fixes and new features: https://structr.org/download

Also, a short while ago our friends at TheSilverLogic wrote a guest blog post in our blog with a step-by-step tutorial for a blog app. This could be interesting for you. https://structr.org/blog/blog-app-tutorial

Secondly (at least at some points in the log) I can see that the REST query was input in the Cypher query field. This explains it not working.
Could you check and see how the repeater looks. Make sure that only one repeater is filled and the REST query is in the REST field. The fields are dynamically shown and hidden when you click the tab above the field.

For REST it should look like this: (and when you click the cypher tab it should be empty)
![screen shot 2017-06-08 at 08 23 46](https://user-images.githubusercontent.com/3099108/26915078-d8011878-4c24-11e7-8032-9f38a245d372.png)

You can check all queries in the "Node properties" tab scrolling a bit down. Only one should be filled.
![screen shot 2017-06-08 at 08 24 09](https://user-images.githubusercontent.com/3099108/26915091-e831b630-4c24-11e7-95fa-ebf3dac0aa18.png)

You can delete the other queries by either emptying the text boxes and clicking "Save" in the "Query and Data Binding" tab or by clicking the "x" in the "Node Properties" tab.

Hope this works for you! Let me know if this solved the problem! :)
