### ISSUE TITLE
Case insensitive search doesn't work with Cyrillic

### ISSUE THREAD

**Issue by l-1** [structr/structr#509]
It doesn't work neither in search StructrScript function, nor in REST requests with 'loose=1', only exact and inexact case sensitive searches are working.

**Comment by amorgner** [comment]
Would you mind providing a test case?

**Comment by amorgner** [comment]
Structr uses UTF-8 everywhere, so in general any letter/character works. A quick test with StructrScript and REST in the interactive console (activate with ctrl-alt-c) passes:

	        _                          _         
	 ____  | |_   ___   _   _   ____  | |_   ___ 
	(  __| | __| |  _| | | | | |  __| | __| |  _|
	 \ \   | |   | |   | | | | | |    | |   | |
	 _\ \  | |_  | |   | |_| | | |__  | |_  | |
	|____) |___| |_|   |_____| |____| |___| |_|  
	Welcome to Structr (2.3.5  ). Use <Shift>+<Tab> to switch modes.
	Mode is 'JavaScript'.
	Mode set to 'StructrScript'.
	admin@Structr> find('Page', 'name', 'Д')
	[428319001bf24115a6af9509b4180eb4]
	admin@Structr> search('Page', 'name', 'Д')
	[428319001bf24115a6af9509b4180eb4]

	Mode set to 'Cypher'.
	Mode set to 'AdminShell'. Type 'help' to get a list of commands.
	Mode set to 'REST'. Type 'help' to get a list of commands.
	anonymous@Structr> as admin:admin get /Page/?name=Д
	GET http://0.0.0.0:8082/structr/rest/Page/?name=Д
	HTTP/1.1 200 OK
	{
	    "query_time": "0.015996504",
	    "result_count": 1,
	    "result": [
	        {
	            "id": "428319001bf24115a6af9509b4180eb4",
	            "type": "Page",
	            "name": "Д",
	    		
	    		...
	        }
	    ],
	    "serialization_time": "0.001799829"
	}

	anonymous@Structr> as admin:admin get /Page/?name=Д&loose=1
	GET http://0.0.0.0:8082/structr/rest/Page/?name=Д&loose=1
	HTTP/1.1 200 OK
	{
	    "query_time": "0.004041293",
	    "result_count": 1,
	    "result": [ ... ]
	}

Without further details we can't determine what went wrong in your case so I close this issue. If you can provide a good test case please reopen this issue and describe exactly what you did, what didn't work and what you expected.
