### ISSUE TITLE
No CSS displayed for unauthenticated users

### ISSUE THREAD

**Issue by ongzexuan** [structr/structr#511]
Hi I'm new to structr. I'm following the tutorial as posted here, and I'm stuck at the resource access grant section:
[https://structr.org/blog/blog-app-tutorial#resource-access-grants](https://structr.org/blog/blog-app-tutorial#resource-access-grants)

I cannot seem to get the bootstrap CDN to be displayed for unauthenticated users i.e. When I open the signup page on incognito or other browsers, I get a page without css. I've checked the source of the pages with issues, and it displays a "?" where the link should be in the link href.

I have selected "apply visibility switches recursively" before toggling the visibility to public users. I think the green flashes on all the nodes in the tree is a positive indicator. However there is no CSS being displayed for unauthenticated users. I have also toggled on the visibility to authenticated users as well but there is no difference.

I am using structr 2.1.3 on OSX 10.12.6.

**Comment by vigorouscoding** [comment]
Setting the visibility switches in the pages editor only sets visibility of the page elements (tags, templates, etc). The files themselves also need to be visible for public users.
Go to the "Files" area and set the visibility options for the file and every folder in the file path to be visible to public users. That should work.

On a side-note: This is not a bug and more of a structr-users question. The best place to ask this question would be our discussion group: https://groups.google.com/forum/#!forum/structr
