### ISSUE TITLE
Sample Application Tutorial - Redirecting Elements

### ISSUE THREAD

**Issue by parm00** [structr/structr#512]
Trying to follow the tutorial at https://support.structr.com/article/232 . When I import the bootstrap jumbotron page, the elements are not as shown in the screenshots. Many state 'Redirecting..' . Is this the expected behaviour?

**Comment by vigorouscoding** [comment]
This is not a problem with structr - the page on the external page has been changed. It is now redirecting to another page: https://getbootstrap.com/docs/3.3/examples/jumbotron/
Change out the URL to that and you should be fine.
I will update the article - thanks for bringing this to our attention!
