### ISSUE TITLE
docker error: manifest not found

### ISSUE THREAD

**Issue by smartinsightsfromdata** [structr/structr#513]
I'm using OSX 10.13.2 & Docker Version 17.12.0-ce-mac49 (21995).

I follow the instructions on docker hub: use `docker pull structr/structr`

This is what I get:

```
$ docker pull structr/structr
Using default tag: latest
Error response from daemon: manifest for structr/structr:latest not found
```

**Comment by amorgner** [comment]
Thanks for reporting this. Please add the tag you want to pull, like in the following example:

    $ docker pull structr/structr:2.3.3

Documentation is updated.
