### ISSUE TITLE
How make persistence in Docker?

### ISSUE THREAD

**Issue by GustavoRPS** [structr/structr#515]
What is the `volume` path on docker to not lost the data when move the container?

Something like this:

`docker run -ti -v ~/data/structr:/var/lib/structr/? -p 0.0.0.0:8082:8082 structr/structr:2.3.5`

**Comment by amorgner** [comment]
The default setup doesn't use volumes. To decide what you want to persist, see https://support.structr.com/article/256.

Please note that we'd like to use the GitHub repo for bug reports and feature requests exclusively. For general questions and discussions around Structr, there's a mailing Google Groups list/forum at https://groups.google.com/forum/#!forum/structr.
