### ISSUE TITLE
Running on Docker: Out of memory

### ISSUE THREAD

**Issue by gustavorps** [structr/structr#516]
Environment: Linux
 
```
docker run -ti -p 0.0.0.0:8082:8082 structr/structr:2.3.3
        Creating logs directory...
        Starting structr server structr-2.3.3.jar: OK

OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000006c0000000, 4294967296, 0) failed; error='Out of memory' (errno=12)
```

**Comment by amorgner** [comment]
Structr tries to allocate 4 GB of RAM at startup and fails to do so. You can either add more RAM (recommended) or reduce the Java heap space Structr tries to allocate in the configuration:

To do the latter, start the docker container and login with

    sudo docker exec -i -t <your-docker-container-id> /bin/sh

You should land in the directory `/var/lib/structr`. Edit `bin/config`, go to the line beginning with `JAVA_OPTS` and modify the parameters

    -Xms4g -Xmx4g

to a value of about 75% of available RAM. As an example, if your container can allocate 4 GB of RAM, set it to

    -Xms1g -Xmx3g

Does that help?

**Comment by ravensorb** [comment]
Any thoughts on making this a param that can be passed in via docker?

**Comment by GustavoRPS** [comment]
@amorgner thanks for the config tip!

I solver my problem to run the container in test mode setting the [container memory resource option](https://docs.docker.com/config/containers/resource_constraints/#memory):
`docker run -ti -p 8082:8082 --memory=4g structr/structr:3.0.3`

I liked the @ravensorb suggestion to make the memory options parameterized.
I look in the `structr-binaries/src/main/deb/bin/config`[file](https://github.com/structr/structr/blob/3.1.1/structr-binaries/src/main/deb/bin/config) of version 3.1.1 and find the `MEMORY_OPTS` variable. 

I think we can add another condition in `config` to check if an environment variable `$MEMORY_OPTS` is set.

My sugestion is to change `structr-binaries/src/main/deb/bin/config` file from:

https://github.com/structr/structr/blob/c9393ed5f0767637257333d122a16d71b3aa40cb/structr-binaries/src/main/deb/bin/config#L1-L17

to

```
#!/bin/bash
#
# configuration options for FINAL_NAME
#

if [ -f /usr/lib/structr/bin/memory.config ]; then
	MEMORY_OPTS="$(cat /usr/lib/structr/bin/memory.config)"
elif [ -n "$MEMORY_OPTS" ]; then
       	MEMORY_OPTS="$MEMORY_OPTS"
else
	MEMORY_OPTS="-Xms4g -Xmx4g"
fi

RUN_OPTS="-cp lib/*:FINAL_NAME.jar"
JAVA_OPTS="-Djava.awt.headless=true -Djava.system.class.loader=org.structr.StructrClassLoader -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false -Duser.timezone=Europe/Berlin -Duser.country=US -Duser.language=en -Dorg.apache.sshd.registerBouncyCastle=false -Dorg.neo4j.io.pagecache.implSingleFilePageSwapper.channelStripePower=0 -server -d64 $MEMORY_OPTS -XX:+UseNUMA -XX:+UseG1GC"
MAIN_CLASS="org.structr.Server"
DISPLAY_NAME="FINAL_NAME"
LOG_FILE="/var/log/structr.log"
PID_FILE="/var/run/structr.pid"
```

**Comment by vigorouscoding** [comment]
Thank you for your input! I just checked and saw that the `config` file is only used when creating the `deb` archive.
Another instance of that file is used for docker builds. This is due to the difference in paths for different build envs. For deb the path is `/usr/lib/structr/bin/`, for docker it seems to be `/var/lib/structr/bin`...

But I will have a look at which file it is and see to it that we change it so that you can use the MEMORY_OPTS variable and it is not overwritten.

I think it would make sense to change your code slightly to only write the MEMORY_OPTS if they are not set already.
```
if [ -z "$MEMORY_OPTS" ]; then
	MEMORY_OPTS="-Xms4g -Xmx4g"
fi
```

**Comment by amorgner** [comment]
With the two commits ace4e66a9febc3fdc3dbc4297a2207f4c4078054 and d7f39e2f92fcf5270697f83b12ec770ee2dc2d57 we have removed the defaults for `-Xms` and `-Xmx` completely and introduced the option to set `MEMORY_OPTS` in the environment or via command line.

I think this issue can be closed. Please feel free to re-open and/or comment on this.
