### ISSUE TITLE
How do I get code-signing keys for community build?

### ISSUE THREAD

**Issue by grimace** [structr/structr#523]
successful build does not produce functioning code.  Is it possible to get code-signing keys or is the community edition no longer viable?

**Comment by cmorgner** [comment]
I just uploaded the latest stable release to structr.org/download, does that fix your problem?

**Comment by cmorgner** [comment]
Additionally, you can use the Docker image at https://hub.docker.com/r/structr/structr/, or download the latest build from our CI server at http://ci.structr.org:59398/job/Structr/ws/structr-binaries/target/
