### ISSUE TITLE
Removing the id column from the Data view breaks page size

### ISSUE THREAD

**Issue by peter-vanderspiegel** [structr/structr#525]
Hi,

When you remove the id column from the Data view, only one more line is displayed in the table. The ajax request for the data doesn't return the id's anymore. The code to build the table uses the id to check if a row with that id already exists. If it can't find one, it creates a new row, if it can find one it updates the existing row. The first result creates a row with id _undefined. All subsequent results also have their id equal to undefined, so they just overwrite the first line. I suppose you should never remove the id from the data to fetch.

Thanks,
Peter Van der Spiegel, Neanex

**Comment by amorgner** [comment]
Good point, thanks! Will be fixed in one of the next snapshots.

**Comment by amorgner** [comment]
Has been fixed with https://github.com/structr/structr/commit/501a5a7dde87a206de58f811697e3c67053a69fe#diff-50629ddd6530ea882af55d44a9c83346R1090.
