### ISSUE TITLE
"Error: Could not find or load main class org.structr.Server"

### ISSUE THREAD

**Issue by Sparkblender** [structr/structr#532]
Just followed the instructions described [here](https://support.structr.com/article/258), but get the following message after executing "c:\Program Files\structr-3.3.3\bin\start.cmd" 

"Error: Could not find or load main class org.structr.Server"

I installed Structr on Windows 7 Ultimate x64 from latest download:  Structr-3.3.3.msi

Any ideas how to troubleshoot this issue?

Thanks.

**Comment by derkaiserreich** [comment]
Hi,

did you call the start script from the bin folder with `start.cmd` or from the root directory of your Structr installation with `bin\start`? When you call it from the bin folder itself, the directory path to the main jar files can't be found, that would explain that error message.

Can you check on that and give us feedback again? 

Thanks!

**Comment by Sparkblender** [comment]
Hi derkaserreich,

It worked.  I started the script as `bin\start.cmd` from `c:\Program Files\structr-3.3.3\bin` which is my installation directory.

Thanks!

**Comment by derkaiserreich** [comment]
Ok, super! Thank you for the feedback.

I'll close this issue then.
