### ISSUE TITLE
Could not initialize class org.structr.schema.compiler.NodeExtender on Windows 7

### ISSUE THREAD

**Issue by Sparkblender** [structr/structr#533]
After following the instructions described [here](https://support.structr.com/article/258), and executing `bin\start.cmd`, I can't get Structr to run.  I'm getting the following error messages:

[start_mcv_log.txt](https://github.com/structr/structr/files/3410438/start_mcv_log.txt)

The first error is:

> 11:28:39.779 [main] ERROR org.structr.schema.SchemaService - Unable to compile dynamic schema: Could not initialize class org.structr.schema.compiler.NodeExtender

I installed Structr on Windows 7 Ultimate x64 from latest download: Structr-3.3.3.msi

The first reason I could think of is the the common issue with the Java JDK, but I'm not sure if this is the root cause.  

The `where java` and `where javac` both returned the expected results, namely:
`C:\Program Files\Java\jdk1.8.0_221\bin\java.exe`
`C:\Program Files\Java\jdk1.8.0_221\bin\javac.exe`

I found that only the following got enabled though:  
`c:\Program Files\Java\jre1.8.0_221\bin.javaw.exe`

The following shows it in more detail:
[Installing Java JDK 8 on Windows 7 (1).pdf](https://github.com/structr/structr/files/3410382/Installing.Java.JDK.8.on.Windows.7.1.pdf)

Any ideas where the problem could be?

Thanks.

**Comment by cmorgner** [comment]
The MSI installs a system service that starts Structr automatically, so there is no need to run the start.cmd manually.

I suspect that the start.cmd picks up a JRE instead of the JDK which leads to the well-known error.

**Comment by Sparkblender** [comment]
@cmorgner 

> The MSI installs a system service that starts Structr automatically, so there is no need to run the start.cmd manually.

Does this mean that I should be able to start Structr without problems?  As I enter `http://localhost:8082/structr` in my browser, I still get the infamous "this site can't be reached" message.

> I suspect that the start.cmd picks up a JRE instead of the JDK which leads to the well-known error.

Please excuse my lack of experience with this subject, but does this mean there is still a problem with the JRE/JDK? 

Thanks.

**Comment by Sparkblender** [comment]
@cmorgner

> > The MSI installs a system service that starts Structr automatically, so there is no need to run the start.cmd manually.
> 
> Does this mean that I should be able to start Structr without problems? As I enter `http://localhost:8082/structr` in my browser, I still get the infamous "this site can't be reached" message.

After some more testing, I found that the Structr service was not started, as it was set to manual mode.  After starting the service, I'm now able log into Structr.

A small side note: I noticed that on my system it takes about 2 min. for the service to start after booting the PC.

Thanks for the help.
Cheers.
