### ISSUE TITLE
Security Contact Request

### ISSUE THREAD

**Issue by prodigysml** [structr/structr#540]
Hi! We found some potential security flaws and were wondering whether there was anyone we could talk to on the contributor's team about it. Is there anyone we can talk to?

**Comment by amorgner** [comment]
Sure, feel free to pick and contact someone from the team. Or just post your findings here, or, if you want to contribute, submit a PR. Thanks a lot!

**Comment by vigorouscoding** [comment]
I believe this issues can be closed - feel free to comment if there are more questions
