### ISSUE TITLE
Group users shouldn't be self-added

### ISSUE THREAD

**Issue by JonasL5** [structr/structr#541]
Hi guys,
I added a permission group to itself and displayed the members; my browser started to infinitely loop.

That's fun but I'm not sure why you would allow this in any use case ^^'

![image](https://user-images.githubusercontent.com/59539594/84105557-f257d180-aa18-11ea-89f4-94b90a718d09.png)

**Comment by vigorouscoding** [comment]
Thanks for reporting - this is fixed with https://github.com/structr/structr/commit/72c126af42074f059ed5f6fcdc713546fee3c35a
