### ISSUE TITLE
if query parameter contains 'announce' will no response from rest api

### ISSUE THREAD

**Issue by gege-shinetech** [structr/structr#550]
for example:
http://localhost:8082/structr/rest/TestTable?name=announce
http://localhost:8082/structr/rest/TestTable?name=blablable_announcements
both requests for a get method will be no response from structr.

**Comment by cmorgner** [comment]
Hi,

thank you for reporting this issue!

The REST interface uses _exact match_ queries by default, so you will only see those result that match the given request parameter exactly.

If you want to do an inexact search, please add the request parameter `loose=1`.

Does that help?

For future question, please refer to the Structr Goole Group at https://groups.google.com/g/structr!

Best regards,
Christian

**Comment by gege-shinetech** [comment]
thanks @cmorgner , but the issue is not about exact or inexact, the issue is if the query parameter's value contains 'announce', when call a get method of the rest api, the request will keep loading until timeout, cannot get any response.

**Comment by cmorgner** [comment]
Sorry I misunderstood your initial comment.

Can you please share the following information:
- Structr version
- log file
- schema (screenshot or JSON export)
- database contents (what and how many objects of type TestTable exist?)

Are there any scripting actions defined on the test type? Are there maybe a lot of test objects in the database?

The behaviour / error situation is very unusual, so please share as much information as you can!

Thank you.

**Comment by gege-shinetech** [comment]
![image](https://user-images.githubusercontent.com/20633093/106721361-86794780-663f-11eb-86e1-65b2bd1ba548.png)
![image](https://user-images.githubusercontent.com/20633093/106720302-436aa480-663e-11eb-8c4c-659bcb671857.png)
![image](https://user-images.githubusercontent.com/20633093/106720320-4cf40c80-663e-11eb-9706-bee5c1708e9c.png)
![image](https://user-images.githubusercontent.com/20633093/106720504-8593e600-663e-11eb-8010-66ba619b0b45.png)
![image](https://user-images.githubusercontent.com/20633093/106720626-a6f4d200-663e-11eb-8100-53142679848c.png)
![image](https://user-images.githubusercontent.com/20633093/106720998-0e128680-663f-11eb-902e-70096416a732.png)
![image](https://user-images.githubusercontent.com/20633093/106721071-25ea0a80-663f-11eb-96bf-97bd9b0069c4.png)

@cmorgner here are some images for the issue, hope it could be help.

**Comment by cmorgner** [comment]
Can you please share the log file, there could be some info in there.

**Comment by gege-shinetech** [comment]
@cmorgner here is the server log
[server log.txt](https://github.com/structr/structr/files/5918121/server.log.txt)

**Comment by cmorgner** [comment]
Hi, please use the official project-specific communication channels for internal project issues. You can reach me via e-mail, or open a ticket in the project.

**Comment by gege-shinetech** [comment]
@cmorgner Thanks, what's your email address?

**Comment by cmorgner** [comment]
I sent you an e-mail the address in listed in your github profile, did you get that one?
