### ISSUE TITLE
The UI starts to blink endlessly

### ISSUE THREAD

**Issue by JusticeN** [structr/structr#560]
Version | 4.1-SNAPSHOT 86e2c9 202112161219 (no new release available \| no new snapshot available)
-- | --
Edition | (Structr Community Edition)
Modules | core, rest, ui
Licensee | Unlicensed
License Start Date | -
License End Date | -
Database Driver | In-Memory Database Driver

**Given Step to reproduce**
start structr from docker using 4.1-SNAPSHOT tag
use in Memory Database.

**When i open the **security / Ressource access grant** tab** 
**Then the whole page starts to blink endlessly.** 

after selecting the tab it is impossible to use the UI again. even after reloading the page

**Comment by vigorouscoding** [comment]
Thank you for bringing this to our attention and for the perfect bug-report!

I just committed a fix for this.

Until a new build is ready, you should be able to fix the situation by closing the tab and changing the address hash to `#dashboard` in a new tab like so: `http://localhost:8082/structr/#dashboard`.

I'll leave this issue open for the moment - I'd be grateful for you to test this with the new build (should be available in a couple of hours) and close this ticket if it works for you. (Perhaps you'll have to do a hard reload to get rid of cached JavaScript files).

Thanks again for contributing!

**Comment by JusticeN** [comment]
thanks it works now
