### ISSUE TITLE
make cors origin configurable

### ISSUE THREAD

**Issue by mostafa8026** [structr/structr#563]
Could you please make cors origin configurable?

https://github.com/structr/structr/blob/ce690cade0c27f8e6695db5c51b7fde01cb3cede/structr-ui/src/main/java/org/structr/web/auth/UiAuthenticator.java#L171

**Comment by mostafa8026** [comment]
I can't work with the REST api because of the lack of this configuration :(
Do you accept pr?

**Comment by mostafa8026** [comment]
I can't work with the REST api because of the lack of this configuration :(
Do you accept pr?

**Comment by mostafa8026** [comment]
I can't work with the REST api because of the lack of this configuration :(
Do you accept pr?

**Comment by mostafa8026** [comment]
I can't work with the REST api because of the lack of this configuration :(
Do you accept pr?

**Comment by mostafa8026** [comment]
I can't work with the REST api because of the lack of this configuration :(
Do you accept pr?

**Comment by mostafa8026** [comment]
I can't work with the REST api because of the lack of this configuration :(
Do you accept pr?

**Comment by vigorouscoding** [comment]
We already have a plan to make this more configurable - this will hit `main` very soon. Thank you!

**Comment by vigorouscoding** [comment]
This got a little lost - this has been in `main` since e6697c9b217d6c460c0487bc04ba45f766e1d65b... I'll close this now.
