### ISSUE TITLE
Test Smell: it is not a good practice to introduce nondeterministic randomness in test code

### ISSUE THREAD

**Issue by TestSmell** [structr/structr#575]
Hi!

We notice that the random number generator (RNG) is used to produce test code in your project.
For example, a random generator in the test method named ''testStringPropertyUniquenessAgain() '' in ''ValidationTest.java''
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/110402847/185108695-c1e09dee-a72d-4956-8f1a-fd10de4e0eb0.png">

But generating random data in test code is not a good test practice. Since Using randomized data may lead to unexpected unit test failure and once the test case fails, it is hard to trace what test data causes it.

Solution:
There are two solutions:

set a random seed number for your random generator 
using a hash method to generate random data

Besides, we suggest you need to refactor your test cases since they are too long, which may violate the single responsibility principle.

**Comment by cmorgner** [comment]
Thanks for reporting.

The randomness in this case is part of the test, because we want a newly created object to collide with *one* of the existing objects, but we don't care which one.
