### ISSUE TITLE
Dependency on nexus.bedatadriven.com ?

### ISSUE THREAD

**Issue by akbertram** [structr/structr#601]
Hi,
I see that you are depending on our maven repo at nexus.bedatadriven.com, which hosts pre-built jars of R packages for Renjin. I was curious if you were using using Renjin? Otherwise you may not need to depend on our repo.

Thanks,
Alex

**Comment by ckramp** [comment]
Hi Alex,
thanks for your feedback. We indeed still had the repository referenced from when we used to depend on Renjin. Since this is no longer the case, we have now removed the maven repository you mentioned from our dependencies. 
Thank you.

Kind regards,
Christian
