### ISSUE TITLE
Request logging is not charset-safe

### ISSUE THREAD

**Issue by amorgner** [structr/structr#88]
All umlauts are destroyed when full request logging is enabled with `log.requests = true`.

**Comment by vigorouscoding** [comment]
I extensively tested this and came to the following conclusions:

1. Keeping `<charset>UTF-8</charset>` in `etc/logback-access.xml` leads to Umlauts being correctly encoded in the response body (which is only rendered for REST requests and not regular pages). Umlauts are mangled in the request URL and cookies

2. Changing that to `<charset>ISO-8859-1</charset>` has the consequence that the request URLs and cookies are being encoded correctly and that Umlauts in response bodies (for REST requests) get mangled

3. Removing the `<charset>` completely leads to the same effects as described in (1)

I will report if I find a configuration in which either the encoding is consistently wrong or right.

**Comment by amorgner** [comment]
This was fixed a long time ago, closing.
